### ISSUE TITLE
这个项目是否可以在生产使用？

### ISSUE THREAD

**Issue by 13878168026** [openspug/spug#1]
主机的管理能不能支持免密码？？不然每次添加主机验证都是要输入root密码,

**Comment by zyupo** [comment]
你好，项目在我公司线上已经用了差不多一年了，目前没有什么问题，添加的主机只需要第一次输入密码，输完密码平台会进行密钥认证，然后以后批量执行命令、登陆服务器其他操作都是通过密钥的，不需要多次输入密码。运维平台为了安全起见也不保存添加主机的密码。

2018-03-27 8:53 GMT+08:00 13878168026 <notifications@github.com>:

**Comment by vTNT** [comment]
有打算使用ansible吗 @zyupo

**Comment by vTNT** [comment]
@zyupo  demo地址访问不了
