### ISSUE TITLE
请问此项目是个人还是团队开发？

### ISSUE THREAD

**Issue by Zhang21** [openspug/spug#101]
最近在 spug 和 codo 之间选择，想了解项目的后期迭代怎么样。毕竟选择了项目，我就得花时间去看项目源码，做二开。

谢谢！

**Comment by Zhang21** [comment]
我之前写的运维平台是前后端不分离，使用django template和jquery来实现的前端。此项目是不是还得学习如何写React?

**Comment by DaveSteven** [comment]
star不少，说明项目比较成熟，使用的人还是很多的，既然你做二开，发现什么bug也可以修复做贡献呀～
前端是react写的，如果你自己要维护的话，那肯定需要学习一下啦～

**Comment by zyupo** [comment]
Spug有个小团队在维护，后续开发计划可以参考：https://github.com/openspug/spug/projects/1

**Comment by Zhang21** [comment]
谢谢！
