### ISSUE TITLE
请问web如何升级

### ISSUE THREAD

**Issue by kenvin-feng** [openspug/spug#102]
使用manage.py升级后，查看版本，貌似只升级了api。那么web该如何升级呢？

**Comment by zyupo** [comment]
版本升级可以参考：https://www.spug.dev/docs/update-version/

**Comment by kenvin-feng** [comment]
我是参照文档进行的升级，就是升级后还发现api版本已经是3.0了，但是web版本依然是2.6。才来提问的。

**Comment by vapao** [comment]
是用的 `manage.py update` 升级的吗，这个升级会更新 web 的，  你刷新下浏览器试试，可能是缓存。

**Comment by kenvin-feng** [comment]
已成功升级，确实缓存问题。
