### ISSUE TITLE
# BUG # 服务配置修改后，调用接口好像有缓存？

### ISSUE THREAD

**Issue by ChoGathK** [openspug/spug#105]
- docker 安装
- v2.3.0

接口路径：/api/apis/config/
参数:    ?apiKey=HUAS3223SDF&app=demo&env=test&format=json

**Comment by ChoGathK** [comment]
希望这块，开发团队能再压测，或者开放演示账号一起联调下看看

**Comment by vapao** [comment]
我们并不建议把业务代码与配置中心接口强关联，推荐常见的两种方式，每次发布时 从配置中心 读取配置后在内存中缓存，有些没有常驻进程的应用推荐把配置保存成文件的形式，后续从文件中读取配置。
