### ISSUE TITLE
选择主机的时候希望可以加入主机组选项，我批量管理几百台机器，不能一个一个点主机

### ISSUE THREAD

**Issue by wangyancun** [openspug/spug#107]
选择主机的时候希望可以加入主机组选项，我批量管理几百台机器，不能一个一个点主机

**Comment by vapao** [comment]
你说的选择主机是哪个地方的，目前批量执行选择主机是支持按分类筛选后全选的。

**Comment by wangyancun** [comment]
应用发布申请的时候，需要一个一个主机选择，发布应用一般都是一批一批，一个一个选太麻烦了还有目前有没有将批量执行任务的时候，加入审计，像jumpserver一样可以看控制台操作历史




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "vapao"<notifications@github.com&gt;; 
发送时间: 2020年6月5日(星期五) 晚上6:46
收件人: "openspug/spug"<spug@noreply.github.com&gt;; 
抄送: "　　　　　　　　"<1504068285@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [openspug/spug] 选择主机的时候希望可以加入主机组选项，我批量管理几百台机器，不能一个一个点主机 (#107)





 
你说的选择主机是哪个地方的，目前批量执行选择主机是支持按分类筛选后全选的。

**Comment by leonanor98** [comment]
还有监控中心新建监控任务的时候,如果要监控每一台的机器的某个进程,或者自定义监控项来监控每一台机器的同一个项目,机器多的时候需要一个个定义很麻烦

**Comment by cocobear** [comment]
还有任务计划的地方，可以用统一的一个选择主机的组件

**Comment by vapao** [comment]
v3.0.1 已发布欢迎体验
