### ISSUE TITLE
列表显示创建时间字段。

### ISSUE THREAD

**Issue by bruceqiq** [openspug/spug#113]
提个小小的反馈，每个数据列表可否加一列创建时间的字段呢？这样方便查看，列表数据多了，好查找。

**Comment by vapao** [comment]
基本上所有数据表都是按时间倒序排的， 有些数据表已经很多字段了，再增加时间页面会比较乱。

**Comment by vapao** [comment]
很久没收到回复了，先关闭问题了，有需要再打开。
