### ISSUE TITLE
Permission denied 初始化失败

### ISSUE THREAD

**Issue by jeiry** [openspug/spug#114]
root@openmediavault:/home/jeiry# docker exec c0f59dc73618e11f6cc56fb71cc80907a606a2f5ab3951c0aadbf3f6a18852b3 init_spug admin spug.dev
/bin/init_spug: line 7: ./manage.py: Permission denied

Permission denied 初始化失败 为什么？大哥

**Comment by vapao** [comment]
看起来应该是文件没有执行权限，你那获取获取的哪个镜像呢？
可以先执行：
```shell
docker exec c0f59dc73618e chmod +x /bin/init_spug
```
然后在尝试执行。

**Comment by jeiry** [comment]
> 看起来应该是文件没有执行权限，你那获取获取的哪个镜像呢？
> 可以先执行：
> 
> ```shell
> docker exec c0f59dc73618e chmod +x /bin/init_spug
> ```
> 
> 然后在尝试执行。

还是不行，不知道为什么？？ 哎 用不了。

**Comment by jeiry** [comment]
我自己来回答把

先
docker exec cbf63482b8ae python /data/spug/spug_api/manage.py initdb
再
docker exec cbf63482b8ae python /data/spug/spug_api/manage.py user add -u admin -p adminadmin -n 管理员 -s
