### ISSUE TITLE
channels_redis==2.4.1版本安装失败

### ISSUE THREAD

**Issue by maginaro** [openspug/spug#120]
环境：
python版本：3.5.3
pip版本：20.1.1

问题：
pip install -r requirements.txt -i https://pypi.doubanio.com/simple/
安装到这步时，包安装失败，报错如下：
ERROR: Could not find a version that satisfies the requirement channels_redis==2.4.1 (from -r requirements.txt (line 4)) (from versions: 2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.1.0, 2.1.1, 2.2.0, 2.2.1, 2.3.0, 2.3.1, 2.3.2)

**Comment by vapao** [comment]
需要Python 3.6 +

**Comment by maginaro** [comment]
安装python 3.6+之后解决了，👍
