### ISSUE TITLE
关于LDAP问题

### ISSUE THREAD

**Issue by jianjiefang** [openspug/spug#121]
我在系统配置好了LDAP，也测试成功了。
![微信图片编辑_20200610105816](https://user-images.githubusercontent.com/42630557/84222080-4fcb4b80-ab09-11ea-9a17-f5d13310ffdc.jpg)
但是在登录的时候，选在LDAP登录，但是点击登录的时候F12控制台也没报错，就是一直停留在登录页面。过了一会儿连管理员账户都不能登陆了。

**Comment by jianjiefang** [comment]
![image](https://user-images.githubusercontent.com/42630557/84222845-2e6b5f00-ab0b-11ea-9f7c-3a8997f561b7.png)

**Comment by zyupo** [comment]
如果方便，把你后端api日志贴出来一下。

**Comment by jianjiefang** [comment]
![image](https://user-images.githubusercontent.com/42630557/84235918-4f42ad00-ab29-11ea-90a7-4662e80a9afa.png)
@

> 如果方便，把你放在api日志贴出来一下。

**Comment by jianjiefang** [comment]
> 如果方便，把你后端api日志贴出来一下。

你好，再请问下，我看官网说docker安装，使用的是容器内的MySQL。但是我看到我日志里面又报sqlite3.OperationalError: database is locked

**Comment by jianjiefang** [comment]
> docker 安装是使用的 mysql, 你那可以执行下 `docker images` 看下镜像名称和ID。

但是我进入docker容器内，使用mysql命令时，提示我mysql命令不存在。如何查数据库的数据？

**Comment by vapao** [comment]
为了控制镜像的体积，没有安装mysql客户端。

**Comment by jianjiefang** [comment]
> 为了控制镜像的体积，没有安装mysql客户端。
谢谢。您知道LDAP需要如何配置吗？还有就是如何查看数据库的数据？

**Comment by zyupo** [comment]
进入容器后执行：apk add mariadb-client  安装mysql客户端，然后进入mysql后查看数据。

**Comment by zhangwk02** [comment]
我也碰到这个问题
