### ISSUE TITLE
发布出错

### ISSUE THREAD

**Issue by jeiry** [openspug/spug#122]
不创建目录吧，就返回
14:41:46 执行发布...        ln: target '/data/www/' is not a directory: No such file or directory

创建目录吧，就返回
14:44:54 数据准备...        
please make sure the '/data/www/' is not exists.

ssh-key也做好了，就是不帮我创建。有知道为什么的吗？谢谢？

**Comment by vapao** [comment]
能截图发下第一个报错信息吗

**Comment by vapao** [comment]
先关闭这个问题了，如有需要请重新打开。
