### ISSUE TITLE
关于caddy用反向代理将spug挂载到网站二级目录****/spug下的配置问题

### ISSUE THREAD

**Issue by StrangerB** [openspug/spug#123]
## 配置情况：
远程主机端在docker两个容器中分别安装了caddy网页服务器和spug. caddy开了80和443端口，spug开了host模式并将nginx监听端口设置成了6080. caddy上使用反向代理访问spug.

## 问题描述：
之前一直是直接通过网址访问spug,现在想用网址+/spug的方式访问，只修改了caddy的配置，发现并不成功。
## 配置代码
caddy配置：
```
ops.eshipenet.com {
  proxy /spug 172.17.0.1:6080 {
    without /spug
  }
  gzip
  log
}
```
spug容器下的nginx配置:
```
server {
        listen 6080 default_server;
        error_log /var/log/nginx/debug.log debug;
        root /data/spug/spug_web/build/;
        location ^~ /api/ {
                rewrite ^/api(.*) $1 break;
                proxy_pass http://127.0.0.1:9001;
                proxy_redirect off;
                proxy_set_header X-Real-IP $remote_addr;
        }
        location ^~ /api/ws/ {
                rewrite ^/api(.*) $1 break;
                proxy_pass http://127.0.0.1:9002;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "Upgrade";
                proxy_set_header X-Real-IP $remote_addr;
        }
        error_page 404 /index.html;
}
```
## access日志
输入网址`https://ops.eshipenet.com/spug`，输出日志：
`2020:12:54:54 +0800] "GET / HTTP/1.1" 200 3085 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36" "183.141.23.237"` 从访问日志可以看出caddy服务器将`https://ops.eshipenet.com/spug`中的`/spug`部分切割后才将网址传给了nginx服务器。因为没有设置caddy中的`without /spug`并将`proxy /spug`改为`proxy /`输出日志为：
` "GET /api/notify/ HTTP/1.1" 200 25 "https://ops.eshipenet.com/spug" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36" "183.141.23`
## 网页显示
![Screen Capture_select-area_20200611130917](https://user-images.githubusercontent.com/23401104/84349578-2b936b80-abea-11ea-8a4b-62452c945d2e.png)

**Comment by vapao** [comment]
前端会使用浏览器地址栏的url，当你访问 `/spug` 的时候前端项目内并没有这个路由，所以会报你发的图的错误， 你这个可能需要把路由模式更改为 `HashRouter` 模式，需要重新编译前端。

**Comment by StrangerB** [comment]
> 前端会使用浏览器地址栏的url，当你访问 `/spug` 的时候前端项目内并没有这个路由，所以会报你发的图的错误， 你这个可能需要把路由模式更改为 `HashRouter` 模式，需要重新编译前端。

可以告诉我是那个配置文件吗，我新手上路......

**Comment by vapao** [comment]
`spug_web/src/index.js` 第8行改为 `import { HashRouter as Router } from 'react-router-dom';`
`spug_web/src/libs/history.js` 内容修改为
```python
import {createHashHistory} from 'history';

export default createHashHistory()
```
修改完后重新编辑下前端。

**Comment by StrangerB** [comment]
> `spug_web/src/index.js` 第8行改为 `import { HashRouter as Router } from 'react-router-dom';`
> `spug_web/src/libs/history.js` 内容修改为
> 
> ```python
> import {createHashHistory} from 'history';
> 
> export default createHashHistory()
> ```
> 
> 修改完后重新编辑下前端。

可以告诉我如何编译吗，网上没查到关于js编译的方法。

**Comment by vapao** [comment]
前端需要先安装依赖包，流程大概是这样子：
```shell
cd /data/spug/spug_web
npm install --registry=https://registry.npm.taobao.org
npm run build
```

**Comment by StrangerB** [comment]
> 前端需要先安装依赖包，流程大概是这样子：
> 
> ```shell
> cd /data/spug/spug_web
> npm install --registry=https://registry.npm.taobao.org
> npm run build
> ```

好的

**Comment by StrangerB** [comment]
> > 前端需要先安装依赖包，流程大概是这样子：
> > ```shell
> > cd /data/spug/spug_web
> > npm install --registry=https://registry.npm.taobao.org
> > npm run build
> > ```
> 
> 好的

我感觉我陷入了泥潭，编译后还是没有访问成功，页面空白，错误信息如下
![Screen Capture_select-area_20200615141448](https://user-images.githubusercontent.com/23401104/84624065-3bc18880-af13-11ea-8c58-ab28f80177c7.png)
网上没有搜到`text/plain`错误,倒是有`text/html`的错误报告，关于`text/html`有两种说法，一种是格式问题，另一种是路径出错，感觉都不像。点开其中一个文件的详细错误信息如下
![Screen Capture_select-area_20200615141631](https://user-images.githubusercontent.com/23401104/84624417-e89c0580-af13-11ea-9e23-97e4883fd05c.png)
文件所在终端路径如下：
![Screen Capture_select-area_20200615141754](https://user-images.githubusercontent.com/23401104/84624442-f5b8f480-af13-11ea-9e00-887d8237e842.png)
其他配置文件除了之前讲的没有改动过。

**Comment by StrangerB** [comment]
好像不是这个原因，这个问题好像是前端代码内部网页跳转的时候并没有加上/spug前缀，导致反向代理服务器根本识别不了导致的，我还是吧这个问题关了吧

**Comment by qfilsdv731** [comment]
```conf
    # spug
    location /spug/ {
        rewrite  ^/spug/(.*)  /$1 break;
        proxy_set_header Host $host;
        proxy_pass http://192.168.1.1:8080;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        sub_filter_types *;
        sub_filter_once off;
        sub_filter '/static/' '/spug/static/';
    }
```
这么配置页面出来了，但是显示 404，看了上面回答需要自己再编译，就有点麻烦了，@vapao 能否添加相关配置来改变路由方式呢？
