### ISSUE TITLE
新建主机，输入ssh的密码时，提示这个错误，怎么解决？

### ISSUE THREAD

**Issue by hyhweb** [openspug/spug#127]
Exception: add public key error: b'bash: line 1: /root/.ssh/authorized_keys: Permission denied\n'

**Comment by vapao** [comment]
看下/root/.ssh/authorized_keys 这个文件的权限，如果没有这个文件的话 看下 /root/.ssh 这个目录的权限。

**Comment by hyhweb** [comment]
这个问题解决了，主要是这个文件被加了个 i的属性。所以写入不了。导致报错。
