### ISSUE TITLE
执行任务时，无法识别到java命令。报错如下

### ISSUE THREAD

**Issue by hyhweb** [openspug/spug#128]
nohup: failed to run command ‘java’: No such file or directory

**Comment by vapao** [comment]
确定系统里有java 的把，把完整的命令发下看看。

**Comment by hyhweb** [comment]
在docker 安装spug后，执行主机是有安装java的，但在执行任务的执行命令里面写入java。是识别不了java命令。应该是容器里面没有没有安装java导致的。有没有办法识别到执行主机的这些命令？

**Comment by vapao** [comment]
重复 #131
