### ISSUE TITLE
#主机管理#批量导入后，无法使用console，提示Connection is closed

### ISSUE THREAD

**Issue by longhu735** [openspug/spug#129]
在刚部署完spug后，使用主机管理导入首批服务器后，进行console时，
界面显示
Connecting ...
Exception: Authentication failed.

Connection is closed.

但是删除这些服务器手动单独添加一台，则无此问题，同时再使用批量导入主机功能，则无问题

**Comment by vapao** [comment]
感谢反馈，我们会尽快测试并确认这个问题。

**Comment by vapao** [comment]
我们进行了测试但无法复现这个问题。

**Comment by longhu735** [comment]
> 我们进行了测试但无法复现这个问题。

我周一再验证下

**Comment by longhu735** [comment]
> > 我们进行了测试但无法复现这个问题。
> 
> 我周一再验证下
我这边验证了 没有问题，实在不好意思，可能是当时的本地环境哪里出了问题
