### ISSUE TITLE
你好，我遇到了添加主机的问题。

### ISSUE THREAD

**Issue by 522247020** [openspug/spug#13]
我通过docker 在虚拟机部署完毕后，可以正常打开网页，在主机管理里面我添加单条主机不能成功，里面的连接主机docker的地址，我添加为虚拟机的IP不能成功，docker的2375端口映射为主机的2375端口也不能成功提示信息为： 
“获取扩展信息失败，请检查docker是否可以正常连接“
在网站上没有找到相关说明。
![编辑主机](https://user-images.githubusercontent.com/38172233/61102582-03aefb80-a4a1-11e9-9d2b-635cccc80bd4.png)
![链接失败](https://user-images.githubusercontent.com/38172233/61102583-03aefb80-a4a1-11e9-845b-71bae4d8a2cf.png)

**Comment by zyupo** [comment]
你进入spug的docker容器内，telnet 192.168.192.199 2375 看看是否可以添加的ip 和端口是否可以正常通信。确认一下docker内部网络和你添加的主机网络可以正常通信就不会报错。
