### ISSUE TITLE
#新功能建议#关于项目发布及项目编译的优化

### ISSUE THREAD

**Issue by longhu735** [openspug/spug#130]
1、【应用管理】-【新建发布】建议增加默认分支，避免在新建发布申请时，误选分支
2、进行任务发布时，是否可以将项目编译及部署分开
可解决如下问题：
a:提前编译可以避免正在系统上线时出现编译故障，降低上线时意外情况的发生
b:针对编译时间较长的项目，可以提前进行操作，到上线窗口时，直接进行部署，节省上线时长
3、在进行项目部署完成后的消息通知内容，建议加上线申请的标题

**Comment by vapao** [comment]
感谢你的建议，关于你说的两个问题
第1个问题：首次选择后，后边的新建的时候会默认使用上一次选择的分支。
第2个问题：关于提前编译这个需求个人感觉很有用，我们会内部讨论评估如何优雅的实现，关于消息通知也是很好的建议，我们会尽快上线。

**Comment by longhu735** [comment]
在你们设计问题2的方案时，希望可以加入对项目部署的时间管控，该限制的目的是控制上线时间点，避免提前上线。
当然基于此也可以扩展，可利用本身已有的应用监控功能，实现预约式的上线部署，可以不用运维人员手工操作，通过钉钉或微信消息推送即可知道项目的部署情况。

建议4、希望在【应用发布】-【应用管理】查询时，增加描述信息的查询，这个功能会很有用的  @vapao

**Comment by vapao** [comment]
v3 版本已发布欢迎体验
