### ISSUE TITLE
在spug容器里面安装jdk，配置好java相关的变量后，无法识别java命令

### ISSUE THREAD

**Issue by hyhweb** [openspug/spug#131]
1，jdk存放的路径：

/usr/local/jdk # pwd
/usr/local/jdk
/usr/local/jdk # ls -ls
total 25992
     4 -r--r--r--    1 root     root          3244 Oct  6  2018 COPYRIGHT
     4 -r--r--r--    1 root     root            40 Oct  6  2018 LICENSE
     4 -r--r--r--    1 root     root           159 Oct  6  2018 README.html
   108 -rw-r--r--    1 root     root        108062 Sep 12  2018 THIRDPARTYLICENSEREADME-JAVAFX.txt
   152 -r--r--r--    1 root     root        155003 Oct  6  2018 THIRDPARTYLICENSEREADME.txt
     4 drwxr-xr-x    2 root     root          4096 Oct  6  2018 bin
     4 drwxr-xr-x    3 root     root          4096 Oct  6  2018 include
  5088 -rw-r--r--    1 root     root       5207154 Sep 12  2018 javafx-src.zip
     4 drwxr-xr-x    5 root     root          4096 Oct  6  2018 jre
     4 drwxr-xr-x    5 root     root          4096 Oct  6  2018 lib
     4 drwxr-xr-x    4 root     root          4096 Oct  6  2018 man
     4 -rw-r--r--    1 root     root           424 Oct  6  2018 release
 20608 -rw-r--r--    1 root     root      21101479 Oct  6  2018 src.zip

,2，打印$PATH:
cbbbff802c2b:/usr/local/jdk# echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/jdk/bin:/usr/local/jdk/jre/bin

3,查看env:
cbbbff802c2b:/usr/local/jdk# env
HOSTNAME=cbbbff802c2b
PYTHON_PIP_VERSION=20.1.1
SHLVL=1
HOME=/root
OLDPWD=/usr/local/jdk/bin
JRE_HOME=/usr/local/jdk/jre
GPG_KEY=0D96DF4D4110E5C43FBFB17F2D347EA6AA65421D
PAGER=less
PS1=\h:\w\$ 
PYTHON_GET_PIP_URL=https://github.com/pypa/get-pip/raw/eff16c878c7fd6b688b9b4c4267695cf1a0bf01b/get-pip.py
TERM=xterm
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/jdk/bin:/usr/local/jdk/jre/bin
LANG=C.UTF-8
PYTHON_VERSION=3.6.10
CLASSPATH=.:/usr/local/jdk/lib:/usr/local/jdk/jre/lib:
PWD=/usr/local/jdk
JAVA_HOME=/usr/local/jdk
PYTHON_GET_PIP_SHA256=b3153ec0cf7b7bbf9556932aa37e4981c35dc2a2c501d70d91d2795aa532be79
TZ=Asia/Shanghai
JAVA_PATH=/usr/local/jdk/bin:/usr/local/jdk/jre/bin
4,使用java命令，报错无法找到：
cbbbff802c2b:/usr/local/jdk# java -version
sh: java: not found

**Comment by vapao** [comment]
使用绝对路径可以执行吗，例如： `/usr/local/jdk/bin/java -version`

**Comment by hyhweb** [comment]
/usr/local/jdk/bin/java -version
这样执行也是同样的报错，之前提issues的时候就试过了。

**Comment by wangbaocongnb** [comment]
把```java```配置写到```/etc/profile```或者```~/.bash_profile```下
执行命令前加上
```
source /etc/profile
或者
source ~/.bash_profile
```

再或者:
```
ln -sf /usr/local/jdk/bin/java /usr/bin/java
ln -sf /usr/local/jdk/bin/javac /usr/bin/javac
```

**Comment by hyhweb** [comment]
以上的方法都已经尝试过了。还是报错java: not found。之前试过把这个jdk安装在其他的容器里面，是可以正常运行java命令的。好奇怪的问题。

**Comment by vapao** [comment]
可以参考这个文档安装 https://spug.dev/docs/example-java/

**Comment by vapao** [comment]
很久没收到回复，先关闭这个问题了，如有需要再打开。
