### ISSUE TITLE
Exception: NOAUTH Authentication required.

### ISSUE THREAD

**Issue by huanjoyous** [openspug/spug#132]

**Comment by huanjoyous** [comment]
问题描述:
本地运行，执行任务报错
![image](https://user-images.githubusercontent.com/28851617/85228241-fe7a6080-b414-11ea-974b-995730a3d3c5.png)
![image](https://user-images.githubusercontent.com/28851617/85228242-ff12f700-b414-11ea-9933-6c461a131eed.png)

**Comment by vapao** [comment]
看报错信息应该是 `redis` 应该不需要密码， 但你配置了密码。

**Comment by vapao** [comment]
很久没收到回复，暂时关闭问题，如有需要请再打开。
