### ISSUE TITLE
#BUG 发布目标为多台主机时, 状态和日志无法显示

### ISSUE THREAD

**Issue by xhcnb** [openspug/spug#133]
使用docker安装的v2.3.3版本
应用发布目标为单目标主机时一切正常
当发布目录为多台主机时, 表现为发布正常, 但是状态页面显示"发布中"
从列表点进去, 依然显示 "发布中" 
从chrome调试窗口可以看到接口?/log=1 返回的是"发布成功" , 但是UI没有更新

**Comment by xhcnb** [comment]
尝试刷新这种页面会报错误

`GET https://spug.xxx.com/deploy/do/ext1/21/1 404`
`main.5e5ff086.chunk.js:1 Uncaught (in promise) TypeError: Cannot read property 'scrollIntoView' of undefined
    at t.a._parse_message (main.5e5ff086.chunk.js:1)
    at main.5e5ff086.chunk.js:1
a._parse_message @ main.5e5ff086.chunk.js:1
(anonymous) @ main.5e5ff086.chunk.js:1
XMLHttpRequest.send (async)
(anonymous) @ 2.eb62fa2b.chunk.js:1
e.exports @ 2.eb62fa2b.chunk.js:1
e.exports @ 2.eb62fa2b.chunk.js:1
Promise.then (async)
c.request @ 2.eb62fa2b.chunk.js:1
r.forEach.c.<computed> @ 2.eb62fa2b.chunk.js:1
(anonymous) @ 2.eb62fa2b.chunk.js:1
fetch @ main.5e5ff086.chunk.js:1
value @ main.5e5ff086.chunk.js:1
jc @ 2.eb62fa2b.chunk.js:1
t.unstable_runWithPriority @ 2.eb62fa2b.chunk.js:1
Go @ 2.eb62fa2b.chunk.js:1
Rc @ 2.eb62fa2b.chunk.js:1
wc @ 2.eb62fa2b.chunk.js:1
mc @ 2.eb62fa2b.chunk.js:1
ol @ 2.eb62fa2b.chunk.js:1
(anonymous) @ 2.eb62fa2b.chunk.js:1
Sc @ 2.eb62fa2b.chunk.js:1
ul @ 2.eb62fa2b.chunk.js:1
render @ 2.eb62fa2b.chunk.js:1
640 @ main.5e5ff086.chunk.js:1
p @ 1:1
348 @ main.5e5ff086.chunk.js:1
p @ 1:1
l @ 1:1
e @ 1:1
(anonymous) @ main.5e5ff086.chunk.js:1`

**Comment by xhcnb** [comment]
研究了一下js, 找到一个workaround
删除了main.5e5ff086.chunk.js 中的
'a.elements[t].scrollIntoView()'
没有滚动效果了, 但是可以使用了

**Comment by vapao** [comment]
问题已确认，感谢反馈。 我们会尽快发布 `v3.3.4` 修复该问题。

**Comment by vapao** [comment]
`v2.3.4` 已发布，请参考 [https://spug.dev/docs/update-version/](https://spug.dev/docs/update-version/) 升级至新版，如有问题可以再次打开该问题。
