### ISSUE TITLE
可否支持针对不同apm(skywalking,pinpoint)等的webhook的支持

### ISSUE THREAD

**Issue by suntianxian** [openspug/spug#136]
可否支持针对不同apm(skywalking,pinpoint)等的webhook的支持,并且设置模版进行报警？
并且按照一定规则@到不同人

**Comment by vapao** [comment]
目前监控中心设计的比较轻量级能满足基本的需求，会把开发重点放在发布方面。

**Comment by vapao** [comment]
长时间没有收到回复，暂时关闭问题，如有需要请再次打开。
