### ISSUE TITLE
账号禁用能否改为限制一段时间（如30分钟），而不要一直禁用！

### ISSUE THREAD

**Issue by smally84** [openspug/spug#145]
密码不小心输错被禁用，发现会一直禁用，可能在实际过程中不太方便。
建议改为：输错一定次数，禁用账号（30分钟，也可以更长如一天，也可以将这个时间作为系统配置）。然后禁用时间到期后，允许用户再尝试一次，如果还是输错，继续禁用，依次类推……

**Comment by vapao** [comment]
这个限制出发点是安全性，**连续** 3 次错误才会禁用账户，这个在实际正常使用中被触发的概率并不大。

**Comment by winglight** [comment]
> 这个限制出发点是安全性，**连续** 3 次错误才会禁用账户，这个在实际正常使用中被触发的概率并不大，且这是个面向公司内部的系统，并非面向 C 端用户的。

现在我这里，admin被禁用了，怎么恢复呢？这种设定，很容易被攻击呀，随便谁尝试三次登录就能永久锁定admin

**Comment by vapao** [comment]
https://spug.cc/docs/system-account  参考这个文档启用账户。
