### ISSUE TITLE
请教在线终端的代码入口在哪

### ISSUE THREAD

**Issue by ADAM-CT** [openspug/spug#147]
我想在我的项目中引入你们的在线终端解决方案，能否提供代码入口以及思路，感谢

**Comment by vapao** [comment]
具体代码或涉及的比较多，用到主要技术点： `paramiko`、`websocket` 前端使用的 `xtermjs`。

**Comment by vapao** [comment]
涉及相关主要文件：
[spug_api/consumer/consumers.py](https://github.com/openspug/spug/blob/master/spug_api/consumer/consumers.py) 
[spug_web/src/pages/ssh/index.js](https://github.com/openspug/spug/blob/master/spug_web/src/pages/ssh/index.js)

**Comment by ADAM-CT** [comment]
感谢您的回答！还有一个问题，只需要第一次输密码以后不需要输入密码，这是怎么实现的？



---原始邮件---
发件人: "vapao"<notifications@github.com&gt;
发送时间: 2020年7月10日(周五) 下午4:59
收件人: "openspug/spug"<spug@noreply.github.com&gt;;
抄送: "ADAM-CT"<489262602@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [openspug/spug] 请教在线终端的代码入口在哪 (#147)




 
具体代码或涉及的比较多，用到主要技术点： paramiko、websocket 前端使用的 xtermjs。

**Comment by zyupo** [comment]
第一次输入密码会对服务器进行密钥认证，认证通过后，使用密钥对服务器进行管理，就不需要密码了。
