### ISSUE TITLE
win 下，初始化数据库会报错，主要是ldap安装报错

### ISSUE THREAD

**Issue by Weightang** [openspug/spug#149]
建议使用ldap3 看能不能代替下

**Comment by Weightang** [comment]
python 版本 3.8

**Comment by zyupo** [comment]
window环境暂时不支持，没有做过兼容性测试，后续会增加window兼容支持。

**Comment by Weightang** [comment]
😂都安装到大部分依赖库了，就差ldap没过去，算了，我先看能不能改下源码 去掉ldap验证

**Comment by Weightang** [comment]
那也麻烦下在标准安装中，备注下吧，不支持window 环境
