### ISSUE TITLE
gave up: nginx entered FATAL state, too many start retries too quickly

### ISSUE THREAD

**Issue by 18898359289** [openspug/spug#150]
docker容器安装的spug ，在deepin系统上重启docker容器，容器内部的ngxin启动失败
错误：gave up: nginx entered FATAL state, too many start retries too quickly
同样的容器，在ubuntu20 上没有问题
手动执行 docker exec spug bash -c "/usr/sbin/nginx &" 是可以成功启动内部nginx的，但是不可能每次宿主机重启后都要去手动启动一下，不知道这个可能是什么原因？如何解决

**Comment by zyupo** [comment]
抱歉，我们只在Centos 和Ubuntu上做了测试，深度操作系统暂未测试验证，这个问题似乎跟深度操作系统有关。你找到解决办法后，也帮忙在这里回复一下。
