### ISSUE TITLE
主机管理文件管理器能否支持文件夹上传

### ISSUE THREAD

**Issue by peach7orange** [openspug/spug#152]
主机管理文件管理器能否支持文件夹上传

**Comment by vapao** [comment]
目前还没有完美的解决方法，你可以先通过压缩包的形式上传目录。

**Comment by FSSlc** [comment]
可以参考一下 https://stackoverflow.com/a/46009260 来使用 paramiko 上传目录，但需求前端支持文件夹的上传。。
