### ISSUE TITLE
批量执行的任务卡住无法看到执行输出 主机管理点进入Console连接上主机后马上 Connection is closed.

### ISSUE THREAD

**Issue by ChobitsSP** [openspug/spug#153]
spug使用生产环境安装部署
使用frp从内网穿透spug站点

```
操作系统Linux-3.10.0-1062.9.1.el7.x86_64-x86_64-with-centos-7.8.2003-Core
Python版本3.6.8
Django版本2.2.13
Spug API版本v2.3.5
Spug Web版本v2.3.5
```

frpc客户端配置

```
[spug]
type = http
local_ip = 127.0.0.1
local_port = 80
use_encryption = false
use_compression = true
custom_domains = spug.test.net
```

主机管理点进入Console连接上主机后马上 Connection is closed.

![image](https://user-images.githubusercontent.com/4433217/87867404-04854200-c9bf-11ea-9636-c53742bbfba5.png)

如果是websocket问题 能否自定义修改websocket模式为polling 或者自定义请求websocket的域名端口

**Comment by vapao** [comment]
看下浏览器的开发者工具里是否有报错信息，目前只能通过改源码修改websocket域名端口

**Comment by ChobitsSP** [comment]
> 看下浏览器的开发者工具里是否有报错信息，目前只能通过改源码修改websocket域名端口

批量执行没有报错 连接主机在Connection is closed.后会有WebSocket is already in CLOSING or CLOSED state.的错误
并且此页面返回httpcode为404 GET http://xxxxx:8081/ssh/5 404 (Not Found) 但是并不影响访问

![84MKFLB U)77CWSP@T4F9%C](https://user-images.githubusercontent.com/4433217/87905588-8a72bd00-ca93-11ea-9fac-1b8dcc8d639e.png)
![$8P){K5SWF7V`LH0A4Q61{E](https://user-images.githubusercontent.com/4433217/87905594-8e9eda80-ca93-11ea-9350-34e761f64e14.png)

**Comment by vapao** [comment]
最终解决了吗，跳过 frp 直接访问是否正常？

**Comment by vapao** [comment]
长时间没有收到回复，暂时关闭这个问题，如有需要请再打开。

**Comment by huchuansai** [comment]
检查一下nginx的websocket链接问题
