### ISSUE TITLE
任务执行bug，当命令执行返回状态非0时，直接退出

### ISSUE THREAD

**Issue by siyiys** [openspug/spug#155]
任务执行bug，当命令执行返回非0时，直接退出。
如进行一个页面的健康检查，当健康检查失败时，重启应用。
当页面检查失败时，这个就执行不了，在状态码处就直接退出了。
#!/bin/bash
set -o xtrace
############健康检查脚本###################
health_check (){
CODE=`curl  -s  -w "%{http_code}\\n"   --connect-timeout 5  http://192.168.1.100:8080/ping  -o /dev/null `
if [ $CODE -eq 200 ];then
  echo 'app was ok'
else
  echo 'app was down,restart app'
  bash /opt/tomcat/bin/start.sh
fi
}
##########end 健康检查脚本###################

health_check
set +o xtrace

-------------------
输出：
+ health_check
++ curl -s -w '%{http_code}\n' --connect-timeout 5 http://192.168.1.100:8080/ping -o /dev/null
+ CODE=000
到这来就直接退出去了。未往下执行。

操作系统Linux-3.10.0-1127.13.1.el7.x86_64-x86_64-with-centos-7.8.2003-Core
--
Python版本3.6.8
Django版本2.2.13
Spug API版本v2.3.6
Spug Web版本v2.3.6

**Comment by vapao** [comment]
👍 很棒的问题反馈，版本什么的都贴了出来。 
状态非0直接退出是 `Spug` 的默认行为，你可以在自定义的命令开头写上 `set +e` 来禁用这一特性，例如：
```
set +e
set -o xtrace
############健康检查脚本###################
health_check (){
CODE=curl -s -w "%{http_code}\\n" --connect-timeout 5 http://192.168.1.100:8080/ping -o /dev/null
if [ $CODE -eq 200 ];then
echo 'app was ok'
else
echo 'app was down,restart app'
bash /opt/tomcat/bin/start.sh
fi
}
##########end 健康检查脚本###################

health_check
set +o xtrace
```

**Comment by siyiys** [comment]
收到，谢谢
