### ISSUE TITLE
自定义发布功能建议-附件

### ISSUE THREAD

**Issue by SilenceDN** [openspug/spug#156]
使用常规发布可以使用git仓库，但是像我们git仓库是内网，平时发布时都是打包然后上传更新。
但是自定义里面只能执行命令，不能执行上传文件就很有局限性啊，发布和上传还要分开搞
强裂建议加一个😁

**Comment by vapao** [comment]
嗯，自定义发布会增加一个内置的文件分发动作。

**Comment by wangbaocongnb** [comment]
我公司也是这样，后来自己改了下代码。。。好了

**Comment by vapao** [comment]
v2.3.7 已添加，可以更新至该版本体验。

**Comment by SilenceDN** [comment]
> v2.3.7 已添加，可以更新至该版本体验。

我已经更新了，但是发现好像仍然是跟之前的差距不大，对于使用者来讲只不过上传文件动作目标由目标主机转为容器主机，任然有手动上传到服务器的这种操作，我希望在发布时在发布界面就能传文件比如像这样的一种形式（使用者不用去打开ftp或者自带的web控制台去传, 这样可见减少非专业人士的误操作，比如服务器的后台只允许部分人去登录，但是其他开发者有部署的权限，通过这种方式就可以避免）:
![image](https://user-images.githubusercontent.com/16896067/89095281-f4c61e80-d3fe-11ea-80b1-2b6caf2446ec.png)

**Comment by vapao** [comment]
嗯，这也是种方式，在 2.3.7 种添加的数据传输考虑的场景是比如项目是 svn 管理的，在发布过程种通过 SPUG_RELEASE 指定版本，在发布动作内根据这个版本检出代码，然后通过新增的数据传输动作把代码传输至目标主机。
你数的这个是在新建发布申请时就把要更新的代码打包一起上传，在发布过程中把上传的代码传至目标主机是这样吧？

**Comment by SilenceDN** [comment]
> 嗯，这也是种方式，在 2.3.7 种添加的数据传输考虑的场景是比如项目是 svn 管理的，在发布过程种通过 SPUG_RELEASE 指定版本，在发布动作内根据这个版本检出代码，然后通过新增的数据传输动作把代码传输至目标主机。
> 你说的这个是在新建发布申请时就把要更新的代码打包一起上传，在发布过程中把上传的代码传至目标主机是这样吧？

是的，在发布过程上传代码

**Comment by vapao** [comment]
这是一种更灵活更通用的发布方式，我们会在 2.3.8 版本中更新， 感谢你的建议。

**Comment by vapao** [comment]
你对自定义发布的回滚实现，有什么建议吗？

**Comment by SilenceDN** [comment]
我觉得可以在发布时有可勾选的选项(保留本次发布文件-用于回滚)，回滚自由度交给用户。 发布主机保留当前发布文件，回滚时直接将这次发布对应的文件回滚就行，还可以增加一个清除历史发布文件的功能。这是目前我能想到的使用场景

**Comment by vapao** [comment]
2.3.8 已经发布，新增了上传自定义数据的功能，默认保留每个发布配置最近10次的文件，超过会自动删除。

**Comment by YJiWei** [comment]
两位大佬好，支持多大的文件上传呢？有大小限制吗？

**Comment by YJiWei** [comment]
我测试了一下，好像上传几十M的压缩包就会失败，请问大佬是哪里没配置对吗？盼回复

**Comment by vapao** [comment]
@YJiWei  重复 #177
