### ISSUE TITLE
添加云主机时遇到报错 Exception: list index out of range

### ISSUE THREAD

**Issue by li55626437** [openspug/spug#157]
添加主机遇到这个问题该怎么解决呢，用的是阿里云ecs。我把spug主机的公钥放在目标机器上去了，因为我们没有用到密码登录。
![QQ截图20200721161019](https://user-images.githubusercontent.com/52647808/88029932-30462a80-cb6d-11ea-8807-a2f7fa1c0ac9.png)

**Comment by vapao** [comment]
你看下 `系统管理 / 系统设置 / 密钥设置` 确保里边有合法的密钥对，记得修改保存后重启服务。
如果还有问题麻烦发下日志： `/data/spug/spug_api/logs/api.log`

**Comment by vapao** [comment]
长时间没有收到回复，暂时关闭问题，如有需要请再次打开。
