### ISSUE TITLE
部署一直报错

### ISSUE THREAD

**Issue by tianyouyuyu** [openspug/spug#159]
按照官网的文档部署，docker方式和一键部署方式成功，但是无法访问；尝试手动部署，结果一直数据库初始化报错，依赖也没有问题。

**Comment by tianyouyuyu** [comment]
docker部署方式显示镜像运行，但是却访问不通；一键部署方式也显示脚本全执行成功了，但是也是访问不了（另外一键部署是不是也访问80端口呢？我看文档里没写，就按80端口访问的）

**Comment by tianyouyuyu** [comment]
好像是我使用ubuntu系统的原因，看来还是得用centos系统

**Comment by vapao** [comment]
请发下具体的报错信息

**Comment by vapao** [comment]
长时间没有收到回复，暂时关闭问题，如有需要请再次打开。
