### ISSUE TITLE
Feat: 希望增加新 全局变量 适配更加宽泛的项目种类

### ISSUE THREAD

**Issue by Vndroid** [openspug/spug#162]
## 背景

目前使用 Spug 进行 PHP 项目的部署工作，但是发现存在通用的配置文件无法默认迁移至新环境中，回滚等操作也存在此类问题。

## 建议

希望增加新的全局变量，用于标记部署新版本前的当前「部署路径」，这样即可在「应用发布前执行」块中使用命令将当前环境使用的配置文件备份到指定目录，部署后将配置文件移回的操作。

或者直接提供「应用发布保留内容」功能，在项目部署前将「旧环境」中指定列表内的文件（比如配置文件等）移动至「新环境」的相同目录结构中。

**Comment by vapao** [comment]
部署新版本前的当前「部署路径」，这个路径其实就是创建发布配置时第2步设置的 目标主机部署路径， 这个大部分场景下是固定的，所以之前没有考虑把这个作为一个全局变量。 但如果考虑发布配置的通用性的话用变量来代替会好点，我们会在 v2.3.8 版本添加这个变量，感谢你的使用建议。

**Comment by vapao** [comment]
`v2.3.8` 已发布。
