### ISSUE TITLE
开放api无法使用

### ISSUE THREAD

**Issue by scfobao** [openspug/spug#164]
使用docker部署,
操作系统Linux-4.15.0-96-generic-x86_64-with-centos-7.8.2003-Core
Python版本3.6.8
Django版本2.2.13
Spug API版本v2.3.7
Spug Web版本v2.3.7
官网文档https://spug.dev
更新日志https://spug.dev/docs/change-log/

--
别的都很正常，就是curl "http://XXXXX/api/apis/config/?apiKey=cCeGKBFlJ1AnyXso&app=order&env=2134234"
返回结果如下
HTTP/1.1 400 Bad Request
Invalid params

**Comment by vapao** [comment]
请检查所传的三个参数，app 和 env 分别是应用和环境的标识符， apiKey 为 系统管理/系统设置/开放服务设置 中的访问凭据。
三个参数任何一个有问题都会是这个错误。

**Comment by scfobao** [comment]
谢谢，是我理解错了。现在可以了
