### ISSUE TITLE
主机管理中增加公网IP服务器报错

### ISSUE THREAD

**Issue by dsxlinux** [openspug/spug#165]
请问是否只能添加内网IP，公网地址不支持？另外，内网有些服务器只支持秘钥登录，不支持密码方式登录，是否可以支持下秘钥登录。感谢！

**Comment by vapao** [comment]
[https://spug.dev/docs/host-manage/](https://spug.dev/docs/host-manage/) 先看下这个文档

**Comment by dsxlinux** [comment]
感谢您的回复。在主机管理中新建主机，IP是公网地址，点击【验证】时报错：【Exception: No existing session】，不支持公网IP吗？添加的内网服务器都成功了。

**Comment by vapao** [comment]
只要能确保通过部署 spug 的容器或主机能够 正常通过ssh 连目标主机就可以。
