### ISSUE TITLE
如何上传私钥？

### ISSUE THREAD

**Issue by CL545740896** [openspug/spug#166]
Spug 版本:

## 问题重现步骤

1.
2.

**Comment by CL545740896** [comment]
找到了上传私钥  但是私钥是加密的 怎么处理？

**Comment by vapao** [comment]
系统管理 / 系统设置 / 密钥设置

**Comment by CL545740896** [comment]
> 系统管理 / 系统设置 / 密钥设置

私钥是有密码的 怎么处理

**Comment by vapao** [comment]
可以自己生成无密码的密钥对， 也可以不填写，再添加主机时 spug 会自动生成。
