### ISSUE TITLE
SPUG_APP_NAME全局变量解释

### ISSUE THREAD

**Issue by wenchengxu** [openspug/spug#169]
您好，在全局变量中，有一个 SPUG_APP_NAME（发布应用的名称），想问下这个变量是否与应用管理里面的应用名称或唯一标识符相关联，如果不是，请问是什么含义呢？ 我想获取项目的名称

**Comment by vapao** [comment]
是应用管理里面的应用名称，所有变量都可以在发布的hook内通过 echo 打印出来看看。
