### ISSUE TITLE
多个密钥问题

### ISSUE THREAD

**Issue by soonio** [openspug/spug#170]
当前状态：在使用spug的时候，可以上传单个密钥到spug，也可以在初次登录的时候，让spug自动创建一个密钥对
实际需求：当前密钥只有一对，而我的服务器有很多组，比如内网机器10台-密码登录，具体业务A机器3台-密钥A登录，具体业务B机器3台-密钥B登录，...
那么我如何让spug同时管理我这多组认证需求不通的多台服务器呢？

之前也看到很多人提issue，但都被关闭了，没有真正解决问题。

**Comment by vapao** [comment]
2.3.9 版本可以给主机设置独立的密钥，预计本周内发布。
