### ISSUE TITLE
此项目是否安全

### ISSUE THREAD

**Issue by endachao** [openspug/spug#174]
实在是 walle 安装不了，发现这个项目，发现安装简单，配置也简单，就是有点担心

1. 必须部署在公网吗？
2. 发现把 公钥、私钥都添加进去了，会不会有漏洞导致公钥与私钥泄露的风险？
3. 有什么安全措施吗？

**Comment by zyupo** [comment]
1、不是必须，可以部署在内网，不过你想通过邮件，微信报警，需要部署的内网服务器有链接外网的权限。
2、公钥和私钥都是添加在你自己都服务器上，源码也都公开，而且部署在你内网服务器，所以不需要担心密钥泄漏问题。
3、建议你部署spug的服务器放在内网，做好网络访问权限，数据库不要开外网访问权限，其他安全建议参考：https://www.spug.dev/docs/practice/

**Comment by endachao** [comment]
谢谢，准备部署在内网，已向 spug 赞助咖啡一杯，希望项目越来越完善
