### ISSUE TITLE
Bug: 无效的格式

### ISSUE THREAD

**Issue by zgz** [openspug/spug#175]
![图片](https://user-images.githubusercontent.com/2143078/90997531-65262100-e5f4-11ea-84da-5ab27a307864.png)
![图片](https://user-images.githubusercontent.com/2143078/90997577-81c25900-e5f4-11ea-97f5-c8b6fc53a218.png)

Spug 版本:2.3.8

## 问题重现步骤

1.
2.

**Comment by vapao** [comment]
可以在开发者工具中看下接口返回的什么内容吗，截图发下。

**Comment by zgz** [comment]
![图片](https://user-images.githubusercontent.com/2143078/91117675-c5cf5f80-e6c1-11ea-8a5b-51362b4b61f7.png)


<html>
<head>
<script language="javascript">setTimeout("location.replace(location.href.split(\"#\")[0])",2000);</script>
<script type="text/javascript" src="http://1.1.1.3:89/cookie/flash.js"></script>
<script language="javascript">setURL("1.1.1.3");supFlash("18446744073450730088");</script>
</head>
<body>
<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" codebase="http://fpdownload.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=7,0,0,0" width="0" height="0" id="m" align="center"><param name="allowScriptAccess" value="always" />
<param name="movie" value="http://1.1.1.3:89/cookie/flashcookie.swf" />
<param name="quality" value="high" />
<param name="FlashVars" value="srv=1.1.1.3" />
<embed src="http://1.1.1.3:89/cookie/flashcookie.swf"FlashVars="srv=1.1.1.3" quality="high" width="0" height="0"  name="m" align="center" allowScriptAccess="always" type="application/x-shockwave-flash"pluginspage="http://www.macromedia.com/go/getflashplayer" />
</object>
</body

**Comment by zgz** [comment]
#<html>
#<head>
#<script language="javascript">setTimeout("location.replace(location.href.split(\"#\")[0])",2000);</script>
#<script type="text/javascript" src="http://1.1.1.3:89/cookie/flash.js"></script>
#<script language="javascript">setURL("1.1.1.3");supFlash("18446744073450730088");</script>
#</head>
#<body>
#<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" codebase="http://fpdownload.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=7,0,0,0" width="0" height="0" id="m" align="center"><param name="allowScriptAccess" value="always" />
#<param name="movie" value="http://1.1.1.3:89/cookie/flashcookie.swf" />
#<param name="quality" value="high" />
#<param name="FlashVars" value="srv=1.1.1.3" />
#<embed src="http://1.1.1.3:89/cookie/flashcookie.swf"FlashVars="srv=1.1.1.3" quality="high" width="0" height="0"  name="m" align="center" allowScriptAccess="always" type="application/x-shockwave-flash"pluginspage="http://www.macromedia.com/go/getflashplayer" />
#</object>
#</body

**Comment by vapao** [comment]
![image](https://user-images.githubusercontent.com/10863906/91243025-7e0d0e80-e77b-11ea-96b5-3a9c4800e55b.png)
点这个响应看下接口返回的内容

**Comment by zgz** [comment]
![图片](https://user-images.githubusercontent.com/2143078/91246113-a7309d80-e781-11ea-904a-b6f209bffba5.png)

**Comment by zgz** [comment]
![图片](https://user-images.githubusercontent.com/2143078/91246227-e19a3a80-e781-11ea-8d96-2867945b2a56.png)

**Comment by vapao** [comment]
这看起来并不是接口返的内容，不确定你那边的环境，建议你换个浏览器试试，比如 chrome

**Comment by zgz** [comment]
chome也一样
![图片](https://user-images.githubusercontent.com/2143078/91303687-f0f9a200-e7da-11ea-89ae-00cef39e1077.png)

**Comment by zgz** [comment]
![图片](https://user-images.githubusercontent.com/2143078/91303758-0cfd4380-e7db-11ea-9422-444ef25ece09.png)

**Comment by vapao** [comment]
![image](https://user-images.githubusercontent.com/10863906/91307131-21900a80-e7e0-11ea-88c5-13e26961878d.png)

使用 chrome 发个类似这样的截图看下

**Comment by zgz** [comment]
![图片](https://user-images.githubusercontent.com/2143078/91388269-8ba0c200-e869-11ea-8bd5-55b084c5c229.png)

**Comment by zgz** [comment]
![图片](https://user-images.githubusercontent.com/2143078/91388303-99eede00-e869-11ea-9bdb-0ff56739d47e.png)

**Comment by zgz** [comment]
第隔一段时间，报一下，http://192.168.24.14/api/notify/
![图片](https://user-images.githubusercontent.com/2143078/91388433-e0443d00-e869-11ea-86e9-19ab48e0c926.png)

**Comment by vapao** [comment]
你这个应该是网络被劫持了，可以使用https 试试。

**Comment by zgz** [comment]
应不存在吧，这个是我们自己的内部网络啊，没有对外开发啊

**Comment by zgz** [comment]
1.1.1.3是我们的上网行为服务器

**Comment by vapao** [comment]
这就是得你自己查下了

**Comment by vapao** [comment]
如需帮助请再次打开该问题
