### ISSUE TITLE
 如何关闭文件上下传，或者将他们做成权限？

### ISSUE THREAD

**Issue by zgz** [openspug/spug#176]
Spug 版本:

## 问题重现步骤

1.
2.

**Comment by vapao** [comment]
自定义发布的文件上传？

**Comment by zgz** [comment]
不是，是打开主机那里，一般生产环境，可以让他们去分析日志（比如开发人员），但是不能下载 上传任何东西
![图片](https://user-images.githubusercontent.com/2143078/91117578-886ad200-e6c1-11ea-8984-2b0e74a1a392.png)

**Comment by zyupo** [comment]
在系统管理 / 角色管理 / 主机权限， 控制好主机权限，给不同的用户分配不同的主机就可以解决了吧？

**Comment by zgz** [comment]
很多时候，系统出问题时，只想把机器分配给开发，去分析日志，但是就是不希望他们能下载一些敏感信息

**Comment by vapao** [comment]
将在 2.3.9 添加该功能权限，不过这并不能防止开发通过操作命令行查看敏感信息。

**Comment by zgz** [comment]
收到，多谢！
