### ISSUE TITLE
自定义发布，上传文件，结果报错exception: [Errno 2] No such file or directory，几k的小文件没问题，100M的文件就不行了？请问各位大佬如何优化？ 

### ISSUE THREAD

**Issue by YJiWei** [openspug/spug#177]
Spug 版本:

## 问题重现步骤

1.
2.

## 报错/问题截图

![image](https://user-images.githubusercontent.com/39039484/91025309-c5848500-e62b-11ea-8664-25d9c7c3a7e2.png)

**Comment by YJiWei** [comment]
大佬们，我分析了一下，感觉是因为文件没有接收完成，去发布的时候，所以找不到文件，是不是可以加个判断，如果文件没有接收完成，就不能点击发布操作呢？

**Comment by vapao** [comment]
嗯，2.3.9 会优化这个问题，本周内会发布。

**Comment by YJiWei** [comment]
谢谢大佬们的无私奉献，期待2.3.9

**Comment by YJiWei** [comment]
你好，请问怎样增加附件呢？

**Comment by vapao** [comment]
2.3.9 已发布，如有问题，请再次打开问题。
