### ISSUE TITLE
Bug: 创建新用户后，登录或者删除用户提示 “Exception: 'NoneType' object has no attribute 'strip'”

### ISSUE THREAD

**Issue by Greggwen** [openspug/spug#178]
Spug 版本:

操作系统Linux-4.18.0-193.14.2.el8_2.x86_64-x86_64-with-centos-8.2.2004-Core
Python版本3.6.8
Django版本2.2.13
Spug API版本v2.3.8
Spug Web版本v2.3.8

## 问题重现步骤

1.通过系统或者shell命令新增一个非管理员用户
2.登录或者系统操作删除时

## 报错/问题截图
![image](https://user-images.githubusercontent.com/2416646/91289851-75412a80-e7c5-11ea-828b-dae77886bd18.png)

## 期望的结果
创建用户后，可以正常登录，以及删除。

**Comment by vapao** [comment]
通过什么方式创建的用户，可以贴下你创建用户的命令。

**Comment by vapao** [comment]
如需帮助请再次打开该问题。

**Comment by Greggwen** [comment]
> 通过什么方式创建的用户，可以贴下你创建用户的命令。

创建命令：python manage.py user add -u admin -p 123 -n 张三丰

创建超级管理员后，在后台新增用户，也会报相关的错误。
