### ISSUE TITLE
Bug: 升级后发布时git取版本报错

### ISSUE THREAD

**Issue by kenvin-feng** [openspug/spug#179]
Spug 版本:

操作系统Linux-3.10.0-1062.el7.x86_64-x86_64-with-centos-7.7.1908-Core
--
Python版本3.6.8
Django版本2.2.13
Spug API版本v2.3.9
Spug Web版本v2.3.9

## 问题重现步骤

1.升级后发布时git取版本报错
2.

## 报错/问题截图
Exception: Cmd('git') failed due to: exit code(129) cmdline: git fetch -P -p -v origin stderr: 'error: unknown switch `P' usage: git fetch [<options>] [<repository> [<refspec>...]] or: git fetch [<options>] <group> or: git fetch --multiple [<options>] [(<repository> | <group>)...] or: git fetch --all [<options>] -v, --verbose be more verbose -q, --quiet be more quiet --all fetch from all remotes -a, --append append to .git/FETCH_HEAD instead of overwriting --upload-pack <path> path to upload pack on remote end -f, --force force overwrite of local branch -m, --multiple fetch from multiple remotes -t, --tags fetch all tags and associated objects -n do not fetch all tags (--no-tags) -p, --prune prune remote-tracking branches no longer on remote --recurse-submodules[=<on-demand>] control recursive fetching of submodules --dry-run dry run -k, --keep keep downloaded pack -u, --update-head-ok allow updating of HEAD ref --progress force progress reporting --depth <depth> deepen history of shallow clone --unshallow convert to a complete repository

**Comment by vapao** [comment]
如果非 docker 部署，请升级部署spug的服务器的git 版本至 `2.17.0+`，我们也更新下 relases 的注意事项，感谢反馈。

**Comment by kenvin-feng** [comment]
已解决，确实是git版本太低
