### ISSUE TITLE
# 新功能建议 # 发布申请页面将要发布的主机ip显示出来

### ISSUE THREAD

**Issue by wangbaocongnb** [openspug/spug#180]
各位openspug大佬，需求如下图:

![image](https://user-images.githubusercontent.com/66620199/91416845-8603a600-e882-11ea-9617-a3594f657e68.png)

**Comment by vapao** [comment]
这里显示的东西已经很多了，ip 可能也不止一个，这里不可能完整展示，另外应用 加 环境 应该能够说明问题了吧。

**Comment by wangbaocongnb** [comment]
ok
