### ISSUE TITLE
Bug: 自定义发布，上传文件的时候，超过30S就报错了。

### ISSUE THREAD

**Issue by YJiWei** [openspug/spug#185]
Spug 版本: 2.3.9

## 问题重现步骤

1.
2.

## 报错/问题截图

![image](https://user-images.githubusercontent.com/39039484/91696528-48648d00-eba2-11ea-9c8b-57c0d9d77b51.png)

**Comment by YJiWei** [comment]
建议大佬建一个微信或者QQ交流群吧，方便交流

**Comment by vapao** [comment]
感谢反馈，将在下个版本改进。 群在readme 文档下方有的

**Comment by vapao** [comment]
`v2.3.10` 已发布，参考 [https://spug.dev/docs/update-version/](https://spug.dev/docs/update-version/) 升级。
