### ISSUE TITLE
Bug: 阿里云SLB+spug部署登录过期

### ISSUE THREAD

**Issue by wodliwu** [openspug/spug#190]
Spug 版本:

## 问题重现步骤

1. 基于阿里云部署， SLB负载均衡转发到spug
2. 登录成功直接报登录过期退出

**Comment by vapao** [comment]
![image](https://user-images.githubusercontent.com/10863906/92233319-ac5cbd80-eee2-11ea-86e1-d565f6f350eb.png)

**Comment by vapao** [comment]
应该是触发了上述安全规则，默认使用 docker 部署的 `X-Real-IP` 是 `$remote_addr`，阿里云slb 可以转发过来的请求来自不同的ip，当ip发生变化时token 自动失效了。

**Comment by vapao** [comment]
可以尝试编辑容器内的 `/etc/nginx/nginx.conf` 的配置 `proxy_set_header X-Real-IP $remote_addr;` 变更为 `proxy_set_header X-Real-IP $http_X-Forwarded-For;` 试下。

**Comment by wodliwu** [comment]
可以解决
