### ISSUE TITLE
Bug: 对于已经在发布中的，点击查看，里面日志不会自动滚动，需要手动抓心

### ISSUE THREAD

**Issue by weinianta** [openspug/spug#193]
Spug 版本:

![image](https://user-images.githubusercontent.com/13379708/92359698-45c3e380-f11e-11ea-9709-7cd1a4e2f86d.png)

## 问题重现步骤

1.先提交一个发布申请，然后点击发布，让任务处于发布中
2.这时候返回出其他页面，或者其他人点击这个处于发布中的任务，然后再重新点击查看，里面的日志没有刷新滚动，需要手动点击刷新

## 报错/问题截图
![image](https://user-images.githubusercontent.com/13379708/92359640-2f1d8c80-f11e-11ea-99c7-9a735474c55b.png)

## 期望的结果

希望对于已经在发布中的任务，即使退出后，再重新点查看后，日志能自动刷新滚动

**Comment by vapao** [comment]
设想的查看功能更多的场景是发布后排错等原因查看的，一般这种场景都是已经发布完成后了。
我们在后续版本看是否可以优化这个问题。

**Comment by weinianta** [comment]
还是挺需要的，麻烦帮忙加上下。

我们分配了权限的，测试主管才允许了发布申请，其他测试组成员只有查看权限，又需要他们一直在点刷新看

如果能直接支持点击查看后，里面的内容像发布的时候那样实时显示会方便很多。谢谢了，辛苦各位

**Comment by vapao** [comment]
`v2.3.10` 将会提供该功能。

**Comment by weinianta** [comment]
非常感谢

**Comment by vapao** [comment]
`v2.3.10` 已经发布参考 [https://spug.dev/docs/update-version/](https://spug.dev/docs/update-version/) 升级。
