### ISSUE TITLE
建议增加端口类型、IP检测等

### ISSUE THREAD

**Issue by allblue** [openspug/spug#195]
1. 端口检测可以选择TCP或UDP，现在只能检测TCP
2. 增加IP检测，可以用icmp检测主机是否在线，可以简单监控下网络设备。如果能适配下cisco、华为设备更好
3. 在监控中心-任务设置中增加“立即执行”，可以在任务/新建修改后直接测试

**Comment by vapao** [comment]
很不错的建议，记录下来了，感谢你的建议。

**Comment by vapao** [comment]
udp 检测目前还没找到合适的方法，2和3 将再 v2.3.10 版本更新。

**Comment by vapao** [comment]
`v2.3.10` 已经发布参考 [https://spug.dev/docs/update-version/](https://spug.dev/docs/update-version/) 升级。

**Comment by allblue** [comment]
赞响应，已升级
