### ISSUE TITLE
监控中心-自定义脚本使用问题

### ISSUE THREAD

**Issue by wenchengxu** [openspug/spug#196]
您好，咨询一下 监控中心-自定义脚本的退出状态码    监控的方式是什么，是否允许一个脚本多个状态码输出判断？

**Comment by zhenxxin** [comment]
我个人的使用情况是，返回值为 0 被当做正常情况，否则为异常情况。并且脚本 `echo` 输出的信息系统都会转发出去，你说的这个场景，其实可以这样做：异常的情况下，输出不同的消息就好了嘛。供参考哈。

**Comment by vapao** [comment]
@zhenxxin  说的很正确，我们推荐的也是这样使用的。

**Comment by wenchengxu** [comment]
其实想问的是  脚本返回多个状态码，怎么被监控中心识别？
我的使用场景是：脚本监控12个网页链接的状态，会有12个状态码，正常情况下会有12个0返回，反之返回每个错误链接的状态码（可能会返回1-12个）。
对我的情况来说，系统是怎么识别并确认报警的呢

**Comment by vapao** [comment]
执行结束只有一个退出状态码，而且默认脚本中任意一个命令退出状态非0 都会中断脚本的继续执行，可以看下官网文档 [忽略执行中的报错](https://spug.dev/docs/practice/#%E5%BF%BD%E7%95%A5%E6%89%A7%E8%A1%8C%E4%B8%AD%E7%9A%84%E6%8A%A5%E9%94%99)

**Comment by wenchengxu** [comment]
理解了，超感谢回答!


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "openspug/spug"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月11日(星期五) 上午10:10
收件人:&nbsp;"openspug/spug"<spug@noreply.github.com&gt;;
抄送:&nbsp;"1486086502"<1486086502@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [openspug/spug] 监控中心-自定义脚本使用问题 (#196)





 
执行结束只有一个退出状态码，而且默认脚本中任意一个命令退出状态非0 都会中断脚本的继续执行，可以看下官网文档 忽略执行中的报错
