### ISSUE TITLE
配置中心考虑支持注释吗？

### ISSUE THREAD

**Issue by zhenxxin** [openspug/spug#197]
如题，请问配置中心会考虑支持注释吗？

实际使用过程中。类似于 dotenv 这种形式的配置必须要去掉注释才能正常工作，但实际上，如果配置信息有注释的话，会更加易于理解一点，不用每个配置项还要和原始开发去同步确认了。

**Comment by vapao** [comment]
配置是可以添加备注的，你说的注释指的生成的配置文件包含注释吗？
可以给几个例子说明下你想要的是什么样子的。

**Comment by zhenxxin** [comment]
@vapao 抱歉，上面描述的不太清楚。重新确认了一下，在视图为表格模式的时候，是支持注释（备注）的。

我提问的时候的场景是这样的：

1. 视图切换成文本；
2. 直接复制粘贴 `.env` 文件内容到文本编辑区域；
3. 保存后查看效果

此时可以看到以 `#` 打头注释内容，被当做了值的一部分。

这是文本视图下的样子：
![文本模式](https://user-images.githubusercontent.com/4496285/92843968-ec0e3280-f417-11ea-8b04-98ec48142efa.png)

这是表格视图下的样子：
![表格模式](https://user-images.githubusercontent.com/4496285/92844040-ff210280-f417-11ea-83f7-2ffd3079363f.png)


期望的样子，文本视图模式下，支持把文本内容中 `#` 开始的内容当做备注就可以了（但是想了下，注释标识符还可能以 `;` 或者其他的符号，需要适配的工作看来有点多了）。

![期望的样子](https://user-images.githubusercontent.com/4496285/92844561-938b6500-f418-11ea-9f95-c5a1ab4432fc.png)

另外，你提到的生成的文件也支持注释的话其实不是特别强的需求了，因为系统上支持了备注的话，生成的文件就可以没有这部分备注了。

**Comment by vapao** [comment]
嗯，`APP_DEBUG = True  # 是否开启调试` 这种肯定无法处理的，因为有可能值里边确实包含 # 号， 可以考虑增加对以 `#` 或 `;` 开头的行进行备注的解析，例如：
```shell
# 是否开启调试
APP_DEBUG = True
; 主机地址
HOST = 192.168.0.1
```

**Comment by vapao** [comment]
`v2.3.10` 已经发布参考 [https://spug.dev/docs/update-version/](https://spug.dev/docs/update-version/) 升级。
