### ISSUE TITLE
Bug: 首页图标UI显示异常

### ISSUE THREAD

**Issue by weinianta** [openspug/spug#198]
Spug 版本:

## 问题重现步骤

1. 首页图形展示 UI遮挡
2. 2K显示器

## 报错/问题截图

![image](https://user-images.githubusercontent.com/13379708/92869713-b1b38e00-f435-11ea-8578-46938269a1ff.png)

**Comment by vapao** [comment]
感谢反馈，将会在 v2.3.10 优化

**Comment by vapao** [comment]
`v2.3.10` 已经发布参考 [https://spug.dev/docs/update-version/](https://spug.dev/docs/update-version/) 升级。

**Comment by weinianta** [comment]
![image](https://user-images.githubusercontent.com/13379708/93157169-44a53e80-f73c-11ea-835d-c130de0e5531.png)

帮我看看升级报这个错 是为啥

**Comment by weinianta** [comment]
![image](https://user-images.githubusercontent.com/13379708/93158690-3dcbfb00-f73f-11ea-837f-65e9242da3a0.png)

已成功升级，非常感谢
