### ISSUE TITLE
功能建议：希望执行模版可以多选

### ISSUE THREAD

**Issue by weinianta** [openspug/spug#200]
Spug 版本:

## 问题重现步骤

1.目前批量执行任务里面，目标主机可以进行多选操作，这个非常好
2.希望执行模版也能进行多选，每选中一个，当前选中的命令就提前到输入框中，这样的话不同类型的组合命令就会方便很多

## 报错/问题截图
![image](https://user-images.githubusercontent.com/13379708/93062396-761ffa80-f6a7-11ea-8b2d-f805a69870c0.png)

## 期望的结果
感谢各位！！！

**Comment by weinianta** [comment]
祝愿Spug越来越好，来自于一个程序员的小小建议

**Comment by vapao** [comment]
即将发布的 `2.3.10` 版本会改进选择模版的行为，选择模版会在当前内容后追加而不是覆盖，这样应该就能满足你说的要求。 多选会存在 顺序的问题。

**Comment by weinianta** [comment]
这样也能满足需求，追加的时候转行追加。非常感谢

**Comment by vapao** [comment]
`v2.3.10` 已经发布参考 [https://spug.dev/docs/update-version/](https://spug.dev/docs/update-version/) 升级。
