### ISSUE TITLE
Bug: 执行非系统命令，command not found问题

### ISSUE THREAD

**Issue by Mosicol** [openspug/spug#201]
Spug 版本:v2.3.9

## 问题重现步骤

1.执行 java -version 报 command not found （在本机执行该命令没问题，已配置.bash_profile,/etc/profile）
2.如下图

## 报错/问题截图
![image](https://user-images.githubusercontent.com/35798934/93286673-49382880-f80a-11ea-87f8-e2a2947475fd.png)

**Comment by vapao** [comment]
![image](https://user-images.githubusercontent.com/10863906/93297360-b6a48300-f823-11ea-87b8-cfbcdf84bbe9.png)

**Comment by Mosicol** [comment]
![image](https://user-images.githubusercontent.com/35798934/93301056-7563a180-f82a-11ea-82f2-f528bbca7fa5.png)

**Comment by jjeejj** [comment]
> ![image](https://user-images.githubusercontent.com/10863906/93297360-b6a48300-f823-11ea-87b8-cfbcdf84bbe9.png)

可以直接加载 PATH 变量吗？
