### ISSUE TITLE
是否能增加监控数据收集，或者作为一个图表展示的地方？

### ISSUE THREAD

**Issue by Shadow-linux** [openspug/spug#202]

**Comment by vapao** [comment]
有计划会有实时的图表展示基础监控数据，但不会考虑存储收集的数据，做统计分析之类的功能。

**Comment by Shadow-linux** [comment]
感谢回复



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: vapao <notifications@github.com&gt;
发送时间: 2020年9月27日 14:52
收件人: openspug/spug <spug@noreply.github.com&gt;
抄送: Shadow-L <972367265@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[openspug/spug] 是否能增加监控数据收集，或者作为一个图表展示的地方？ (#202)
