### ISSUE TITLE
建议：发布申请查看能改为webSocket或者异步js实现吗

### ISSUE THREAD

**Issue by weinianta** [openspug/spug#203]
Spug 版本: 2.3.10

## 问题重现步骤

1.测试人员点击发布之后，开发人员想看下发布进度
2.或者去检查为什么异常很慢的时候，方便排查任务进度卡在哪一步了

## 报错/问题截图
从这里点击进去的
![image](https://user-images.githubusercontent.com/13379708/94362465-0e799e80-00ee-11eb-9270-a1018840f90d.png)

然后进入后，页面会间隔3秒左右进行页面刷新
![image](https://user-images.githubusercontent.com/13379708/94362479-251ff580-00ee-11eb-84a6-90d9f1467689.png)
体验不是很友好

## 期望的结果
期望使用webSocket更新页面内容信息，就像点发布的时候展示的那样，很好很赞

或者如果webSocket不方便实现的话，能不能使用js异布加载刷新，目前是整个页面刷新，体验不友好

**Comment by weinianta** [comment]
非常感谢，目前spug平台在我们公司的推广程度已经越来越深了，非常好用。

**Comment by weinianta** [comment]
如果可以的话，把那个没有按钮权限的从目前灰色不可点击 变为 不显示比较好。

**Comment by vapao** [comment]
2.x 转入维护阶段，这里改websocket变动会比较多暂时不打算改变刷新方式。 自你那感觉体验不好主要是那个loading 动画的原因吧， 这个如果去掉loading 动画是不是应该就可以了？

**Comment by vapao** [comment]
> 如果可以的话，把那个没有按钮权限的从目前灰色不可点击 变为 不显示比较好。

这个下个版本会优化，感谢建议。

**Comment by weinianta** [comment]
好的，非常感谢。

loading动画取消了，页面刷新频率加快点，或者加个类似于这样的按钮

**Comment by vapao** [comment]
v2.3.11 已发布。

**Comment by weinianta** [comment]
我刚更新完了，发现部分问题。得麻烦你们再辛苦下，重新发包了。

> 发现问题的菜单【点击变为白屏】

1. 主机管理
2. 模版管理
3. 应用管理

等好多都是点击后变为白屏



辛苦帮忙看看

**Comment by weinianta** [comment]
浏览器缓存我清理过了

F12中看到有发起请求，接口也正常响应了，页面没有渲染内容

![image](https://user-images.githubusercontent.com/13379708/94503853-02025c80-023a-11eb-911c-9a5222e37c73.png)

**Comment by weinianta** [comment]
![image](https://user-images.githubusercontent.com/13379708/94504515-87d2d780-023b-11eb-8f18-20911797d824.png)


辛苦

**Comment by zyupo** [comment]
今天发布的版本有个小问题，目前已经修复。
现在重新更新一下最新版本。更新过程中遇到问题可以加群里面沟通解决。
