### ISSUE TITLE
[建议]：刚刚看完了一遍系统的相关功能，感觉有点脱离企业的实际做法

### ISSUE THREAD

**Issue by autohawkeye** [openspug/spug#204]
各位开发：
      首先，非常感谢大家辛苦的开发出一个运维平台，让大家多一个选择，但做为一个企业的工作多年，且多个公司的实际经验来讲，不得不提出一些不同的意见，系统整体看来此系统过于简单，想法也太简单，并不能通过此系统提高工作效率，相反会降低效率。脱离了企业的真实使用场景。

     举例：
     1. 目前云市场火爆，且很多企业都已经在使用云服务，系统未考虑到这一点，云主机的相关同步，维护等，太偏传统了。
     2. 即使是面对自建机房的企业，单个的添加主机也是非常低效率的方式，很多都需要批量添加，如果让大家整理好表格再导入就有点低效了，可以通过IP 段来批量添加相关的主机等信息
     3. 发布过程，企业实际操作中会集成申请，审批流程，操作上线，回滚等场景，且一次上线中会涉及到多个应用，且是自动串行发布或者并行发布，且有相关的通知消息发送给相关的人，知晓上线的进度和状态。另外上线过程中可能会涉及到相关的配置变更等与之相关的操作。
    4. 其它的我就不一一列举了。

    优点：
    1. 远程的网页版的客户端做得不错，不过为了安全，建议客户端连接的URL 进行一定的安全设计，要加密如https://demo.spug.dev/ssh/1 如里面的ID 1 就得加密，不能让别人能够写2，同一个URL ，复制到其它的浏览器上面，换一个人是否能够登入，同一个换一个ID 是否能够登入，此处我没有仔细的测试，建议考虑这些吧。

**Comment by autohawkeye** [comment]
个人说得有点多，如果有什么不对的地方，还请多多包涵

**Comment by vapao** [comment]
感谢你中肯的意见，spug 的定位并不是做一个大而全的运维平台，更多的注重简单、灵活、易用。

**Comment by vapao** [comment]
如有需要请再次打开该问题。
