### ISSUE TITLE
无法登陆，一直提示：会话过期，请重新登陆。

### ISSUE THREAD

**Issue by ycathi** [openspug/spug#206]
![01](https://user-images.githubusercontent.com/38828027/94866216-7a069780-0471-11eb-9437-a031d8b973b3.png)

![02](https://user-images.githubusercontent.com/38828027/94866225-7d9a1e80-0471-11eb-9af7-ffe47f6ac6d9.png)

![03](https://user-images.githubusercontent.com/38828027/94866231-7ffc7880-0471-11eb-8ebc-c692ff1155f5.png)

![04](https://user-images.githubusercontent.com/38828027/94866237-812da580-0471-11eb-9026-259999d0beb6.png)

{"data": "", "error": "验证失败，请重新登录"}

是不是哪里的权限没有开？

**Comment by ycathi** [comment]
![05](https://user-images.githubusercontent.com/38828027/94866348-bf2ac980-0471-11eb-860f-a3b826436ab5.png)

**Comment by vapao** [comment]
看下这个 #190

**Comment by ycathi** [comment]
有用，已解决。
