### ISSUE TITLE
站点检测异常

### ISSUE THREAD

**Issue by linsu2223** [openspug/spug#207]
感觉站点检测不是很稳定。在项目实际的站点是正常的情况下，频繁发生类似HTTPConnectionPool(host='x', port=x): Max retries exceeded with url: xxx (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f63e87e70f0>, 'Connection to xxxx timed out. (connect timeout=10)'))或HTTPSConnectionPool(host='x', port=x): Read timed out. (read timeout=10) 警报。

**Comment by vapao** [comment]
没有相关环境我们这无法复现这个问题，如果spug 是在容器里部署的，那么检测是在容器内进行的，确保容器与要检测的站点之间的网络稳定。

**Comment by vapao** [comment]
也可以尝试比如写脚本的形式来辅助排查网络问题。

**Comment by vapao** [comment]
很久没收到回复，如需帮助请再次打开

**Comment by botsphp** [comment]
能否指定默认超时的时间，默认的10s 有些短。
