### ISSUE TITLE
建议：列表分页展示，希望能显示总条数

### ISSUE THREAD

**Issue by weinianta** [openspug/spug#208]
Spug 版本: 2.3.11

## 问题重现步骤

1.发布申请
2.报警历史

等需要列表展示的页面

## 报错/问题截图
![image](https://user-images.githubusercontent.com/13379708/95933816-074ad400-0e02-11eb-85a1-4c35ed6b2f38.png)

## 期望的结果

![image](https://user-images.githubusercontent.com/13379708/95933839-103ba580-0e02-11eb-8094-90b86db63519.png)

**Comment by vapao** [comment]
感谢建议，下个版本应该会增加。

**Comment by vapao** [comment]
v2.3.13 已更新。
