### ISSUE TITLE
Bug: 上传大文件报错

### ISSUE THREAD

**Issue by zgz** [openspug/spug#209]
Spug 版本:v2.3.11

## 问题重现步骤

1.文件上传超过1G会网络错误
2.小文件上传正常

## 报错/问题截图

![图片](https://user-images.githubusercontent.com/2143078/95956421-d766f500-0e30-11eb-86cc-a9427ef64199.png)

**Comment by vapao** [comment]
看下浏览器开发者工具的console是否有报错信息

**Comment by vapao** [comment]
很久没收到回复，如需帮助请再次打开。

**Comment by zgz** [comment]
关闭，这个与nginx的配置有关
