### ISSUE TITLE
开发大大，有木有windows版的安装教程啊，急需。

### ISSUE THREAD

**Issue by erikgqp8645** [openspug/spug#21]
开发大大，有木有windows版的安装教程啊，急需。

**Comment by vapao** [comment]
可以参考 [标准安装文档](https://spug.dev/docs/install/) ,  差别不大.

**Comment by 2637309949** [comment]
@vapao 可以提供一个docker版本不

**Comment by erikgqp8645** [comment]
> 可以参考 [标准安装文档](https://spug.dev/docs/install/) , 差别不大.

多谢老大，我试试哈。

**Comment by vapao** [comment]
@2637309949 目前还没有docker版本,  后期会提供, 如果你可以帮忙提供下那就太好了 😄

**Comment by vapao** [comment]
Docker 安装文档已更新，请参考 [Docker安装](https://www.spug.dev/docs/install-docker/)
