### ISSUE TITLE
批量执行不执行命令 

### ISSUE THREAD

**Issue by ilovebamboo** [openspug/spug#211]
![image](https://user-images.githubusercontent.com/6214084/96562716-a7699700-12f3-11eb-8ecd-956ba60d184e.png)

**Comment by ilovebamboo** [comment]
![image](https://user-images.githubusercontent.com/6214084/96562835-ce27cd80-12f3-11eb-82d6-0a46d8b2e9f1.png)

**Comment by ilovebamboo** [comment]
有人遇到过吗？今天重新安装docker 还是一样。

**Comment by vapao** [comment]
cd 命令本身就什么也不输出，截图显示的已经执行完毕了。 可以执行其他命令测试下比如 ls /tmp
