### ISSUE TITLE
Bug: 应用发布，git报错

### ISSUE THREAD

**Issue by lugoing** [openspug/spug#212]
操作系统Linux-3.10.0-693.el7.x86_64-x86_64-with-centos-7.4.1708-Core
--
Python版本3.6.8
Django版本2.2.13
Spug API版本v2.3.13
Spug Web版本v2.3.13

## 问题重现步骤

1.应用发布，随便选个git地址都会报错如下图
2.我看了下好像是git不支持 -P参数
3.我是手动内网部署，在云主机上用docker启的就没有问题，出错的内网centos7.4  ，云主机是7.8， 其他py版本等等都一直

## 报错/问题截图
![微信图片_20201029145502](https://user-images.githubusercontent.com/41786602/97535862-429af480-19f7-11eb-8355-d843e9ba1005.png)
![微信图片_20201029145524](https://user-images.githubusercontent.com/41786602/97535868-475fa880-19f7-11eb-9533-833656f93a45.png)
![微信图片_20201029145530](https://user-images.githubusercontent.com/41786602/97535879-4a5a9900-19f7-11eb-932c-f089a37028bc.png)

**Comment by vapao** [comment]
Git 版本需要 2.17.0+

**Comment by lugoing** [comment]
> Git 版本需要 2.17.0+

的确，去编了一个新版的git就可以了。。。
从来没想过竟然被git拖了后腿
