### ISSUE TITLE
发布问题

### ISSUE THREAD

**Issue by lovese** [openspug/spug#217]
发布提示拉取代码失败，私有gitlab仓库地址是要账号密码的或者SSH密钥，请问这个怎么配置？

**Comment by vapao** [comment]
git clone 可以使用系统设置密钥设置里密钥对进行ssh认证，具体设置ssh密钥认证的方法可以在网上搜下每种类型的git仓库操作方法可能不太一样， 可以参考下 https://spug.dev/docs/install-error/#%E6%96%B0%E5%BB%BA%E5%B8%B8%E8%A7%84%E5%8F%91%E5%B8%83%E7%94%B3%E8%AF%B7-git-clone-%E9%94%99%E8%AF%AF
