### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by linyaohong** [openspug/spug#218]
Spug 版本: 
Spug API版本v2.3.13
Spug Web版本v2.3.13

## 问题重现步骤

1. 当新建用户和角色后带着token 没有权限的接口也可以访问

## 报错/问题截图

/api/config/environment/
{"data": [{"id": 1, "name": "123", "key": "123123", "desc": null, "created_at": "2020-11-05 00:11:02", "created_by_id": 1}], "error": ""}

## 我的权限
{"data": [{"id": 2, "username": "test00000", "nickname": "test100000", "type": "default", "is_supper": false, "is_active": true, "token_expired": 0, "last_login": "2020-11-04 23:59:36", "last_ip": "112.251.178.91", "role_id": 1, "created_at": "2020-11-04 23:33:49", "created_by_id": 1, "deleted_at": null, "deleted_by_id": null, "role_name": "abcd"}], "error": ""}

**Comment by vapao** [comment]
目前的大部分权限是通过前端实现的，后续版本会进行改进。
