### ISSUE TITLE
Bug: initdb 出错 app表不存在

### ISSUE THREAD

**Issue by berlinsaint** [openspug/spug#222]
spug/spug_api/apps/app/views.py    临时初始化这个 apps表还没建呢， 怎么first?
Spug 版本:
master
## 问题重现步骤

1. initdb 出错 app表不存在
2.

## 报错/问题截图

![image](https://user-images.githubusercontent.com/10629930/98627139-71e22780-234e-11eb-8498-fdd37b42558d.png)

**Comment by vapao** [comment]
是的，这个问题正在修复，正式部署或升级不要使用 Pre-Release 版本，这些版本我们会先进行测试，没问题后转为正式版本。
