### ISSUE TITLE
需求：工作台近30天登陆需要权限划分

### ISSUE THREAD

**Issue by weinianta** [openspug/spug#229]
Spug 版本: 2.3.14

## 问题重现步骤

1.登陆到主页后，在工作台右下角有相关显示
2.目前是所有用户登陆，都能看到其他用户的登陆信息

## 报错/问题截图

![image](https://user-images.githubusercontent.com/13379708/99923719-f92d9300-2d71-11eb-9d69-38f84bebcbba.png)

## 期望的结果

需要根据权限进行精细划分，默认都只能查看自己的登陆信息

**Comment by vapao** [comment]
下个版本会优化，感谢建议。

**Comment by vapao** [comment]
v3 版本已发布，这部分内容放在了专门的 dashboard页面，有单独的权限控制
