### ISSUE TITLE
建议：spug对于svn的支持有限，希望能够正式支持

### ISSUE THREAD

**Issue by onaug6th** [openspug/spug#231]
svn没有git常规发布这么便利，而且也没有常规发布的一些信息。例如项目版本信息，版本号等内容。希望后续常规发布也能支持svn

**Comment by mailbyms** [comment]
svn 是远古时代的产物了，你说的 git 都能支持，而且 git 和 CI 集成更好。
没必要使用 svn 了

**Comment by onaug6th** [comment]
> svn 是远古时代的产物了，你说的 git 都能支持，而且 git 和 CI 集成更好。
> 没必要使用 svn 了

公司集团大部分都是用的svn方案，本来想推广使用。可惜不支持
