### ISSUE TITLE
Bug: 登录频繁出现，会话过期，请重新登录

### ISSUE THREAD

**Issue by Wp516781950** [openspug/spug#232]
Spug 版本:

## 问题重现步骤

1.k8s，StatefulSet部署
2.部署后首次登录正常，但主机管理等其他功能点击后会闪退。
3.闪退后再次登录会频繁出现，会话过期，请重新登录。
4.无法登录的情况。

## 报错/问题截图
![image](https://user-images.githubusercontent.com/65537358/100061948-cb2b7a00-2e69-11eb-9d70-2853edb829a9.png)

## 期望的结果
提供下k8s的部署方式。目前虽然架设在K8S中，但感觉问题比较多。

**Comment by vapao** [comment]
请查看官网 [安全性说明文档](https://spug.dev/docs/practice/#%E5%AE%89%E5%85%A8%E6%80%A7%E5%AE%9E%E8%B7%B5%E6%8C%87%E5%8D%97)

**Comment by Wp516781950** [comment]
![Uploading image.png…]()
我已经关闭了这个特性了

**Comment by vapao** [comment]
与是否关闭这个特性没关系，那个只是关闭无法验证时的警告提示。
你的问题是spug 前是否加的有负载均衡之类的，造成spug 获取到ip来回变动， 可以看下 #190

**Comment by Wp516781950** [comment]
好的，感谢已解决。
