### ISSUE TITLE
建议: 前端逻辑太重了，权限和菜单是不是可以考虑通过后端API获取 

### ISSUE THREAD

**Issue by ntuwang** [openspug/spug#234]
Spug 版本:

## 问题和 期望

目前菜单和权限list都是直接卸载前端的，不利于维护，是否考虑把他们挪到后端，通过API获取，权限可以单独维护一张表做关联

**Comment by vapao** [comment]
欢迎提交 pr， 直接发些简单的伪代码可以，欢迎一起来完善。
