### ISSUE TITLE
Bug: GIT拉取代码后，怎么确定当前分支是release

### ISSUE THREAD

**Issue by 359587** [openspug/spug#238]
Spug 版本:

## 问题重现步骤

1.我在【代码检出后执行】的命令框获取当前分支，我想判断当前分支是否是release，但是我无论用什么方法，看到的都是master分支，无论我再应用发布中选择的是什么分支，所以我想知道，我在创建一个发布申请后，选择分支界面选的分支，是在哪个环节帮我切换的？

**Comment by 359587** [comment]
> [](url)

**Comment by luckyjade** [comment]
是个bug，选择branch无效，每次都是master
