### ISSUE TITLE
Bug: 点击登录后系统崩溃

### ISSUE THREAD

**Issue by s045pd** [openspug/spug#239]
操作系统 macOS-10.16-x86_64-i386-64bit
Python版本 3.9.0
Django版本 2.2.13
Spug API版本 v2.3.5
Spug Web版本 v2.3.5

## 问题重现步骤

1. 打开站点，输入账户及密码
2. 点击登录

![image](https://user-images.githubusercontent.com/22721729/100561412-d2340b80-32f3-11eb-9462-287f939d4a3b.png)

## 报错/问题截图
黑屏并风扇狂转一下后系统崩溃重启

![image](https://user-images.githubusercontent.com/22721729/100561441-e546db80-32f3-11eb-8a37-263df3aba5ed.png)

## 期望的结果

正常进入,也不至于直接系统崩溃吧。。。

**Comment by vapao** [comment]
😓  每次都这样嘛？ 可以测试下演示环境 https://demo.spug.dev
