### ISSUE TITLE
Exception: Authentication failed

### ISSUE THREAD

**Issue by liyuliang** [openspug/spug#24]
账号密码 ip 地址都对, 首次验证也通过
但是console 里面提示验证失败

```
Connecting ...
Exception: Authentication failed.

Connection is closed.
```

**Comment by vapao** [comment]
可参考 [这个文档](https://spug.dev/docs/install-error/#%E6%B7%BB%E5%8A%A0%E4%B8%BB%E6%9C%BA%E6%8A%A5%E9%94%99-exception-not-a-vaild-rsa-private-key-file)  尝试是否能解决问题。

**Comment by haiya512** [comment]
遇到了同样的问题，我之前添加了主机，现在又用另外一个用户的身份修改了，于是报错了，登陆不了
