### ISSUE TITLE
bug:目标主机部署路径不存在的时候自动发布会到最后会报错

### ISSUE THREAD

**Issue by nsnake** [openspug/spug#240]
使用的docer镜像，版本如下
Django版本2.2.13
Spug API版本v2.3.14
Spug Web版本v2.3.14

设置目标主机部署路径为/opt/a/b/c
如果只有目录/opt/a，系统不会自动创建b目录而造成发布最后创建软链接的时候失败。
建议发布之前直接创建完成的目录，而后软链接直接挂载在目录上即可解决路径不存在的问题，且解决了项目访问时可能的目录不存的问题

**Comment by vapao** [comment]
感谢建议，大部分情况下上级目录会存在的，没有自动帮创建目录，我们考虑是怕用户输入的可能是个错误的路径，我们自动创建后反而不好排查问题。 这个情况我们也会综合考虑是否在后续版本添加。
