### ISSUE TITLE
bug:部署失败之后不会回退

### ISSUE THREAD

**Issue by nsnake** [openspug/spug#241]
发布项目如果指定了多台机器。在发布过程中如果其中一台机器失败。则其它成功机器的数据已经变了，但失败机器的没有变化。
应该是失败的话则都回退回之前的状态。
由于我是新项目发布。之前没有发布的状态，不清楚是否因此造成的无法回退

**Comment by vapao** [comment]
可以看下官网文档的 [回滚机制说明](https://spug.dev/docs/deploy-rollback/)
