### ISSUE TITLE
Bug: 部署到远程机过程中，数据准备报错

### ISSUE THREAD

**Issue by kiros666** [openspug/spug#245]
Spug 版本: v2.3.14

## 问题重现步骤

1. 新建应用
2. 执行第一次发布，可以成功
3. 再次提交发布并执行发布，报错

## 报错/问题截图
第一次建立应用时执行发布部署成功：
![image](https://user-images.githubusercontent.com/38120428/101436440-1c973700-3949-11eb-8d0b-10c1513d849b.png)

第二次执行发布部署报错：
![image](https://user-images.githubusercontent.com/38120428/101436299-df32a980-3948-11eb-80ca-8a6f983adbbc.png)

## 期望的结果
每次出现这个问题，我都需要删除并重新建立应用才能部署成功，第二次就不行了，这样子很烦，期待作者大大的回复

**Comment by vapao** [comment]
远程主机默认的 zsh 吗？ 可以更改为  bash 试下

**Comment by kiros666** [comment]
> 远程主机默认的zsh吗？可以更改为bash试下

改成默认为bash就可以了，感谢作者。因为zsh比较广泛使用，希望作者大大可以在readme中补充下这一点

**Comment by kiros666** [comment]
> 远程主机默认的zsh吗？可以更改为bash试下

改成默认为bash就可以了，感谢作者。因为zsh比较广泛使用，希望作者大大可以在readme中补充下这一点
