### ISSUE TITLE
Bug: 登陆页面没有做登陆态验证（已登陆用户，直接访问此页面需要重新填写密码）

### ISSUE THREAD

**Issue by wg2019** [openspug/spug#247]
Spug 版本:最新版本

## 问题重现步骤

1.登陆页面，填写账号密码登陆
2.直接访问登陆页面，会要求填写信息
3.比较严重的问题，这个时候密码如果故意填错多次，会导致账号被锁，已登陆的用户也无法使用

## 报错/问题截图
![image](https://user-images.githubusercontent.com/41517731/101736704-cbc93f00-3afe-11eb-98f7-9aaa9f92c503.png)

## 期望的结果

1.已登陆的账号，访问登陆页面自动跳转
2.密码输入多次后锁定（当前页面），希望不要将已经登陆的账号退出

**Comment by zyupo** [comment]
1、已经登录的账号，同一个浏览器访问页面不需要登录。
2、第一个问题不存在，所以第二个问题也不存在了。具体可以验证一下demo环境。

**Comment by wg2019** [comment]
可能是我说的不清楚，我的意思是直接访问登陆链接，demo也是存在这个问题的
访问https://demo.spug.dev/页面登陆后
开启新标签（关掉原页面吴映香），访问https://demo.spug.dev/，就还是需要登录的
这是第一个问题
