### ISSUE TITLE
Bug: 无法拉取远程代码

### ISSUE THREAD

**Issue by zsboss** [openspug/spug#251]
Spug 版本:

## 问题重现步骤

1. 应用发布
![image](https://user-images.githubusercontent.com/19493235/102293996-35c06900-3f83-11eb-813a-067e6e611eab.png)

## 报错/问题截图
![image](https://user-images.githubusercontent.com/19493235/102293954-19bcc780-3f83-11eb-8287-bbbdab0bee05.png)

## 期望的结果
在容器里面并没有找到clone的代码

**Comment by vapao** [comment]
可以执行 ls 和 pwd 确认当前所在目录和文件
