### ISSUE TITLE
手动安装问题

### ISSUE THREAD

**Issue by Myshiner** [openspug/spug#252]
Spug 版本:v2.3.14
我看手动部署那里有两部，1是clone项目代码，2是下载 已编译打包后的前端项目即web_v2.3.14.tar.gz，请问这两部只需要下载web_v2.3.14.tar.gz就可以了吗，因为我拉git代码的时候，其实里面已经有spug_web了，但是第二步的tar包也是解压到spug_web，啥意思？

**Comment by zhaoxuan** [comment]
spug_web 里面是源码，你需要自己编译。如果不想编译前端的代码，可以直接下载放进去。
