### ISSUE TITLE
Bug: $SPUG_REPOS_DIR/$SPUG_DEPLOY_ID获取的目录和实际同步到服务器的目录不是同一个

### ISSUE THREAD

**Issue by nsnake** [openspug/spug#253]
官方文档中说明$SPUG_REPOS_DIR/$SPUG_DEPLOY_ID 即为本次发布应用的源码目录。
比如你的项目id为8，则会有/data/spug/spug_api/repos/8和/data/spug/spug_api/repos/8_68_20201218153215这样的2个目录
其中$SPUG_REPOS_DIR/$SPUG_DEPLOY_ID 对应的/data/spug/spug_api/repos/8，但实际发布的时候使用的是data/spug/spug_api/repos/8_68_20201218153215里的代码。这样就造成了如果你需要对发布的代码做些修改并且是使用$SPUG_REPOS_DIR/$SPUG_DEPLOY_ID来获取的绝对路径，则最终发布的结果是有问题的。

**Comment by vapao** [comment]
如果要修改在 “代码检出后” 这个钩子里执行就行了，在这个钩子里当前目录就是 例如上边你说的 `/data/spug/spug_api/repos/8_68_20201218153215`

**Comment by nsnake** [comment]
> 如果要修改在 “代码检出后” 这个钩子里执行就行了，在这个钩子里当前目录就是 例如上边你说的 `/data/spug/spug_api/repos/8_68_20201218153215`

最好能在加一个获取当前应用发布的源码目录的变量。 这个变量比$SPUG_DEPLOY_ID使用频率其实更高，否则用户就只能从bash里面获取目录地址了

**Comment by vapao** [comment]
v3 版本已默认为源码目录
