### ISSUE TITLE
Bug: 发布后执行ifconfig提示无此命令

### ISSUE THREAD

**Issue by irisrain** [openspug/spug#255]
Spug 版本:v2.3.14

## 问题重现步骤

1.在应用发布后执行: 这里输ifconfig获取IP的时候提示ifconfig: command not found

## 报错/问题截图

![image](https://user-images.githubusercontent.com/14995750/102913444-b4ecfa00-44b9-11eb-8f79-11a5b205f340.png)

**Comment by irisrain** [comment]
需要写全路径/usr/sbin/ifconfig解决。不知道算不算bug

**Comment by mailbyms** [comment]
这个系统应该是运行在 sh，不是 bash
环境变量加载不全
也不支持 shell 切换，例如运行 bash ，就挂死了

**Comment by mailbyms** [comment]
在 ifconfig 前多加一行 source /etc/profile 就可以了，这样：

source /etc/profile
ifconfig
