### ISSUE TITLE
Bug: 执行sudo su - 失败

### ISSUE THREAD

**Issue by mailbyms** [openspug/spug#259]
Spug 版本:  2.3.14 

## 问题重现步骤

1. 执行任务 -> “选择执行主机"
2. “执行命令” 框里输入 sudo su -
3. 点击 ”开始执行“

## 报错/问题截图
弹出的控制台，一直转圈

## 期望的结果
能切换到 root 用户，或明确提示不支持该命令

**Comment by zyupo** [comment]
暂时不支持sudo 后续会考虑优化。
