### ISSUE TITLE
建议：在监控中心添加监控任务时，能够选择多个主机

### ISSUE THREAD

**Issue by sheisdancing** [openspug/spug#267]
现在一个监控任务只能监控一台主机，大部分情况下需要对很多台主机进行监控，每次都创建一样的任务。
比如创建磁盘剩余空间监控，100台主机就需要创建100个任务，很不方便。

**Comment by zyupo** [comment]
感谢建议，这个问题已经在优化中了。

**Comment by vapao** [comment]
v3.0.1 beta版已发布
