### ISSUE TITLE
自定义发布一些问题

### ISSUE THREAD

**Issue by hryGithub** [openspug/spug#27]
不是基于git的应用发布，不适用于常规发布，使用自定义发布，自定义的环境环境变量，每一步不能通用，spug的全局变量没有当前发布机器的ip地址

**Comment by vapao** [comment]
自定义发布可以使用发布申请创建时的 SPUG_RELEASE 变量。
全局变量没有当前发布机器的ip地址的问题，后续综合评估后如有需要会添加该变量。

**Comment by hryGithub** [comment]
有时候需要多个自定义的环境变量，spug_release这一个不够呀

**Comment by vapao** [comment]
可以基于这个变通下，比如如果需要多个自定义的值 可以设置 spug_release 为空格隔开的多个值，在脚本内再分割即可取到对应的多个值

**Comment by hryGithub** [comment]
这是一个办法，不过还是建议有自定义环境变量的地方，就像常规发布的自定义变量

**Comment by vapao** [comment]
嗯，可以考虑。感谢提议

**Comment by vapao** [comment]
v2.2.3 新增了 `SPUG_HOST_ID` 和 `SPUG_HOST_NAME` 全局变量。

**Comment by hryGithub** [comment]
spug的全局变量在自定义发布过程中，本地动作阶段是拿不到这些环境变量的值吗，

**Comment by vapao** [comment]
可以的， 但新增的 `SPUG_HOST_ID` 和 `SPUG_HOST_NAME` 是在主机执行阶段才可以使用
