### ISSUE TITLE
需求：应用环境需要自定义排序

### ISSUE THREAD

**Issue by weinianta** [openspug/spug#270]
Spug 版本: v2.3.14

## 问题重现步骤

1. 新建发布申请，选择应用的时候
2.我的第一个会优先出来生产环境的，每次都要去选择下面的，有点怕误操作

## 报错/问题截图

![image](https://user-images.githubusercontent.com/13379708/105468057-7a04fe80-5cd1-11eb-9ad3-74473ffe9367.png)

## 期望的结果

每次进来，都默认的生产环境。以免误操作希望能自定义排序，让我把测试环境等之类的往前排

**Comment by vapao** [comment]
收到建议，下个版本会考虑优化。

**Comment by weinianta** [comment]
谢谢
