### ISSUE TITLE
建议：编译机器和部署分开

### ISSUE THREAD

**Issue by AlbertNie** [openspug/spug#273]
目前使用平台时候，在镜像中安装了 mvn , nodejs等等，用来从 git  拉取项目后进行编译和发布，但是这样的操作，在后续升级3.0版本就很麻烦了，而且平台在大规模使用的时候，机器编译很占性能
因此，建议将编译 和 部署分开，编译可以让我们自己安装在另一台机器或者一个集群上，发布平台就不依赖机器环境，可以编译任意项目。也可以平滑升级到新版本的 SPUG

**Comment by zyupo** [comment]
很不错的建议。我们会考虑这个问题。

**Comment by farzer** [comment]
期待

**Comment by wingahi** [comment]
编译和部署分开，而且部署可以自由选择环境。可参考以前的 女娲

**Comment by vapao** [comment]
v3 版本已发布，支持构建和部署的分离
