### ISSUE TITLE
Bug: 添加主机出现异常

### ISSUE THREAD

**Issue by dmskys** [openspug/spug#277]
添加主机，填入用户名 服务id后添加弹出异常
Exception: ('Invalid private key', [_OpenSSLErrorWithText(code=67764350, lib=4, func=160, reason=126, reason_text=b'error:040A007E:rsa routines:RSA_check_key_ex:iqmp not inverse of q')])

**Comment by zyupo** [comment]
你目标主机什么操作系统？

**Comment by dmskys** [comment]
使用的是docker 重新安装后可以正常使用了

**Comment by dmskys** [comment]
目标主机是centos

**Comment by mrmsl** [comment]
我也有同样的问题，windows系统通过docker安装，不知道怎么解决。
