### ISSUE TITLE
请问可否支持svn代码仓库？

### ISSUE THREAD

**Issue by wingahi** [openspug/spug#279]
目前公司短期内没有考虑使用git，所以希望能找到一个支持svn的devops，且还会继续迭代的开源项目

**Comment by zyupo** [comment]
Spug项目会持续维护。
可以用spug的自定义发布功能，自定义发布可以支持任意命令。

**Comment by RainNameless** [comment]
> 目前公司短期内没有考虑使用 git，所以希望能够找到一个支持 svn 的开发操作，并且继续继续的开源项目

老哥你有解决方案了吗？ 同遇到这个问题
