### ISSUE TITLE
主机管理需要增加共钥登陆

### ISSUE THREAD

**Issue by neosun100** [openspug/spug#28]
服务器的主机一般还要添加密钥登陆，否则极不安全，目前的版本只能账号密码登陆，考虑增加下密钥登陆，谢谢

**Comment by neosun100** [comment]
特别是阿里云的机器，都是要密钥登陆的，这个问题希望能尽快解决，可以参考项目：https://github.com/huashengdun/webssh

**Comment by vapao** [comment]
目前已经是密钥登录，添加主机时输入的密码仅用于添加密钥登录功能，并不会存储密码， 也不会通过密码连接。
