### ISSUE TITLE
测试任务执行功能，无论什么命令都一直转圈

### ISSUE THREAD

**Issue by dwx542914** [openspug/spug#285]
按要求部署完成，在主机管理中添加自己的虚拟机，添加完成后，能通过console控制台进行连接，但是在使用任务执行功能时，发现无论什么命令，都会一直转圈，如下图
![image](https://user-images.githubusercontent.com/55649693/110750734-e20da500-827d-11eb-94da-42e2044e0569.png)
我当前的环境是python 3.7，所有module都是和requirement文件中的一致，还望解答

**Comment by vapao** [comment]
通过什么方式部署的？ 如果自己启动的服务看下 [官网文档](https://spug.dev/docs/install-error/#%E6%A0%87%E5%87%86%E5%AE%89%E8%A3%85%E6%89%B9%E9%87%8F%E6%89%A7%E8%A1%8C%E7%9A%84%E4%BB%BB%E5%8A%A1%E5%8D%A1%E4%BD%8F%E6%97%A0%E6%B3%95%E7%9C%8B%E5%88%B0%E6%89%A7%E8%A1%8C%E8%BE%93%E5%87%BA)

**Comment by dwx542914** [comment]
> 通过什么方式部署的？ 如果自己启动的服务看下 [官网文档](https://spug.dev/docs/install-error/#%E6%A0%87%E5%87%86%E5%AE%89%E8%A3%85%E6%89%B9%E9%87%8F%E6%89%A7%E8%A1%8C%E7%9A%84%E4%BB%BB%E5%8A%A1%E5%8D%A1%E4%BD%8F%E6%97%A0%E6%B3%95%E7%9C%8B%E5%88%B0%E6%89%A7%E8%A1%8C%E8%BE%93%E5%87%BA)

的确是没有启动消费服务，thanks
