### ISSUE TITLE
Bug: 权限有bug

### ISSUE THREAD

**Issue by Gooooodman** [openspug/spug#287]
Spug 版本: 最新

## 问题重现步骤
获取人员信息如下：

{
    "data": {
        "access_token": "553707231b524397acd4591192d1b402",
        "nickname": "大牛",
        "is_supper": false,
        "has_real_ip": false,
        "host_perms": [],
        "permissions": [
            "host.host.view",
            "host.host.del"
        ]
    },
    "error": ""
}

## 报错/问题截图

能访问 /account/role/ 接口。

![image](https://user-images.githubusercontent.com/13062160/111016830-f9b66c00-83ea-11eb-8839-7495b2db1f6a.png)

**Comment by vapao** [comment]
嗯，目前后端仅有一些关键接口的权限校验，页面功能的权限是前端实现的。 后续我们会完善权限
