### ISSUE TITLE
主机管理登陆mac以及windows都会有问题

### ISSUE THREAD

**Issue by neosun100** [openspug/spug#29]
windows登陆如下

**Comment by neosun100** [comment]
![image](https://user-images.githubusercontent.com/13846998/76638841-175ab680-6588-11ea-8c9a-12647ead7bed.png)

**Comment by neosun100** [comment]
Exception: add public key error: b'\xbb\xb7\xbe\xb3\xb1\xe4\xc1\xbf -e \xc3\xbb\xd3\xd0\xb6\xa8\xd2\xe5\r\n'

**Comment by neosun100** [comment]
mac可以登陆成功，但是无法进入shell管理

**Comment by neosun100** [comment]
报错如下：
Connecting ...
Exception: Authentication failed.

Connection is closed.

**Comment by vapao** [comment]
使用场景主要用于linux系统的运维管理，mac 和 windows 使用场景少，还未进行全面测试。
感谢反馈，后期可能会进行测试。

**Comment by xiantuteng** [comment]
> ![image](https://user-images.githubusercontent.com/13846998/76638841-175ab680-6588-11ea-8c9a-12647ead7bed.png)

报“Exception: add public key error：命令语法不正确”错误的原因是Spug通过账号和密码登录主机后，会尝试通过密码连接目标主机并执行以下命令设置密钥认证 https://spug.cc/docs/host-manage/：
``` bash
mkdir -p -m 700 ~/.ssh
echo 'public key content ....' >> ~/.ssh/authorized_keys
chmod 600 ~/.ssh/authorized_keys
```
默认情况下Windows服务器环境下没有Bash命令环境 ，因此解决方案是在Windows服务器里Git，这样就有了Git Bash环境，即可登录成功。
如果希望在Spug连接Windows服务器后执行Bash脚本，则需要将Git Bash作为Windows的默认Shell，在PowerShell执行以下命令：
``` powershell 
New-ItemProperty -Path "HKLM:\SOFTWARE\OpenSSH" -Name DefaultShell -Value "C:\Program Files\Git\bin\bash.exe" -PropertyType String -Force

```

**Comment by wwwangzh** [comment]
> > ![image](https://user-images.githubusercontent.com/13846998/76638841-175ab680-6588-11ea-8c9a-12647ead7bed.png)
> 
> 报“Exception: add public key error：命令语法不正确”错误的原因是Spug通过账号和密码登录主机后，会尝试通过密码连接目标主机并执行以下命令设置密钥认证 [https://spug.cc/docs/host-manage/：](https://spug.cc/docs/host-manage/%EF%BC%9A)
> 
> ```shell
> mkdir -p -m 700 ~/.ssh
> echo 'public key content ....' >> ~/.ssh/authorized_keys
> chmod 600 ~/.ssh/authorized_keys
> ```
> 
> 默认情况下Windows服务器环境下没有Bash命令环境 ，因此解决方案是在Windows服务器里Git，这样就有了Git Bash环境，即可登录成功。 如果希望在Spug连接Windows服务器后执行Bash脚本，则需要将Git Bash作为Windows的默认Shell，在PowerShell执行以下命令：
> 
> ```powershell
> New-ItemProperty -Path "HKLM:\SOFTWARE\OpenSSH" -Name DefaultShell -Value "C:\Program Files\Git\bin\bash.exe" -PropertyType String -Force
> ```

安装了git环境 但是还是提示错误
![image](https://github.com/openspug/spug/assets/8326760/eaac4129-8f25-40f3-995d-cb9f23ea1a1d)
请问有啥方案吗
