### ISSUE TITLE
如何根据发布的不同主机执行不同的命令？

### ISSUE THREAD

**Issue by dmskys** [openspug/spug#290]
我现在有2台主机，但是用的是同一个程序，在两台主机发布应用后，我想根据不同的主机判断，执行不同命令，或者说只有在某一台主机才执行命令

**Comment by vapao** [comment]
参考 [官方文档](https://spug.dev/docs/practice/#%E5%8F%91%E5%B8%83%E8%BF%87%E7%A8%8B%E4%B8%AD%E4%B8%8D%E5%90%8C%E4%B8%BB%E6%9C%BA%E6%89%A7%E8%A1%8C%E4%B8%8D%E5%90%8C%E6%93%8D%E4%BD%9C)
