### ISSUE TITLE
Bug: git仓库中的submodule不能获取

### ISSUE THREAD

**Issue by haohedev** [openspug/spug#291]
v2.3.9 Docker版本
Spug 版本:

## 问题重现步骤

1. Git仓库中如果包含子模块，在代码检出后执行`git submodule update --init --recursive --remote`没有办法更新子模块

## 报错/问题截图
查看代码， 是通过`git archive`获取目标仓库的文件， 导致没有办法更新子模块。

## 期望的结果
可以在检出后执行`git submodule update --init --recursive --remote`

**Comment by vapao** [comment]
可以考虑在 检出前 执行这个操作，使用 `$SPUG_REPOS_DIR/$SPUG_DEPLOY_ID` 可以切换到仓库路径。

**Comment by haohedev** [comment]
> 可以考虑在 检出前 执行这个操作，使用 `$SPUG_REPOS_DIR/$SPUG_DEPLOY_ID` 可以切换到仓库路径。

👍，多谢

**Comment by HuangLuGuang** [comment]
V3.05 版本，`git submodule update --init --recursive --remote`检出前执行这个命令没什么反应，也没有任何报错
