### ISSUE TITLE
应用发布申请时 ，提示 could find username for http....................... （gitlab服务器地址）

### ISSUE THREAD

**Issue by hj00494yong** [openspug/spug#293]
拉取gitlab项目不需要输入用户名密码吗， spug在哪边设置 ；

我看官网有个提示 ：  Git仓库地址 该应用的 Git 仓库地址（请确保部署运维平台的服务器有权限通过给定的地址克隆仓库）。
这个应该是spug服务器没有权限克隆gitlab仓库项目，这个如何处理

**Comment by hj00494yong** [comment]
项目是http协议拉取

**Comment by vapao** [comment]
请 [参考官方文档](https://spug.dev/docs/install-error/#%E6%96%B0%E5%BB%BA%E5%B8%B8%E8%A7%84%E5%8F%91%E5%B8%83%E7%94%B3%E8%AF%B7-git-clone-%E9%94%99%E8%AF%AF)
