### ISSUE TITLE
Bug: 多人同时更改项目配置，后提交的由于缓存会覆盖前面提交的内容

### ISSUE THREAD

**Issue by AlbertNie** [openspug/spug#297]
Spug 版本: all version

## 问题重现步骤
例如项目配置为 ： abcd-a
1. 多人同时修改项目配置
2. 第一人先提交 abcd-ab
3. 第二人由于缓存，页面上看到的还是 abcd-a，此时第二人往后再加内容，则覆盖了第一人提交的内容

## 期望的结果
建议给项目配置加上版本hash, 提交内容时，检查hash值是否相同，如果不相同，则提示用户当前配置已被另一人更新，请刷新页面后再做修改提交

**Comment by vapao** [comment]
可以通过权限控制尽量避免多人同时操作，出现的概率一般不大，这个涉及的接口很多工作量略大，目前主要在开发3.0的内容，这个需要延后处理。
