### ISSUE TITLE
【报警中心-报警历史】需要增加删除功能，时间堆积，几千条下来，有点尴尬

### ISSUE THREAD

**Issue by neosun100** [openspug/spug#30]

**Comment by vapao** [comment]
会保留最近30天的记录，超过的会自动删除。

**Comment by neosun100** [comment]
好的，可以考虑增加用户主动删除操作哦

**Comment by neosun100** [comment]
另外是否考虑增加私钥密钥登陆服务器的方式

**Comment by vapao** [comment]
嗯，可以考虑主动删除功能。 
登录服务器的问题，目前就是密钥登录的，添加主机时输入的密码仅做首次添加密钥登录验证使用，并不会存储密码，后期也不会使用密码登录服务器。
