### ISSUE TITLE
bug: 常规发布的一个问题 

### ISSUE THREAD

**Issue by myysophia** [openspug/spug#301]
Spug 版本:

## 问题重现步骤

1.使用了一段时间spug的感受: spug 常规发布时，  对于从git上clone的同一tag代码没有共享，每次都重新打包。   

## 期望的结果
同一仓库的同一tag的多次发布 是否可以共享之前的repo

**Comment by vapao** [comment]
你期望的是同一个应用的不同环境发布时，只打包一次？ 比如测试环境打包，可以在生产环境发布时候直接用？

**Comment by myysophia** [comment]
vapao 你好，不是生产的发布用测试的发布， 有个场景，例如  有的项目需要用同样的tag同样的发布(测试或者生产)，发布多次，是否可以复用同一tag的repo, 类似于一个basic repo.  有点像docker的 基础镜像.

**Comment by vapao** [comment]
没太明白你描述的问题，可否说下按你的理解目前spug是怎样的，你期望是怎样的。
