### ISSUE TITLE
改进建议: 新建发布申请加载速度慢

### ISSUE THREAD

**Issue by aq0706** [openspug/spug#302]
Spug 版本: v2.3.14

## 问题重现步骤

 1. 控制台 应用发布/发布申请/新建发布申请 加载[选择分支/标签/版本]非常慢

## 报错/问题截图
 
![image](https://user-images.githubusercontent.com/12995007/116168733-b2cfcc00-a735-11eb-9d59-38420ef8e36e.png)

## 期望的结果
加载速度能快点，我看代码是去拉取分支和commit，可以优化成先拉取分支，然后再根据用户选择的分支，拉取commit。

**Comment by vapao** [comment]
首次会进行完整的clone比较慢，剩余的都是增量和本地操作，理论上都会比较快。

**Comment by aq0706** [comment]
我个人操作是一次性选好分支和commitId，不会频繁切换分支。
