### ISSUE TITLE
手动安装二次开发环境时遇到的问题

### ISSUE THREAD

**Issue by Runbacktoo** [openspug/spug#303]
参考说明文档：https://www.spug.dev/docs/install/
部署前端时出现报错，由于初次接触node，不知从何排查，请赐教。
npm start后报错如下：
src/components/ACEditor.js
  Line 13:1:  Unexpected default export of anonymous function  import/no-anonymous-default-export

src/components/SearchForm.js
  Line 12:1:  Unexpected default export of anonymous class  import/no-anonymous-default-export

src/layout/Footer.js
  Line 11:1:  Unexpected default export of anonymous class  import/no-anonymous-default-export

src/layout/Header.js
  Line 15:1:  Unexpected default export of anonymous class  import/no-anonymous-default-export

src/layout/index.js
  Line 16:1:  Unexpected default export of anonymous class  import/no-anonymous-default-export

src/menus.js
  Line 6:1:  Assign array to a variable before exporting as module default  import/no-anonymous-default-export

src/pages/alarm/routes.js
  Line 12:1:  Assign array to a variable before exporting as module default  import/no-anonymous-default-export

src/pages/config/routes.js
  Line 13:1:  Assign array to a variable before exporting as module default  import/no-anonymous-default-export

src/pages/deploy/routes.js
  Line 13:1:  Assign array to a variable before exporting as module default  import/no-anonymous-default-export

src/pages/exec/routes.js
  Line 11:1:  Assign array to a variable before exporting as module default  import/no-anonymous-default-export

src/pages/home/AlarmTrend.js
  Line 11:1:  Unexpected default export of anonymous function  import/no-anonymous-default-export

src/pages/home/LoginActive.js
  Line 11:1:  Unexpected default export of anonymous function  import/no-anonymous-default-export

src/pages/home/RequestTop.js
  Line 14:1:  Unexpected default export of anonymous function  import/no-anonymous-default-export

src/pages/home/routes.js
  Line 9:1:  Assign array to a variable before exporting as module default  import/no-anonymous-default-export

src/pages/host/routes.js
  Line 10:1:  Assign array to a variable before exporting as module default  import/no-anonymous-default-export

src/pages/monitor/routes.js
  Line 10:1:  Assign array to a variable before exporting as module default  import/no-anonymous-default-export

src/pages/schedule/routes.js
  Line 10:1:  Assign array to a variable before exporting as module default  import/no-anonymous-default-export

src/pages/system/role/codes.js
  Line 6:1:  Assign array to a variable before exporting as module default  import/no-anonymous-default-export

src/pages/system/routes.js
  Line 11:1:  Assign array to a variable before exporting as module default  import/no-anonymous-default-export

src/pages/welcome/index/index.js
  Line 9:1:  Unexpected default export of anonymous function  import/no-anonymous-default-export

src/pages/welcome/routes.js
  Line 10:1:  Assign array to a variable before exporting as module default  import/no-anonymous-default-export

src/routes.js
  Line 20:1:  Assign array to a variable before exporting as module default  import/no-anonymous-default-export

Search for the keywords to learn more about each warning.
To ignore, add // eslint-disable-next-line to the line before.

**Comment by zyupo** [comment]
1、确认一下Nodejs 版本是否满足最低要求（Nodejs 12.14）
2、确认一下node 包是否安装完整

**Comment by Runbacktoo** [comment]
我使用npm ls 查看发现一些警告，我安装提示把缺少的依赖安装后再次执行就没有了，可是npm start依然 出现很多warning。
我在本地的浏览器能够正常打开网页，但是尝试远程打开时页面出现以下报错：
TypeError: _libs_http__WEBPACK_IMPORTED_MODULE_17__.default.get(...).then(...).finally is not a function
push../src/layout/Header.js.__webpack_exports__.default.fetch
src/layout/Header.js:38
  35 | fetch = () => {
  36 |   this.setState({loading: true});
  37 |   http.get('/api/notify/')
> 38 |     .then(res => this.setState({notifies: res, read: []}))
| ^  39 |     .finally(() => this.setState({loading: false}))
  40 | };
  41 | 
请问这个能确定是哪个npm包问题吗？

**Comment by Runbacktoo** [comment]
我重新下载了spug_web目录，然后安装npm包，现在npm start没有任何问题，只是远程打开登录后就会出现报错如下：
TypeError: _libs_http__WEBPACK_IMPORTED_MODULE_17__.default.get(...).then(...).finally is not a function
push../src/layout/Header.js.__webpack_exports__.default.fetch
src/layout/Header.js:38
  35 | fetch = () => {
  36 |   this.setState({loading: true});
  37 |   http.get('/api/notify/')
> 38 |     .then(res => this.setState({notifies: res, read: []}))
     | ^  39 |     .finally(() => this.setState({loading: false}))
  40 | };
  41 | 
View compiled
push../src/layout/Header.js.__webpack_exports__.default.componentDidMount
src/layout/Header.js:27
  24 | }
  25 | 
  26 | componentDidMount() {
> 27 |   this.fetch();
     | ^  28 |   this.interval = setInterval(this.fetch, 60000)
  29 | }
  30 | 
View compiled
▶ 27 stack frames were collapsed.
LoginIndex.doLogin.data [as doLogin]
src/pages/login/index.js:73
  70 |   if (history.location.state && history.location.state['from']) {
  71 |     history.push(history.location.state['from'])
  72 |   } else {
> 73 |     history.push('/welcome/index')
     | ^  74 |   }
  75 | };
  76 | 
View compiled
libs__WEBPACK_IMPORTED_MODULE_15__.http.post.then.data
src/pages/login/index.js:56
  53 |           onOk: () => this.doLogin(data)
  54 |         })
  55 |       } else {
> 56 |         this.doLogin(data)
     | ^  57 |       }
  58 |     }, () => this.setState({loading: false}))
  59 | }
View compiled

**Comment by zyupo** [comment]
使用Nodejs 12.14 以上的版本，删除node_models 后，重新安装node 依靠包再试试看。
