### ISSUE TITLE
容器里使用外面docker命令

### ISSUE THREAD

**Issue by makeaini** [openspug/spug#310]
启动命令是：
docker run -d --restart=always --name=spug --privileged -p 8005:80 -v /data/spug/:/data -v /var/run/docker.sock:/var/run/docker.sock -v /usr/bin/docker:/usr/bin/docker  registry.aliyuncs.com/openspug/spug
报错：docker: error while loading shared libraries: libltdl.so.7: cannot open shared object file: No such file or directory
加上 
-v /usr/lib64/libltdl.so.7:/usr/lib/x86_64-linux-gnu/libltdl.so.7 
也是一样的

**Comment by zyupo** [comment]
Centos7_x64 操作系统启动没有报错。
确认一下你本地docker环境是否有问题。
