### ISSUE TITLE
Bug: 最新版本用域名访问spug  出现格式无效的错误提示。

### ISSUE THREAD

**Issue by xiaozhitaba** [openspug/spug#311]
Spug 版本:

## 问题重现步骤

1.用域名访问spug
2.

**Comment by xiaozhitaba** [comment]
关闭nginx的gzip功能就正常了。

因为请求的回复有text/html  这个压缩的格式。解析不正常、


添加这个text/html  text/plain text/css text/javascript application/javascript application/json。nginx会报错重复。所以直接关闭gzip

**Comment by vapao** [comment]
可能存在网络劫持问题，可以换个网络访问 或 使用 https。
