### ISSUE TITLE
Bug: 无法显示主机组

### ISSUE THREAD

**Issue by GoDan0** [openspug/spug#317]
Spug 版本:  分支3.0

## 问题重现步骤

1. 直接部署因为数据库（host表）没有主机，所有导致无法显示主机组

## 报错/问题截图

![image](https://user-images.githubusercontent.com/31703007/119343421-00a20a80-bcc9-11eb-8438-5460c770ab86.png)
![image](https://user-images.githubusercontent.com/31703007/119343448-0dbef980-bcc9-11eb-9b5a-633223896a42.png)

## 期望的结果
![image](https://user-images.githubusercontent.com/31703007/119343479-16173480-bcc9-11eb-8631-4f65986ae460.png)

**Comment by vapao** [comment]
收到，感谢反馈。

**Comment by vapao** [comment]
v3.0.1-beta.1 已修复
