### ISSUE TITLE
Bug: 通过密码验证主机时第二次才能获取密码

### ISSUE THREAD

**Issue by GoDan0** [openspug/spug#318]
Spug 版本:  3.0

## 问题重现步骤

1.   第一次输入密码后点击提交按钮获取password为空。第二次能正确获取
2.

## 报错/问题截图
![image](https://user-images.githubusercontent.com/31703007/119344242-02b89900-bcca-11eb-92f4-c6ef9926df0a.png)

## 期望的结果

应该是第一次输入密码时组件没重新渲染

**Comment by vapao** [comment]
v3.0.1-beta.2 已修复，感谢反馈。
