### ISSUE TITLE
Bug: 任务计划记录超过文档说明的50条不会自动删除

### ISSUE THREAD

**Issue by f071** [openspug/spug#319]
Spug 版本:
操作系统Linux-3.10.0-1160.11.1.el7.x86_64-x86_64-with-centos-7.8.2003-Core
Python版本3.6.8
Django版本2.2.22
Spug API版本v2.3.16
Spug Web版本v2.3.16

## 问题重现步骤

1. 通过docker安装（仅修改了管理员登录信息）
2. 添加1条间隔为1秒（执行对象：本机）的任务计划

任务内容：
curl -sS --connect-timeout 10 -m 60 'https://www.baidu.com'
endDate=`date +"%Y-%m-%d %H:%M:%S"`
echo "★[$endDate] Successful"

## 报错/问题截图
https://ftp.bmp.ovh/imgs/2021/05/2eba9155e19106e6.png

## 期望的结果
修复

**Comment by vapao** [comment]
每天凌晨会自动执行清理操作，并不是实时。
