### ISSUE TITLE
版本回滚以后，回滚的按钮不是灰色

### ISSUE THREAD

**Issue by hryGithub** [openspug/spug#32]
![image](https://user-images.githubusercontent.com/32188410/76742595-481b3580-67ac-11ea-9c36-d434e2d7f1df.png)

**Comment by vapao** [comment]
你的意思是按你发的截图第二行标题为`测试9` 的 回滚按钮也应该变成灰色的？ 可以解释下为什么想这样做呢

**Comment by hryGithub** [comment]
测试9已经回滚到测试8的版本，我再从测试9回滚，应该也是回滚到上一个版本，好像没什么意义

**Comment by vapao** [comment]
嗯，也是回滚到上一个版本，这个是已经比较明确的操作，我们感觉并不需要通过禁用回滚按钮来告诉用户这个版本已经回滚过了，也没必要限制一个版本只能回滚一次。

**Comment by hryGithub** [comment]
这应该是业务上的分歧，影响不大
