### ISSUE TITLE
Bug: 2.3.9 版本升级到最新版本（2.3.16）失败

### ISSUE THREAD

**Issue by reednow** [openspug/spug#320]
Spug 版本:
2.3.9

## 问题重现步骤

1.  python3 /data/spug/spug_api/manage.py update

## 报错/问题截图
v2.3.16 更新日志：
**3.0 Coming soon**

- 🐞 修复某些情况下Console卡顿的问题
发现新版本 v2.3.16 是否更新[y|n]？y
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   153  100   153    0     0    392      0 --:--:-- --:--:-- --:--:--   391
tar: This does not look like a tar archive

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
获取更新失败，排除网络问题后请附带输出内容至官方论坛反馈。

**Comment by vapao** [comment]
看起来像是网络问题，造成更新包下载失败了，可以稍后再尝试看看。
