### ISSUE TITLE
请问有计划支持各类主机商的api自动开通主机吗？

### ISSUE THREAD

**Issue by mushokumunou** [openspug/spug#322]
很感谢作者能开源spug，这给批量运维的人带来了福音。

现在很多大型主机商都会提供api来快速开通主机，诸如 scaleway，vultr之类，他们的api很完善。也被各大主机管理平台所集成，比如whmcs。
spug是否也能集成他们，这样可以直接可以利用spug的批量工具进行快速部署，极大方便及缩短了开通到交付的时间，提高了应用效率。

希望作者能考虑一下，当然二次开发也是可行的，但还是希望能原生支持，这是一个比较进阶需求的功能，我觉得原生维护将得到更大的发展舞台。

**Comment by vapao** [comment]
scaleway，vultr  并不太了解，这个功能目前评估下来并不是大众需求，可以考虑基于spug 进行二次开发。
