### ISSUE TITLE
使用一键部署的方式安装完成后，一直提示会话过期，请重新登录

### ISSUE THREAD

**Issue by xsh126410** [openspug/spug#324]
**Spug 版本:2.3.16**
![image](https://user-images.githubusercontent.com/48798341/120921011-3943da00-c6f4-11eb-9ed1-3e11a98bd501.png)
已按照[#190](https://github.com/openspug/spug/issues/190)方式修改nginx配置，加上proxy_set_header X-Real-IP $http_X-Forwarded-For;还是无效
![image](https://user-images.githubusercontent.com/48798341/120921119-ba02d600-c6f4-11eb-9a66-163b4a52057c.png)

**Comment by zyupo** [comment]
1、确认一下后端服务是否正常启动。
2、确认一下后端接口日志是否有报错信息，后端接口日志路径：/data/spug/spug_api/logs/api.log
3、以上如果无法解决，可以加群沟通。
