### ISSUE TITLE
Bug: Exception: 'utf-8' codec can't decode byte 0xdd in position 0: invalid continuation byte

### ISSUE THREAD

**Issue by xiaozhitaba** [openspug/spug#325]
Spug 版本:

操作系统Linux-3.10.0-1062.9.1.el7.x86_64-x86_64-with-centos-7.8.2003-Core
--
Python版本3.6.8
Django版本2.2.22
Spug API版本v2.3.16
Spug Web版本v2.3.16

## 问题重现步骤

1.为什么文件管理器  点击进入一个目录会报错
2.访问可读写的文件夹报错

## 报错/问题截图

![image](https://user-images.githubusercontent.com/10022712/121115111-4fae7a80-c847-11eb-825c-a44b3d13fadf.png)

**Comment by vapao** [comment]
文件可能是特殊编码，我们这暂时没法复现问题
