### ISSUE TITLE
Bug: 为什么 新建发布申请的时候，不是往我指定的地方clone

### ISSUE THREAD

**Issue by cs-sea** [openspug/spug#334]
Spug 版本: 2.3.9

## 问题重现步骤

1. 新建发布申请
2.

## 报错/问题截图
![image](https://user-images.githubusercontent.com/28532478/122221515-ea602680-cee3-11eb-9ba5-8a928bb6fc72.png)

## 期望的结果
clone 的位置 是我在 应用配置的路径
![image](https://user-images.githubusercontent.com/28532478/122221637-0b287c00-cee4-11eb-8731-fc1783b534d6.png)

**Comment by cs-sea** [comment]
还是说，git clone 到本地的路径必须是/data/spug/spug_api/....

**Comment by vapao** [comment]
这个目前是必须的，git clone 也不是在目标主机执行的。可以看下官网 使用手册里应用发布相关的文档。
