### ISSUE TITLE
Bug:  3.0.1-beta.2 钉钉 通知不生效

### ISSUE THREAD

**Issue by cs-sea** [openspug/spug#336]
Spug 版本: 3.0.1-beta.2

## 问题重现步骤

1. 新建项目，配置钉钉通知，失败发布后 没有通知
2. 

## 报错/问题截图
昨天试了下，2.3.9 版本还是可行的
![image](https://user-images.githubusercontent.com/28532478/122496143-da4c6200-d01d-11eb-8d65-3753e5309bb2.png)

## 期望的结果
发布失败 钉钉通知

**Comment by vapao** [comment]
v3.0.1-beta.3 已修复，感谢反馈。
