### ISSUE TITLE
Bug: 3.0版本发布，企业微信机器人不能收到通知

### ISSUE THREAD

**Issue by Leaonly** [openspug/spug#338]
Spug 版本:

操作系统Linux-3.10.0-693.el7.x86_64-x86_64-with-centos-7.8.2003-Core
--
Python版本3.6.8
Django版本2.2.22
Spug API版本v3.0.1
Spug Web版本v3.0.1-beta.3

## 问题重现步骤

1. 发布完，企业微信机器人不能收到通知

## 报错/问题截图
![image](https://user-images.githubusercontent.com/41314059/122736386-8d34ee00-d2b2-11eb-9840-8fa2c0a440d8.png)
![image](https://user-images.githubusercontent.com/41314059/122736432-9c1ba080-d2b2-11eb-9843-c3bb364fe3cc.png)

**Comment by vapao** [comment]
spug api 版本应该与 web 版本一致， 可以手动执行下：
```shell
cd /data/spug
git checkout 3.0
git pull
```
最后再重启下服务，确保 系统设置 / 关于 里的spug api 版本也是 v3.0.1-beta.3
