### ISSUE TITLE
按照生成环境部署后，当使用创建的管理用户登录，报400，无错误日志

### ISSUE THREAD

**Issue by tom2ling** [openspug/spug#34]
如标题，
![image](https://user-images.githubusercontent.com/20769441/76840271-e6bd9a00-6871-11ea-91d7-2325fb7a36bf.png)
并且 日志中无错误

**Comment by zyupo** [comment]
修改setting.py里面：
`ALLOWED_HOSTS = ['127.0.0.1'] `

将这里改成你内网地址，这里是后端服务为了安全，默认不允许除了127.0.0.1之外的ip调用接口。
