### ISSUE TITLE
Bug: 版本仓库是否能优化一下

### ISSUE THREAD

**Issue by TuChenH** [openspug/spug#340]
Spug 版本:
3.0.1-beta.3
## 问题重现步骤
构建版本仓库的时候，选择了某个分支进行构建。后续如果该分支有了新的更改，想要重新构建的时候，发现还是构建的老的代码。
如果想要发布最新的代码，必须在重新建一个仓库才能发布最新代码。
## 期望的结果
是否能支持对于一个分支的每次构建都是获取最新的代码进行打包。一个场景就是，测试分支会频繁变动，一天可能需要发布很多次，如果每次都需要新建仓库的话，就会有很多一模一样的仓库，很不方便。

**Comment by vapao** [comment]
确保你的spug_web 版本与 spug_api版本一致，每次构建的时候是会自动获取最新的代码的，没有复现你说的问题。

**Comment by TuChenH** [comment]
我是docker安装的.目前还是有这个问题. 而且发布的时候,选择构建版本的时间显示是之前构建的时候, 不是实时的.

**Comment by TuChenH** [comment]
我是docker安装的.目前还是有这个问题. 而且发布的时候,选择构建版本的时间显示是之前构建的时候, 不是实时的.
