### ISSUE TITLE
Bug: 最新版spug,二次开发依赖python-ldap3.2.0

### ISSUE THREAD

**Issue by LeeZBug** [openspug/spug#344]
Spug 版本:
 最新版 v3.0.1-beta.4

##背景
二次开发,源码的requirements.txt 文件中要求依赖python-ldap3.2.0

## 问题重现步骤
1.windos 64位平台,python3.6.5
2.已安装c++14require,pip install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple/安装依赖时仍报错 miscrosoft build c++ 14require 
3.尝试使用whl文件安装,在https://www.lfd.uci.edu/~gohlke/pythonlibs/中也没有找到cp36平台的python-ldap3.2.0whl安装包

**Comment by LeeZBug** [comment]
依赖能否可以用其他版本的python-ldap进行替换?

**Comment by LeeZBug** [comment]
尝试使用3.3.1,在python manage.py updatedb未有报错

**Comment by maguangqi** [comment]
我是直接注释了,不要ldap了

**Comment by vapao** [comment]
可以使用更新的版本，一般主版本一致就可以了。

**Comment by heyd7fc** [comment]
离线安装
https://www.lfd.uci.edu/~gohlke/pythonlibs/#python-ldap
