### ISSUE TITLE
需求:  提供自动部署的接口不

### ISSUE THREAD

**Issue by imnotprogrammer** [openspug/spug#347]
Spug 版本:

## 需求背景

  目前大多数场景下，开发和测试的更新比较频繁，如果要发布，每次都要单独添加发布申请，非常麻烦

## 期望
  希望能够提供一个单独的接口，每次利用git 钩子监听推送事件，然后通过钩子直接调用spug提供的接口完成自动部署，希望阁下能够考虑这个需求，祝你生活愉快

**Comment by AugustAohui** [comment]
好像你说的功能，在3.0.1-beta.1版本后已经集成了gitee/gitlab的webhook触发自动发布功能。[https://www.spug.dev/docs/change-log/#301-beta1](url)

**Comment by imnotprogrammer** [comment]
额，好的。目前我的版本不是3.0.1， 我升级到该版本，只需要在后台配置就行了吗？另外，对于你的解惑回复，在下深表感谢，再次祝你生活愉快！

**Comment by zyupo** [comment]
spug 3.0 版本已经集成了gitee/gitlab的webhook触发自动发布功能
