### ISSUE TITLE
Bug: 应用管理-》新建应用 主机数量显示

### ISSUE THREAD

**Issue by banditsmile** [openspug/spug#349]
Spug 版本:

操作系统Linux-5.10.25-linuxkit-x86_64-with-centos-7.8.2003-Core
--
Python版本3.6.8
Django版本2.2.22
Spug API版本v3.0.1-beta.6
Spug Web版本v3.0.1-beta.6
## 问题重现步骤

1.应用管理
2.新建应用

## 报错/问题截图
![微信截图_20210722205305](https://user-images.githubusercontent.com/2239356/126642373-2390b371-2d8f-47ae-9e1b-a6f6753d8eea.png)

我总共才3台主机，结果新建应用里面居然显示选择了4台主机

## 期望的结果

显示3台主机

**Comment by banditsmile** [comment]
偶然出现的问题，今天再去看就没有了

**Comment by vapao** [comment]
下次复现的话，@我下，感谢反馈

**Comment by banditsmile** [comment]
> 下次复现的话，@我下，感谢反馈

好的
