### ISSUE TITLE
Bug: 3.0最新代码服务和应用配置导入环境变量异常

### ISSUE THREAD

**Issue by errorCreate** [openspug/spug#358]
Spug 版本:v3.0.1-beta.6

## 问题重现步骤

1.配置应用/服务标识符含有特殊字符。例如符号“-”   应用名"dev-saas"
2.直接发布

## 报错/问题截图
![image](https://user-images.githubusercontent.com/43237070/127089865-6ee52a0c-db7f-42c2-8833-40cac6702767.png)

## 期望的结果
可以对特殊字符做处理，最简单的是将 "-" 转换为 "_"

**Comment by vapao** [comment]
将 "-" 转换为 "_"，感谢反馈，将在 beta.7 更新

**Comment by vapao** [comment]
beta.7 已发布
