### ISSUE TITLE
建议：主机管理添加隧道连接 

### ISSUE THREAD

**Issue by janyyy** [openspug/spug#363]
目前我们在使用过程中，存在一些跨区域（香港、欧洲、新加坡服务器等）且无公网IP的服务器，无法通过主机管理添加，希望添加隧道连接。即通过某台有外网的机器代理连接过去。

![image](https://user-images.githubusercontent.com/27274865/127857297-eab638aa-269a-444b-aeea-58d114c94638.png)

**Comment by janyyy** [comment]
![image](https://user-images.githubusercontent.com/27274865/127857448-285d934d-9e7d-44b8-8f77-8ca83bcba823.png)
![image](https://user-images.githubusercontent.com/27274865/127857464-d571dcbc-c2b9-45b2-be3b-5ddee2a802cd.png)

**Comment by vapao** [comment]
收到，感谢建议，会加入计划

**Comment by LunacyZeus** [comment]
我用nps把流量转发出来🤧
