### ISSUE TITLE
需求：希望在这里能先选择发布环境再选择应用 

### ISSUE THREAD

**Issue by wuai1024** [openspug/spug#366]
Spug 版本:v2.3.17

## 问题重现步骤

1. 目前给角色分配发布权限的时候，希望能先选择发布环境，然后展示发布环境下面的应用
2.再选择应用分配给当前角色，目前全部展示出来了，太多了，也不知道哪个是前端项目哪个是后端项目
3.我们团队目前是3种角色在发版，后端开发，前端开发，测试人员都可以发版。

## 报错/问题截图
![image](https://user-images.githubusercontent.com/13379708/128679252-039d5443-f798-41ee-ad58-ddd8c8e4662f.png)

## 期望的结果

期望能先选择发布环境，再选择该环境下面的应用，给角色分配发布权限

**Comment by wuai1024** [comment]
spug有人收到吗？在看吗？

**Comment by vapao** [comment]
大部分情况一个应用在各个环境下都需要发布，所以先选择环境应该也不能很好的解决问题。
建议你如果想去分前端应用和后端应用的话，可以在应用名字上通过添加不同前缀或后缀，然后就可以方便的通过搜索来过滤并选择应用了。

**Comment by wuai1024** [comment]
加上前缀和后缀后 发布选择应用的时候 展示有问题
![image](https://user-images.githubusercontent.com/13379708/129565664-a767b556-65d0-4111-92ba-bd83274cd97c.png)

没有必要我就不提了，发布的时候已经分的很细了。

分配权限的时候痛苦的很，目前现有 服务25+

**Comment by wuai1024** [comment]
目前尽量已经把应用的名称控制在4个字，这样发布的时候选择应用稍微好些。

不过也是只改进建议，具体采纳与否还得你们考虑

**Comment by vapao** [comment]
v2.3.18 已发布，改进这个问题。
