### ISSUE TITLE
建议：提供 docker 构建能力

### ISSUE THREAD

**Issue by ZzMark** [openspug/spug#370]
目前构建流程和部署流程分离开，方便了很多
不过一个大问题还是存在，构建环境依然过于依赖 spug 部署的环境，要么时 spug 容器内，要么是裸机安装 spug 的主机环境

目前有个想法，容器基于 docker:dind 镜像，部署时再部署一个 dind 容器，这样 spug 就可以使用 docker 的环境来做构建了
类似于 DroneCI 、gitlab CI 的构建流程

目前我将 /var/lib/docker 和 docker.sock 映射到了主机内，效果不尽人意

**Comment by dustinyounglee** [comment]
按照官网compose里面加这个会提示
docker: /lib64/libc.so.6: version `GLIBC_2.32' not found (required by docker)
docker: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by docker)

**Comment by totobo** [comment]
> 

我测试没有这个问题，配置贴出来一起看看
