### ISSUE TITLE
Bug:  添加的主机类别会自动消失

### ISSUE THREAD

**Issue by k1z** [openspug/spug#372]
Spug 版本:
supg 2.3.17 
## 问题重现步骤

1.  正常添加主机类别 
2.  时常出现无效的数据格式

## 报错/问题截图
![MR9RICCISD GE EB6WO({$J](https://user-images.githubusercontent.com/24261046/131603569-e0331498-8c7e-49d7-8b0e-94067846bbe1.png)
![image](https://user-images.githubusercontent.com/24261046/131603685-3f4e300e-0fbe-4faa-b149-8b174609cb3f.png)
![image](https://user-images.githubusercontent.com/24261046/131603692-340c295b-2586-4f5f-8742-1d837a4c0b09.png)

**Comment by k1z** [comment]
想了下 可能是设计的问题， 我添加完主机类别 没有添加主机， 所以主机类别是不单独入库的？  但是一直弹无效的数据格式是什么问题？ docker也有这个问题。。。

**Comment by vapao** [comment]
你这个应该是因为网络劫持，可以使用 https 再试下，或者换个网络
