### ISSUE TITLE
Bug: 发布申请: Exception: Wait spug response timeout

### ISSUE THREAD

**Issue by PrintNow** [openspug/spug#378]
环境：`Docker` for mac

Spug API版本: `v3.0.1-beta.9`
Spug Web版本: `v3.0.1-beta.9`

## 问题重现步骤

1. 发布申请 
2. 新建发布

### 构建配置：

**文件过滤规则:**
```
dist
```

**代码检出前执行**:
```shell
# 创建公共node_modules目录
echo $SPUG_REPOS_DIR/$SPUG_DEPLOY_ID/node_modules
mkdir -p $SPUG_REPOS_DIR/$SPUG_DEPLOY_ID/node_modules
```

**代码检出后执行**:
```shell
pwd
ls

ln -s $SPUG_REPOS_DIR/$SPUG_DEPLOY_ID/node_modules .
yarn
yarn build

pwd
ls
```

**应用发布前执行:**
```shell
pwd
ls
```

**应用发布后执行:**
```shell
```

## 报错/问题截图

![image](https://user-images.githubusercontent.com/28396104/132981609-b0c21c08-3820-4702-aa92-6443ea095e8d.png)

回滚任务也失败：
![image](https://user-images.githubusercontent.com/28396104/132981769-45628633-73b4-4276-9a4a-202dae085af5.png)

## 期望的结果

🔩成功发布

**Comment by cmVtaQ** [comment]
我们执行任务的机器使用zsh时也遇到了这个问题，切换为bash后正常执行。或者参考这个临时兼容zsh的方案：

修改 spug_api/libs/ssh.py 如下两行代码（branch 3.0）
```
@@ -18,7 +18,7 @@ class SSH:
         self.sftp = None
         self.eof = 'Spug EOF 2108111926'
         self.default_env = self._make_env_command(default_env)
-        self.regex = re.compile(r'Spug EOF 2108111926 -?\d+[\r\n]?$')
+        self.regex = re.compile(r'Spug EOF 2108111926 -?\d+[\r\n]?\n?')
         self.arguments = {
             'hostname': hostname,
             'port': port,
@@ -132,7 +132,7 @@ class SSH:

         counter = 0
         self.channel = self.client.invoke_shell()
-        command = 'export PS1= && stty -echo'
+        command = 'export PS1= && unsetopt ZLE; stty -echo'
         if self.default_env:
             command += f' && {self.default_env}'
         command += f' && echo {self.eof} $?\n'
```

**Comment by PrintNow** [comment]
> 我们执行任务的机器使用zsh时也遇到了这个问题，切换为bash后正常执行。或者参考这个临时兼容zsh的方案：
> 
> 修改 spug_api/libs/ssh.py 如下两行代码（branch 3.0）
> 
> ```
> @@ -18,7 +18,7 @@ class SSH:
>          self.sftp = None
>          self.eof = 'Spug EOF 2108111926'
>          self.default_env = self._make_env_command(default_env)
> -        self.regex = re.compile(r'Spug EOF 2108111926 -?\d+[\r\n]?$')
> +        self.regex = re.compile(r'Spug EOF 2108111926 -?\d+[\r\n]?\n?')
>          self.arguments = {
>              'hostname': hostname,
>              'port': port,
> @@ -132,7 +132,7 @@ class SSH:
> 
>          counter = 0
>          self.channel = self.client.invoke_shell()
> -        command = 'export PS1= && stty -echo'
> +        command = 'export PS1= && unsetopt ZLE; stty -echo'
>          if self.default_env:
>              command += f' && {self.default_env}'
>          command += f' && echo {self.eof} $?\n'
> ```

好的，谢谢，我试试

**Comment by vapao** [comment]
@cmVtaQ  感谢建议，已发布新版本改进zsh的兼容性。

**Comment by vapao** [comment]
先关闭了，如有问题再重新打开

**Comment by lesons** [comment]
> 先关闭了，如有问题再重新打开

还是不行我用的最新版，卸载zsh 就可以发布成功 用zsh就不行

**Comment by vapao** [comment]
发下 zsh 和 操作系统的版本

**Comment by lesons** [comment]
> 发下 zsh 和 操作系统的版本

zsh 5.0.2
Linux version 3.10.0-957.21.3.el7.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-36) (GCC) ) #1 SMP Tue Jun 18 16:35:19 UTC 2019
CentOS Linux release 7.6.1810 (Core)
