### ISSUE TITLE
Bug: Websocket链接错误

### ISSUE THREAD

**Issue by yadgen** [openspug/spug#388]
环境是本地，手动部署，非docker，可能问题比较低级，看了几天都不知如何解决，想单独配一个ws的域名，也没找到方法。

操作系统macOS-11.6-x86_64-i386-64bit
Python版本3.9.7
Django版本2.2.24
Spug API版本v3.0.1-beta.12
Spug Web版本v3.0.1-beta.12

Spug 版本: v3

## 问题描述，步骤
构建的时候，ws连接错误。
[参考文档](https://spug.cc/docs/install-error#%E4%B8%BB%E6%9C%BA-console-%E6%88%96%E6%89%A7%E8%A1%8C%E5%8F%91%E5%B8%83%E9%A1%B5%E9%9D%A2%E6%97%A0%E5%86%85%E5%AE%B9)，也无法解决，因为nginx的域名冲突了。

## 报错/问题截图
![1](https://user-images.githubusercontent.com/1206012/136888001-18f1d003-a4b8-430c-8674-4ca41bb536d4.jpg)
![2](https://user-images.githubusercontent.com/1206012/136888007-fccea813-847a-48e9-8cbd-fa6349cddb79.jpg)

## 期望的结果
请问如何配置？

**Comment by vapao** [comment]
不知道你说的nginx域名冲突是指的什么，可以参考 https://spug.cc/docs/deploy-product 手工部署的文档看下。

**Comment by vapao** [comment]
具体原理可以参考 https://spug.cc/docs/practice 
目前看来出现这种问题主要两个原因：
- nginx 配置问题，造成spug获取到ip变化
- 你的网络出口ip可能存在多个，所以确实在来回变化。 这种情况可以考虑把上述nginx配置修改为 `proxy_set_header X-Forwarded-For 1.1.1.1;` 这样来让spug 获取固定的ip地址。

**Comment by yadgen** [comment]
> 具体原理可以参考 https://spug.cc/docs/practice 目前看来出现这种问题主要两个原因：
> 
> * nginx 配置问题，造成spug获取到ip变化
> * 你的网络出口ip可能存在多个，所以确实在来回变化。 这种情况可以考虑把上述nginx配置修改为 `proxy_set_header X-Forwarded-For 1.1.1.1;` 这样来让spug 获取固定的ip地址。

好的，非常感谢。
