### ISSUE TITLE
Bug: 各个页面都提示无效的数据格式

### ISSUE THREAD

**Issue by zjning95** [openspug/spug#389]
Spug 版本:最新版

## 问题重现步骤

1.点击任意页面，提示报错，但不影响使用

2.

## 报错/问题截图

![image](https://user-images.githubusercontent.com/26339492/136942827-2053a16e-7308-456f-add3-74324f4ac52d.png)

**Comment by vapao** [comment]
之前有遇到都是网络劫持的问题，需要使用https， 不过你这全都报这个提示的话可能是其他问题。 可以在你截图的这个地方，点下网络看下请求返回的具体内容。

**Comment by zjning95** [comment]
![Uploading 企业微信截图_16342814199299.png…]()

**Comment by zjning95** [comment]
升级了新版本，这个问题还是存在，有时候第一次进到某个页面会提示这个报错，刷新或者重新进入又不会报了
![image](https://user-images.githubusercontent.com/26339492/140857049-58d1235e-08a0-4ada-a9cb-a6785f6cd1ac.png)

**Comment by vapao** [comment]
可以从 network 选项卡里看下 接口返回的什么内容截图发下。

**Comment by zjning95** [comment]
![image](https://user-images.githubusercontent.com/26339492/140874825-fe5482aa-cce9-4bb8-a517-10b8848eb3b6.png)

**Comment by vapao** [comment]
这看起来就是网络劫持，如果能用 https 的换下https

**Comment by zjning95** [comment]
好的，这个1.1.1.3是公司的网络认证的地址，应该确实是网络的原因
