### ISSUE TITLE
Bug: 新添加的主机如果安装了docker，则在主机列表中显示的ip是docker0设备的ip，不是添加主机时的ip

### ISSUE THREAD

**Issue by ArvinRong** [openspug/spug#391]
Spug 版本:

Python版本3.6.8
Django版本2.2.22
Spug API版本v3.0.1-beta.12
Spug Web版本v3.0.1-beta.12

## 问题重现步骤

1.导入主机列表
2.执行验证
3.验证成功后查看主机列表

## 报错/问题截图
其中部分安装了docker的主机在列表中显示的ip为docker0设备的ip，不是实际导入的ip
显示的ip：
![image](https://user-images.githubusercontent.com/3940375/138018649-5e38cf0b-3893-48c8-a723-493e7a0f9ace.png)
实际导入时的ip：
![image](https://user-images.githubusercontent.com/3940375/138018701-2a7c6fb3-7277-464d-a6e4-fce02daae44d.png)

主机上ifconfig查看网络设备信息：
![image](https://user-images.githubusercontent.com/3940375/138019215-3bade4d3-8cce-46e2-9b34-235d0366de1d.png)

## 期望的结果
主机列表中显示的ip为实际导入的主机网络设备ip 10.147.12.60

**Comment by cxhello** [comment]
我也有同样的问题****

**Comment by cxhello** [comment]
![image](https://user-images.githubusercontent.com/49056040/138224564-1994cefd-b2c1-4ab6-be62-7b3549448b2e.png)
解决了，点击此处可以看到系统获取了两个IP，手动可以修改
![image](https://user-images.githubusercontent.com/49056040/138224510-6b4f9214-1101-46ff-b1ec-28ef2b028681.png)
