### ISSUE TITLE
Bug: Web终端中的文件功能将软连接识别为文件，导致不能直接进入目录

### ISSUE THREAD

**Issue by hjk0205** [openspug/spug#394]
Spug 版本: 
v3.0.1-beta.12

## 问题重现步骤

1.在web终端中链接一个服务器，
2.打开文件管理器

## 报错/问题截图
![QQ截图20211102101439](https://user-images.githubusercontent.com/18556156/139775840-8427d592-0eda-466d-8789-26c7c145163c.png)

## 期望的结果
能够正确点击文件夹图标进入文件夹

**Comment by vapao** [comment]
下个版本改进，感谢反馈。

**Comment by vapao** [comment]
v3.0.1-beta.13 已发布可以更新。
