### ISSUE TITLE
customized crontab rules is invalid 

### ISSUE THREAD

**Issue by shishuchao** [openspug/spug#396]
Spug 版本: v2.3.17

## 问题重现步骤

1. 左侧导航栏，进入【任务计划】，新建任务，创建 "UNIX cron 执行规则"
2. 录入图中所示的规则 “0 1 * * 2-7/2” , 该规则在 https://tool.lu/crontab/ 中可以正确地预览

## 报错/问题截图
![image](https://user-images.githubusercontent.com/43273500/140486066-f12ec75b-b65e-48a8-ae9c-34404c9c5817.png)

## 期望的结果
如果 “ 0 1 * * 2-7/2” 确实正确，期望支持该形式的规则

**Comment by vapao** [comment]
感谢反馈将在 v2.3.18更新。

**Comment by vapao** [comment]
已发布 2.3.18
