### ISSUE TITLE
应用发布->构建仓库出现错误

### ISSUE THREAD

**Issue by breaklinux** [openspug/spug#398]
Spug 版本:
![image](https://user-images.githubusercontent.com/23096478/140877357-496b15af-a128-46ba-80aa-44793811a3ac.png)

## 问题重现步骤

1.必现 应用发布-构建仓库-新建构建出现问题 
2.

## 报错/问题截图
![image](https://user-images.githubusercontent.com/23096478/140877260-4104f138-2155-4cfe-af6b-5f01e1f026ea.png)

## 期望的结果 
拉取正常版本代码信息

**Comment by breaklinux** [comment]
知道源码如下图解决了 修改 默认:true  修改false 正常了
![image](https://user-images.githubusercontent.com/23096478/140879720-017d36fb-a639-4b9b-bdcb-f0b4ac77cf09.png)

**Comment by vapao** [comment]
安装文档已经说明了，需要git 2.17.0+
