### ISSUE TITLE
Bug:  账号密码正确，但是登录时候经常报 回话过期请重新登录，但是重新登还是这样

### ISSUE THREAD

**Issue by myxyz** [openspug/spug#399]
Bug:  账号密码正确，但是登录时候经常报 回话过期请重新登录，但是重新登还是这样
![image](https://user-images.githubusercontent.com/5306695/141104865-0e35ca6f-8f17-45af-aeb2-3c12e7d864c9.png)

**Comment by zyupo** [comment]
默认登陆过期时间为8小时，账号为单点登录机制，确保同一个账号一次只有一个人登录了。

**Comment by vapao** [comment]
可以参考下 #388

**Comment by vqljiang** [comment]
账号只能一次性登录一次
