### ISSUE TITLE
需求：发布申请支持模块选择

### ISSUE THREAD

**Issue by nice555** [openspug/spug#401]
使用场景：一个仓库下包含多个模块，有时只需构建部分模块。
建议在创建应用或者创建发布流程的时候能添加所有模块名称，在创建发布申请的时候可以自由选择需要模块并添加到环境变量

**Comment by zxcvbnm3057** [comment]
这个功能现在有吗，今天刚尝试了Drone，那个没法选择模块，每次有更新全部服务重启太耽误了

**Comment by nice555** [comment]
自己加了个字段，用的自定义发布，代码发布的时候传递SPUG_RELEASE变量，然后再shell里面处理

**Comment by nice555** [comment]
> 自己加了一个字段，用的自定义发布，代码发布的时候动态SPUG_RELEASE变量，然后再shell处理里面

**Comment by nice555** [comment]
> 这个功能现在有吗，今天刚尝试了Drone，那个没法选择模块，每次有更新全部服务重启太耽误了
