### ISSUE TITLE
Bug: 监控中站点检测能否提供https站点监控能力

### ISSUE THREAD

**Issue by zjning95** [openspug/spug#403]
Spug 版本:最新版

## 问题重现步骤

1.添加https站点检测报错

## 报错/问题截图
![image](https://user-images.githubusercontent.com/26339492/141932445-25a7972c-9442-4795-b4cd-6eecb995f15c.png)

## 期望的结果
可以检测https站点

**Comment by vapao** [comment]
是支持https的，这个提示应该是证书验证失败了。
