### ISSUE TITLE
Bug: 腾讯云验证成功后内外网ip混乱

### ISSUE THREAD

**Issue by vqljiang** [openspug/spug#407]
Spug 版本:

## 问题重现步骤

1.使用AccessKey获取主机和内网地址
2.然后批量验证，验证失败不变，验证成功后内网地址会被标记为公网地址
3.在编辑里重新获取信息还是显示外网地址

## 期望的结果

能够区分内外网地址，不混乱

**Comment by vapao** [comment]
能发个截图看下吗？ 我这里没能复现问题。

**Comment by NagaResst** [comment]
他会从多个网卡里选取其中一个显示出来 甚至还会显示docker的虚拟网卡地址

**Comment by vapao** [comment]
默认列表里显示的是第一个ip， 可以在主机详情里调整顺序。

**Comment by vqljiang** [comment]
![16388400243116](https://user-images.githubusercontent.com/73462160/144949950-ad863911-b907-4876-9136-c8172b79cdd5.png)
![16388400798541](https://user-images.githubusercontent.com/73462160/144949989-ecc04472-a1f4-4cee-b05d-1edcf8f75228.png)
![16388401345893](https://user-images.githubusercontent.com/73462160/144950010-ac47c429-b7e3-48cd-a391-2d6330f45713.png)
![1638840186141](https://user-images.githubusercontent.com/73462160/144950025-fd147baf-efab-4d49-a85e-d5143d9f1537.png)
各位大佬看一下，具体就是这样

**Comment by vqljiang** [comment]
> 默认列表里显示的是第一个ip， 可以在主机详情里调整顺序。

那我有几百台机器一验证全都成外网ip了，我得一个一个改，验证成功后有的还会把内网ip变成外网ip，再拉一个docker网卡地址来当内网ip

**Comment by vqljiang** [comment]
> > 默认列表里显示的是第一个ip， 可以在主机详情里调整顺序。
> 
> 那我有几百台机器一验证全都成外网ip了，我得一个一个改，验证成功后有的还会把外网ip变成那内网ip，再拉一个docker网卡地址来当内网ip 磁盘也会乱拉很多1G的 ![image](https://user-images.githubusercontent.com/73462160/144950572-2303eb03-0f70-469b-bf76-1d2acb1cc529.png)

**Comment by vapao** [comment]
9 开头的按理说确实应该是 公网ip地址，  腾讯云的内网地址就是 9 开头的？

**Comment by vapao** [comment]
> 

磁盘的问题，下个版本会优化
