### ISSUE TITLE
建议: 批量执行的部分希望能有执行记录查询的功能

### ISSUE THREAD

**Issue by kaminosama** [openspug/spug#409]
用了一下感觉很好，但是公司业务上经常有细碎的突发需求，要经常用到批量执行。
然后IT流程管理部很不乐意，请问后续是否会有批量执行的部分记录一下操作和操作人的功能，谢谢~

**Comment by vapao** [comment]
计划中了，你那执行记录主要目的是为了从安全角度追踪执行记录，还是为了能够复用执行记录，比如经常重复执行某些内容？

**Comment by kaminosama** [comment]
> 计划中了，你那执行记录主要目的是为了从安全角度追踪执行历史，还是为了能够复用执行记录，比如经常重复执行某些内容？

感谢回复～
只要记录执行内容，时间和执行人即可，主要需求是要责任落实到人。

**Comment by vapao** [comment]
v3.0.1-beta.15 已发布，可以参考 https://spug.cc/docs/update-version 升级新版本。
目前的执行记录与你说的并不完全一致，我们会根据后续反馈，继续改进。
