### ISSUE TITLE
监控中心任务一直显示待检测

### ISSUE THREAD

**Issue by baoming158** [openspug/spug#41]
您好，
       监控中心任务一直显示待检测，是什么原因呢，是哪里还需要配置吗？

**Comment by zyupo** [comment]
监控中心模块添加的监控任务不会执行
监控中心功能需要启动额外的服务，通过以下命令启动，以下操作命令基于 标准安装 文档的环境
```
$ cd /data/spug/spug_api
$ source venv/bin/activate
$ python manage.py runmonitor
```

具体查看：
https://www.spug.dev/docs/install-error/
