### ISSUE TITLE
Bug: 自定义发布定时发布不生效

### ISSUE THREAD

**Issue by tucaoxingren** [openspug/spug#414]
Spug 版本: v3.0.1-beta.14

## 问题重现步骤

1. 新增应用 自定义发布
2. 新增应用发布申请 录入定时发布时间 点击发布

## 报错/问题截图
发布会马上进行

## 期望的结果
发布应该在设置的定时发布时间到后才开始发布

**Comment by vapao** [comment]
定时发布不需要再点击操作按钮发布了， 在指定的时间会自动发布，最多会有有1分钟的延迟。
