### ISSUE TITLE
需求：常规发布增加健康检查

### ISSUE THREAD

**Issue by onecer** [openspug/spug#417]
## 需求

我们之前在遇过因为包传输不完整、配置改错，代码问题等等原因导致发版后，服务未能正常启动。

所以希望在发布的时候，增加健康检查，这样发布有问题的服务就会暴露出来，及时把有问题服务影响范围缩小到第一次发布的几个机器。

比如10个副本，我们并行控制在2个，一旦健康检查通过，就会继续发布，如果不通过，就中断发布，把影响范围缩小。避免全都传输过去后，启动不了，影响正常业务。

## 功能

- 可自定义配置并行发布数量 分批次部署 （严格控制一次发版的数量，控制故障范围）
- 支持TCP和HTTP方式进行健康检查
- 可配置检查间隔和超时时间

## 健康检查判定

HTTP方式健康判定： 发送GET请求，HTTP状态为2xx和3xx都是正常的。

TCP方式健康判定： 创建套接字，进行TCP连接，能连接上指定端口则为健康。

**Comment by vapao** [comment]
非常感谢你的建议。
第一个配置并行数量的问题，不知道你现在部署的spug版本，目前最新的3.x的版本已支持设置发布模式 `并行` 或 `串行`，其中 `串行` 即一台一台依次发布，某个出错即终止发布，应该与你说的效果类似，但限制了并发数量。

下边的健康检查的问题，我们讨论过，认为单独提供这个功能没多大必要，因为你完全可以在 `发布后任务` 这个钩子内实现自己的检查逻辑，只要确保检查失败的时候 退出状态码 非0 （当退出状态码非0，spug会标记为发布失败） 即可达到效果。

**Comment by onecer** [comment]
> 

感谢回复。
我用的是3.x的版本，有并行和串行功能了。在我们使用场景中，希望可以自由控制并行数量。目前而言并行max(10, os.cpu_count() * 5)，串行一个一个来，不太好控制每个项目的并行数量。

比如我有些可能要部署50个副本，有些则就10来个副本。而我们希望在发布不同的项目的时候，控制并行数量。所以增加了个parallel_num。

至于健康检查这个，也考虑过你说的退出状态非0这个来中断。但是我们是有硬性需求，基于以下几点考虑。
1. 太多逻辑在发布后的shell层来体现，会显得冗余，让整体脚本变得难以维护。
2. 其次还要借助工具来实现，比如nc，curl之类的。有些机器可能没有这个工具，还要加上工具安装的脚本。
3. 判断状态码和连接需要很多代码实现，对于普通维护者来说，有点门槛。

作为任务发布系统，保障发布服务的健康其实也是其中一部分，为了降低配置和维护门槛，所以就增加进去了。

以上只是我们业务的一个需求，不代表广大用户的需求。仅作为抛砖引玉，作为一个维护者，保持一个系统简单也是很重要的事情。
