### ISSUE TITLE
ldap 用户删除之后。在登录。 无法接受管理。

### ISSUE THREAD

**Issue by smile-wang** [openspug/spug#42]
ldap 用户删除之后。在登录。 无法接受管理。

**Comment by vapao** [comment]
感谢反馈，将在 2.2.1 版本解决该问题（不允许删除ldap账户，提示使用禁用功能） 。
如果你想恢复之前被删除的ldap账户，请手动在数据库的 `users` 表中找到该用户，把 `delete_by_id` 字段置空即可。
