### ISSUE TITLE
Bug:web terminal主机多了没有滚动条

### ISSUE THREAD

**Issue by LunacyZeus** [openspug/spug#420]
这个WEB终端这里,我目前添加的主机有点多,然后貌似屏幕满了,下面的就不能点进去.....需要在前端这里加个滚动条之类的吧。
目前我解决方法是把网页缩放了，勉强能看到。
稍等 我在楼下补图

**Comment by LunacyZeus** [comment]
![QQ截图20211218191101](https://user-images.githubusercontent.com/20926865/146638993-f7ea8a7d-072c-4843-a802-b46ec1ebcdc8.png)
![QQ截图20211218191641](https://user-images.githubusercontent.com/20926865/146639010-de4a9ebf-f36e-4e46-9b93-80e427e4147f.png)

就像这样 我这里分组超过了30台主机,然后网页也不能滚动 我没办法点击下面的机器
目前版本是3.0.1-beta.15

**Comment by vapao** [comment]
非常感谢你的反馈，下个版本修复， 目前你可以临时使用搜索功能来过滤看不到的主机。

**Comment by vapao** [comment]
`v3.0.2` 已发布并修复了该问题。
