### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by zhangbei59** [openspug/spug#421]
## 期望的结果

是否可以增加agent功能，我们的环境是不允许root登录，也不允许使用sudo用户，现在都是手动xshell登录执行脚本。能否增加agent功能，通过agent的方式管理主机。

**Comment by vapao** [comment]
你说的agent指的什么，是在目标主机上部署一个守护程序？
你那边不允许root登录也不允许sudo，那么你通过xshell是以什么用户的身份登录的？
