### ISSUE TITLE
Bug: shell执行异常

### ISSUE THREAD

**Issue by wind-hx** [openspug/spug#422]
操作系统Linux-4.18.0-193.28.1.el8_2.x86_64-x86_64-with-centos-7.8.2003-Core
--
Python版本3.6.8
Django版本2.2.22
Spug API版本v3.0.1-beta.15
Spug Web版本v3.0.1-beta.15

## 问题重现步骤

1.任务计划 模块
2.配置任务脚本(脚本内容 停止java进程 -> 启动java进程) 这两部操作都会输出log文件
3.在Spug上查看任务计划的历史任务 发现没问题 能看到脚本里的log输出
4.通过终端ssh连上服务器 发现并没有执行 任务计划中的shell 也没有看到shell所输出的log文件

## 报错/问题截图

个人理解，这个问题偶尔会出现的，出现时仿佛Spug执行的shell脚本都在沙箱中执行的，在宿主机上看不到任何效果
还有个现象，偶尔会出现wget 下载文件 Spug显示下载完成 但是 ssh连上服务器发现还是旧的文件

## 期望的结果

所有Spug执行的shell脚本所产生的log以及杀进程等操作，都在宿主机上体现出来

**Comment by vapao** [comment]
脚本的log输出在哪里的 是文件还是标准输出？  如果是只是打印到控制台，你通过ssh连肯定看不到的。
wget下载的问题 你要看下当前执行wget的目录，默认不用 -o 参数的话默认下载到当前目录的。
Spug 没有沙箱。

**Comment by wind-hx** [comment]
<img width="899" alt="截屏2021-12-22 下午9 00 11" src="https://user-images.githubusercontent.com/17685971/147096751-88982911-dd27-4a51-b744-e57fd85b9afb.png">
这是我发布应用的流程

以下是upgrade_jar.sh内容
```
#!/usr/bin/env bash
#!/bin/sh
RESOURCE_NAME=xxx.jar
wget -O $RESOURCE_NAME https://cdn.xxx.com/xxx.jar

```

在spug上看执行流程没有任何问题 并且能看到wget控制台打印的数据，当wget执行完后，我通过ssh连上服务器发现文件并没有更新

我不知道是我的sh脚本有问题还是怎么回事

**Comment by wind-hx** [comment]
@vapao 麻烦你分析一下问题可能出现在哪里，是我的shell脚本有问题吗？发布应用所执行的两个shell脚本，我连上服务器执行没有任何问题。

**Comment by vapao** [comment]
`upgrade_jar.sh`  这个里边路径设置为绝对路径，或者你先 cd 到指定路径后再执行 wget

**Comment by wind-hx** [comment]
经过几天测试 sh脚本中加上cd跳对应路径就没问题了
感谢大佬解答
