### ISSUE TITLE
Bug: 传输较大文件时会中断，

### ISSUE THREAD

**Issue by zyfoan** [openspug/spug#429]
Spug 版本:

## 问题重现步骤

1.web terminal 的文件管理器中，传输较大的文件时会出现请求异常：Network Error

2.

## 报错/问题截图
![1640935935(1)](https://user-images.githubusercontent.com/96817966/147809956-d9471d8d-7b95-4c7b-af26-0b85e04e2709.jpg)

## 期望的结果
能够支持传输大文件。或者直接传输文件夹

**Comment by vapao** [comment]
上传的文件有多大？

**Comment by zyfoan** [comment]
> 上传的文件有多大？

40G

**Comment by ZzMark** [comment]
40G建议自行用 rsync 或者 sftp 来上传，文件太大了，不适合用浏览器做这种工作。性能不够高而且稳定性也没什么保证
