### ISSUE TITLE
报警联系组删除问题

### ISSUE THREAD

**Issue by linl12138** [openspug/spug#43]
删除已经有监控任务，监控联系人的报警联系组，前端页面显示删除成功，但实际未删除，且从逻辑上也应该不允许删除，后台代码逻辑发现是这样的：
 def delete(self, request):
        form, error = JsonParser(
            Argument('id', type=int, help='请指定操作对象')
        ).parse(request.GET)
        if error is None:
            detection = Detection.objects.filter(notify_grp__contains=f'\"{form.id}\"').first()
            if detection:
                return json_response(error=f'监控任务【{detection.name}】正在使用该报警组，请解除关联后再尝试删除该联系组')
            Group.objects.filter(pk=form.id).delete()
        return json_response(error=error)
水平有限，暂未查出问题出在哪？

**Comment by vapao** [comment]
感谢反馈，前端调用了错误的接口， 将在2.2.1 版本修复该问题。
