### ISSUE TITLE
Bug: 在gitlab上不能通过合并分支的方式来触发webhook

### ISSUE THREAD

**Issue by NagaResst** [openspug/spug#434]
Spug 版本: 3.0.4

## 问题重现步骤

与gitlab集成的时候，只能通过推送事件触发webhook，不能通过合并事件触发webhook（返回http 400    ref  ）。
看了一下源码。似乎auto_deploy的函数是通过 'ref' 来检索的，所以不能通过合并分支的方式触发。

## 期望的结果

希望可以支持合并分支触发webhook。

**Comment by NagaResst** [comment]
已经通过其他方式解决

**Comment by GkingF** [comment]
> 已经通过其他方式解决

请问是通过什么方式解决的

**Comment by kyle6364** [comment]
怎么解决的

**Comment by NagaResst** [comment]
@GkingF @kyle6364  不解决 直接用提交的方式触发  反正合并了之后也会有新的提交记录

**Comment by dg-jj** [comment]
自己改一下代码吧，自己改了一下，可用：
路径：spug_api\apps\apis\deploy.py

`    # object_kind
    if(repo=='Gitlab'):
        if(body['object_kind']=='merge_request' and body['object_attributes']['merge_status']=='can_be_merged' and body['object_attributes']['state']=='merged'):
            commit_id = body['object_attributes']['merge_commit_sha']
            ref = body['object_attributes']['target_branch']

            if commit_id != '0000000000000000000000000000000000000000' and ref == request.GET.get('name'):
                message = body['object_attributes']['title']
                Thread(target=_dispatch, args=(deploy_id, ref, commit_id, message)).start()
                return HttpResponse(status=202)
`

![Image](https://github.com/user-attachments/assets/74194f1a-0aaf-4976-96c1-252360a24332)
