### ISSUE TITLE
Bug: Docker安装，迁移数据，重启容器登录报错

### ISSUE THREAD

**Issue by jiangfei1995** [openspug/spug#441]
Spug 版本:  Docker最新版本 docker pull registry.aliyuncs.com/openspug/spug

## 问题重现步骤

1.Docker方式启动
docker run -d --restart=always --name=spug -p 80:80 -v /spug:/data registry.aliyuncs.com/openspug/spug

2.迁移数据到其他服务器目录下如/home/spug，重启
docker run -d --restart=always --name=spug -p 80:80 -v /home/spug:/data registry.aliyuncs.com/openspug/spug

## 报错/问题截图
登录报错
![image](https://user-images.githubusercontent.com/50936045/150942444-401d894b-f7c9-435e-88fc-e287cb8bdc02.png)

Exception: (2002, "Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)")

## 期望的结果
正常登录使用

**Comment by vapao** [comment]
应该是文件权限的问题，可以执行以下命令后再重启容器测试：
```bash
docker exec -it spug bash
chown mysql.mysql -R /data/mysql
```

**Comment by aaro-n** [comment]
同样遇到过，是使用Docker Compose安装的，看了正常运行的文件权限：
`drwxr-xr-x 6   27 sudo 4096 Feb  3 09:10 mysql`
`drwxr-xr-x 7 root root 4096 Dec 27 08:57 spug`
修改对应的文件归属权限
`sudo chown -R 27:sudo  mysql`
`sudo chown -R root:root spug`
执行`docker-compose down`，删除容器
执行`docker-compose up -d`，重新创建运行容器

**Comment by jiangfei1995** [comment]
> 应该是文件权限的问题，可以执行以下命令后再重启容器测试：
> 
> ```shell
> docker exec -it spug bash
> chown mysql.mysql -R /data/mysql
> ```

有效果
