### ISSUE TITLE
Bug: SPUG_VERSION全局变量没有值

### ISSUE THREAD

**Issue by hryGithub** [openspug/spug#444]
Spug 版本: 3.0.4

## 问题重现步骤
1. 使用常规应用发布
2. 
## 报错/问题截图
发布脚本使用了SPUG_VERSION的环境变量，现在没有值，在V2版本是有值的
![微信图片_20220216175813](https://user-images.githubusercontent.com/32188410/154241245-9b69ef25-7d62-443d-a456-f2fdc34cfd6f.png)

## 期望的结果
SPUG_VERSION这个环境有值
![微信图片_20220216180209](https://user-images.githubusercontent.com/32188410/154241281-68e38dd7-7e83-4df0-a08e-7052585d8b83.png)

**Comment by hryGithub** [comment]
期望的结果是使用v2版本发布的

**Comment by vapao** [comment]
新版本已支持 SPUG_BUILD_VERSION
