### ISSUE TITLE
更新问题 获取更新失败: 

### ISSUE THREAD

**Issue by DylanBack** [openspug/spug#450]
v3.0.4 更新日志：
### 新增功能及改进

- 🛠 角色关联的账户信息现可以通过弹窗查看
- 🛠 常规发布配置文件过滤规则展示支持语法高亮
- 🛠 批量执行选择Python时将优先使用python3
- 🐞 修复自定义发布某些情况下一直显示等待调度的问题
发现新版本 v3.0.4 是否更新[y|n]？y
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   279  100   279    0     0    347      0 --:--:-- --:--:-- --:--:--   347
tar: This does not look like a tar archive

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
获取更新失败，排除网络问题后请附带输出内容至官方论坛反馈。

**Comment by vapao** [comment]
你那现在的 版本是多少？  目前最新版本只支持 v3.x 的升级。

**Comment by DylanBack** [comment]
> 你那现在的版本是多少？当前最新版本只支持v3.x的升级。

2.x的版本；
我执行完升级命令后，现在一直500，在哪可以看错误日志？

**Comment by vapao** [comment]
```shell
docker exec -it spug bash
tail -100 /data/spug/spug_api/logs/api.log
```
如需帮助可以把日志发过来，协助你解决，你也可以加下 qq 或微信群 回复会更及时些。

**Comment by DylanBack** [comment]
![image](https://user-images.githubusercontent.com/42115674/157370439-d9e9e59c-def0-445e-bd59-cd76a92c4d30.png)


> ```shell
> docker exec -it spug bash
> tail -100 /data/spug/spug_api/logs/api.log
> ```
> 
> 如需帮助可以把日志发出来，协助你解决，你也可以加下 qq 或微信群 回复会更及时些。

![image](https://user-images.githubusercontent.com/42115674/157370450-34e8356e-1b16-4109-85be-58abef174226.png)
首页请求500，并无日志

**Comment by vapao** [comment]
```shell
docker exec -it spug bash
cd /data/spug
curl -o web.tar.gz https://cdn.spug.cc/spug/web_v2.3.18.tar.gz
mv spug_web/build spug_web/build.bak
tar xf web.tar.gz -C spug_web/
```
执行下这些命令试试

**Comment by vapao** [comment]
如有需要请再次打开

**Comment by DylanBack** [comment]
mv: cannot stat ‘spug_web/build’: No such file or directory

**Comment by DylanBack** [comment]
可以了谢谢
