### ISSUE TITLE
Question:  发布问题

### ISSUE THREAD

**Issue by Quinlan-Z** [openspug/spug#451]
## 问题

请问下Coder：
1. 是否能够将spug部署为多副本模式
2. 如果能部署的话，多个副本是否会存在同一时间点击相同request的发布操作而导致发布多次的结果

**Comment by vapao** [comment]
先回答第2个问题，多副本部署不会造成点击相同request多次发布的情况。
第1个问题，可以多副本，但监控和任务计划会受影响，会出现同一个任务被多次调度执行的问题，这个可以通过更改 `/etc/supervisord.d/spug.ini` 配置文件来解决，删除 `[program:spug-monitor]` 和 `[program:spug-scheduler]` 相关配置段， 确保这两个进程只在其中一个副本内运行即可，

**Comment by Quinlan-Z** [comment]
感谢Coder的回复！ 
我还是有一个疑问, 代码中只看到req.status not in ('1', '-3')来控制不能发布。那如果在多副本模式下，同时快速点击request的发布操作，在第一个副本代码还未执行到req.status = '2'时，第二个副本刚好执行完req.status not in ('1', '-3')。这样会不会触发两次发布能  如果不会触发两次发布的话，那又在那个地方做了控制呢？ 请Coder指点

**Comment by vapao** [comment]
这个没有其他额外限制了，这个是个内部的运维平台，应该不需要应付高并发的场景。

**Comment by Quinlan-Z** [comment]
好的，谢谢回复！
