### ISSUE TITLE
Bug: 容器里的源有问题，导致容器yum将无法update或下载软件

### ISSUE THREAD

**Issue by RainNameless** [openspug/spug#452]
Spug 版本:

## 问题重现步骤

1.endpoint.repo:baseurl=https://packages.endpoint.com/rhel/$releasever/os/$basearch/
2.endpoint.repo 里的packages.endpoint.com域名  此域名已无对应的ip  已为空请及时修改

## 报错/问题截图
![image](https://user-images.githubusercontent.com/43627188/157356885-35209a2a-f5aa-4abe-9f7a-2792ddc3963e.png)

![image](https://user-images.githubusercontent.com/43627188/157356969-7254f155-0a54-4f1a-a87b-cae80ae7ac59.png)

**Comment by vapao** [comment]
收到感谢反馈，可以临时删除改源即可 `rm -f /etc/yum.repos.d/endpoint.repo`，镜像会随着下个版本更新。
