### ISSUE TITLE
Bug: 除admin用户外，其它用户没有新建应用权限

### ISSUE THREAD

**Issue by Haitianisgood** [openspug/spug#453]
Spug 版本:

v3.0.4

## 问题重现步骤

1.
2.

## 报错/问题截图

一个稍微大点组织，不太可能只有一个用户来创建应用的，起码都是以一个小组
## 期望的结果
希望自定义用户可以有 ”新建应用“的权限等相关功能

配置中心-应用配置 和应用发布-应用管理，业务功能令人疑惑，应用管理是不是应该叫发布管理更合适，

目前用下来，感觉是应用管理中，其实对某个应用发布到不同环境，一条记录指定对应一个环境，不能多个

**Comment by vapao** [comment]
关于 `新建应用` 的权限问题，是因为这个功能权限与角色的发布权限冲突了，在发布权限中明确授权的应用才会在页面上展示，如果开放了普通用户的 `新建应用` 权限，会出现用户新建完在页面上看不到的情况。因为现在账户支持多角色授权所以也无法自动处理这个发布权限问题，最终就把 `新建应用` 权限移除了。 如果需要多个人新建应用的话可以创建多个管理员账户即可，参考 https://www.spug.cc/docs/system-account 。

**Comment by vapao** [comment]
应用发布-应用管理 改名为 发布管理，感觉建议很不错，我们讨论后确定。  最后个问题没看明白。
