### ISSUE TITLE
Bug: LC_ALL: cannot change locale (zh_CN.UTF-8)

### ISSUE THREAD

**Issue by ayershub** [openspug/spug#454]
Spug 版本:

## 问题重现步骤

1. docker 运行后， 添加主机报LC_ALL: cannot change locale (zh_CN.UTF-8)

## 报错/问题截图

Exception: invalid literal for int() with base 10: '/etc/profile.d/lang.sh: line 11: warning: setlocale: LC_ALL: cannot change locale (zh_CN.UTF-8)\n/etc/profile.d/lang.sh: line 11: warning: setlocale: LC_ALL: cannot change locale (zh_CN.UTF-8)\n/root

**Comment by vapao** [comment]
你添加的这个主机是什么操作系统 哪个版本？
