### ISSUE TITLE
有支持ARM64 服务器Docker的镜像吗

### ISSUE THREAD

**Issue by qq592939740** [openspug/spug#456]

**Comment by vapao** [comment]
没有 arm的系统环境，github上有 dockerfile 可以尝试自己构建下。

**Comment by zhoucheng45** [comment]
请问下dockerfile 在哪儿获取呢？需要构建arm的环境。谢谢了

**Comment by zhoucheng45** [comment]
dockerfile 找到了。在dock里面

**Comment by vapao** [comment]
https://www.spug.cc/docs/install-docker/  已支持 arm64

**Comment by zhoucheng45** [comment]
您好，您的邮件我已经收到！请放心！，我会尽快回复！若有急事，请拨打15927970512！，祝工作顺利，身体健康！
