### ISSUE TITLE
node前端项目在安装依赖的时候，对于私有源会报错401

### ISSUE THREAD

**Issue by simplast** [openspug/spug#460]
在服务器已经配置了私有源的账号密码信息，在服务器容器内也是可以正常安装依赖的，
但是通过 spug_web平台安装依赖 提示401

**Comment by simplast** [comment]
401是私有npm源在未检测到权限许可的时候才会报错，但是实际上我已经配置了对应的账号密码并且确保无误

**Comment by vapao** [comment]
这个没有相关的环境也没有测试过，猜测你配置的账户密码信息可能只在当前会话有用。
方便的话把你配置账户密码的命令 和 spug 使用npm 安装以来的截图都发下，好确认具体的功能点。
