### ISSUE TITLE
能否支持低级的OpenSSH版本？

### ISSUE THREAD

**Issue by nwpulele** [openspug/spug#461]
在使用Spug添加主机的过程中，会报出E02错误。

按照官方文档，对ssh相应的文件夹权限也做了调整，甚至手动导入了公钥，还是不行。

拟纳管的主机用的SSH版本是Open SSH 4.7p1，OpenSSL 0.9.8g 19 Oct 2007。

由于这个主机是高度定制化的凝思系统，所以SSH版本无法升级。

**Comment by vapao** [comment]
这边没有这个版本的服务器也没法测试，spug 底层使用 paramiko 这个开源的库，如果这个库不支持的话我们也没太多办法。
你可以尝试自己实现在部署spug的容器里密钥连接这个主机，如果容器里可以密钥连接spug 应该也可以的。
