### ISSUE TITLE
咨询是否支持以下功能

### ISSUE THREAD

**Issue by changeflyhigh** [openspug/spug#463]
1、spug能否导入ldap用户？
2、购买腾讯云&阿里云的云主机后，spug能否支持自动更新主机列表
3、spug是否有接口调用用以添加IDC主机

**Comment by vapao** [comment]
1. 支持配置ldap登录， 登录验证通过会自动创建账户。
2. 支持从腾讯云、阿里云同步主机，但没有自动更新功能（因为spug并不会保存同步时输入的access key相关信息）。
3. 建议使用excel导入，有接口但没有优化外部调用，需要自己做相应开发。
