### ISSUE TITLE
关于web终端使用上的建议

### ISSUE THREAD

**Issue by madman163** [openspug/spug#464]
操作系统Linux-3.10.0-957.21.3.el7.x86_64-x86_64-with-centos-7.8.2003-Core
--
Python版本3.6.8
Django版本2.2.27
Spug API版本v3.0.5
Spug Web版本v3.0.5

web终端标签页能否增加菜单,以前主力使用jump server,现在由于任务计划 跟 批量执行任务 以及模板的便利性,开始使用spug进行运维.
但是web终端体验上,这个菜单spug是没有的,因为有比较多服务器有时候标签页开了一堆,一个个关闭麻烦,还有就是有些海外服务器经常断开需要重连功能,而不是还有关闭重新点击服务器打开.所以web终端操作有时候还是切到jump server,求增加这个实用功能.

![image](https://user-images.githubusercontent.com/78993576/160813365-28a2ff25-544d-4cda-99fe-247e6d50e841.png)
web终端这个常用功能 建议放在顶部菜单方便取用
![image](https://user-images.githubusercontent.com/78993576/160813580-13f9faab-6a0c-4f3e-bcf3-27ddab4b3514.png)

**Comment by vapao** [comment]
收到，感谢你的建议，会尽快实现。

**Comment by hmtiannan** [comment]
我觉得吧，jumpserver还是有他优秀的地方，建议spug直接接入jumpserver，由jumpserver来登录ssh终端，我就是这么实现的，直接通过SSO认证获取访问令牌，将主机从spug同步到jumpserver
![image](https://user-images.githubusercontent.com/20086500/161228768-63b2d05e-dbef-4796-a57b-f97ccb43d823.png)

**Comment by vapao** [comment]
v3.1.0+ 已支持。
