### ISSUE TITLE
Bug: 发布中，经常卡在“数据准备.....”，

### ISSUE THREAD

**Issue by indextank** [openspug/spug#466]
Spug 版本: 
![image](https://user-images.githubusercontent.com/6389841/161206850-cfe3d753-9feb-43be-a4e4-ac7c6caedf74.png)

发布的时候，经常会在这里卡住，很久，也不知道到底发生了什么.....以前用v2版本的时候从来没出现过，自从新安装部署了一套v3版本之后，该问题经常出现。

## 问题重现步骤

![image](https://user-images.githubusercontent.com/6389841/161206656-bbd2872f-6a53-4f89-bd38-4ff497a961a2.png)

**Comment by hmtiannan** [comment]
数据准备就是上传代码包慢，检查下发布平台到目标主机的网络情况，另外也可能是你的包真的太大了

**Comment by vapao** [comment]
是的，如果能内网连的最好主机配置称内网地址。

**Comment by suyanhj** [comment]
我今天也出现这个了，页面都显示1个小时了，文件总共就350M，用旧的walle是能正常发布的，现在准备把线上的也切换到spug，但一直卡住

**Comment by vapao** [comment]
这个应该只与部署spug的服务器和目标主机之间的网速相关。 可以尝试下通过scp等方式传下测试下之间的网速。

**Comment by suyanhj** [comment]
发布主机到目标主机的传输，是传压缩包吧，刚刚试了下，12M每秒的速度，也没出现网络问题
![image](https://user-images.githubusercontent.com/95021771/176807960-ae72900f-f659-49b7-9e45-064140ee6ac6.png)

**Comment by zyupo** [comment]
升级到最新版本看看这个问题是否存在，如果存在重新开issue

**Comment by luofeng0603** [comment]
我都是内网环境，也是这个问题

**Comment by luofeng0603** [comment]
找到问题了， 前端vue项目 在拷贝数据到远程服务器之前要把 node_modules 删除，不然它会一起打包进行传输，本来10M左右的项目，硬生生变成了 180M....然后经常就是 在数据准备这个环境卡死。。。。
