### ISSUE TITLE
Bug: 执行模板时报错

### ISSUE THREAD

**Issue by meizj** [openspug/spug#468]
Spug 版本:3.0.X

## 问题重现步骤

1.模板中有大量docker 命令时，执行会报错，在2.X版本或直接在主机中执行是正常的
2.

## 报错/问题截图
<img width="1233" alt="4975415158d6f6f7d4e1a68ad335282" src="https://user-images.githubusercontent.com/36879086/161436416-091e742a-fd7d-426a-8e69-91da91c62e96.png">

**Comment by vapao** [comment]
下个版本会修复，感谢反馈。
