### ISSUE TITLE
在应用管理定制发布的时候能不能像Jenkins一样有目标文件，进行排除多余目录

### ISSUE THREAD

**Issue by mowangzailin** [openspug/spug#47]
在Jenkins里面，打包后进行部署时，选择目标文件目录，可以排除目标文件的其他目录层，在部署的时候就不会出现那么多目录，麻烦研判下是否可以实现这个功能。同时Jenkins创建了一个工程可以多次使用发布，但spug不可以，成功发布后就不能再次使用。麻烦研判下能不能考虑增加这两个功能

**Comment by vapao** [comment]
常规发布是支持文件过滤功能，自定义发布考虑了灵活性没有预设额外功能，但可以自己通过命令来实现。
