### ISSUE TITLE
自定义发布不能定义构建配置

### ISSUE THREAD

**Issue by monlor** [openspug/spug#473]
自定义发布只能配置发布配置，不能配置构建配置

**Comment by vapao** [comment]
本地动作可以用来构建。

**Comment by monlor** [comment]
那”构建仓库“这个功能我有点迷惑，不是用来只构建不发布使用的么，这里不能选“自定义发布”里配置的内容
<img width="1297" alt="image" src="https://user-images.githubusercontent.com/20394007/163679291-09f1cab2-525f-4475-b9d4-16ccdbba1a7a.png">

**Comment by vapao** [comment]
目前的 “构建仓库” 是为常规发布服务的，自定义发布的定位就是完全自定义。

**Comment by vapao** [comment]
常规发布可以选择 “构建仓库” 里构建好的版本的进行发布。
