### ISSUE TITLE
Bug: 新建发布》选择应用 弹框样式显示错乱问题。

### ISSUE THREAD

**Issue by wuai1024** [openspug/spug#477]
Spug 版本: 2.3.18

## 问题重现步骤

以下是运行环境，包括spug，和浏览器，和我显示器

1.
![image](https://user-images.githubusercontent.com/13379708/164153612-0851ef55-58ef-4bac-8c2a-0195e953e9f5.png)

2.
![image](https://user-images.githubusercontent.com/13379708/164153647-62c0856f-13db-48f6-bf8a-298414d12a25.png)

3.
![image](https://user-images.githubusercontent.com/13379708/164153701-d9832929-f9d9-43c2-b6e7-d21465660d13.png)

## 报错/问题截图

![image](https://user-images.githubusercontent.com/13379708/164153846-5417640d-0bcf-4efa-b247-71539a05f52b.png)

## 期望的结果

正常显示

**Comment by vapao** [comment]
应该是浏览器窗口宽度不够的情况下会出现，浏览器全屏试下。
另外建议升级到 3.x
