### ISSUE TITLE
求一个离线升级教程，docker部署

### ISSUE THREAD

**Issue by 15120062651** [openspug/spug#481]
大概写一个步骤就成，感谢感谢！直接迁移数据库的话有一些问题
Exception: (1054, "Unknown column 'deploy_requests.fail_host_ids' in 'field list'")
![image](https://user-images.githubusercontent.com/73933070/165013285-df03657a-805b-4605-a4b8-cee4f3b92236.png)

**Comment by vapao** [comment]
https://github.com/openspug/spug/blob/3.0/spug_api/apps/account/management/commands/update.py 可以看下这个，大部分都是 shell 命令

**Comment by unixtommy** [comment]
解决了吗，我也遇到这个问题，3.0.5升级到3.1.5  打开页面就报 这个字段错误

**Comment by unixtommy** [comment]
我提示的是：Exception: (1054, "Unknown column 'deploy_requests.fail_host_ids' in 'field list'")

**Comment by unixtommy** [comment]
我提示的是：Exception: (1054, "Unknown column 'deploy_requests.fail_host_ids' in 'field list'")

**Comment by 15120062651** [comment]
> 我提示的是：Exception: (1054, "Unknown column 'deploy_requests.fail_host_ids' in 'field list'")

https://github.com/openspug/spug/blob/3.0/spug_api/apps/account/management/commands/update.py
研究一下这个脚本，就按这个就行   能成功，没有问题
