### ISSUE TITLE
Bug: 点击“web终端”，主机分类会自动展开

### ISSUE THREAD

**Issue by aaro-n** [openspug/spug#484]
Spug 版本: v3.1.2

## 问题重现步骤

1.浏览器点击“web终端”，在新的窗口栏中出现webssh界面。
2.看到左侧主机分类全部展开。

## 报错/问题截图
<img width="344" alt="截屏2022-05-01 下午12 25 24" src="https://user-images.githubusercontent.com/45537680/166132184-e76d6528-9291-454b-b88d-52ab3ae2143f.png">

## 期望的结果
需要能设置哪些能自动展开，例如图片中“腾讯云”可以自动展开，“搬瓦工”和“甲骨文”就不需要自动展开。

**Comment by vapao** [comment]
这个为了方便点选，默认全部展开了。 如果不想看到某些分组下的主机可以通过角色权限来控制，感觉没必要再增加设置是否自动展开的功能了。
