### ISSUE TITLE
Bug: {data: "", error: "Exception: (1406, "Data too long for column 'private_ip_address' at row 1")"}

### ISSUE THREAD

**Issue by cyhuauin** [openspug/spug#489]
Spug 版本:

操作系统Linux-5.10.104-linuxkit-x86_64-with-centos-7.9.2009-Core
--
Python版本3.6.8
Django版本2.2.27
Spug API版本v3.1.5
Spug Web版本v3.1.5

## 问题重现步骤
![image](https://user-images.githubusercontent.com/16019312/168952944-8eceb73a-96bb-40fa-bb96-c7d318195510.png)

在添加服务器时，如果服务器网卡中存在大量ipv6内网地址，会报错
{data: "", error: "Exception: (1406, "Data too long for column 'private_ip_address' at row 1")"}

## 报错/问题截图
报错原因为大量的ipv6地址会超出数据库表host_extend 中private_ip_address 设计的长度

## 期望的结果

修复代码中获取内网地址ipv6的问题。
我的临时解决办法时增加表的长度

**Comment by vapao** [comment]
v3.1.6 已修复，感谢反馈。
