### ISSUE TITLE
服务器如果已经禁止密码登录了，只能ssh key登录，那么第一次验证就是失败了

### ISSUE THREAD

**Issue by gengchen528** [openspug/spug#49]

**Comment by vapao** [comment]
这种情况可以手动来实现部署 `Spug` 服务器与目标主机的免密登录。如果已经可以免密登录的情况下添加主机是不需要密码验证的。

**Comment by gengchen528** [comment]
嗯 最后看了代码发现了  应该是我本地用了docker部署导致没有验证成功，下午再试试 谢谢您

**Comment by vapao** [comment]
使用中问题欢迎随时反馈😄

**Comment by gengchen528** [comment]
> 使用中有遇到问题欢迎随时反馈😄

发现一个问题，在发布流程中，我宿主机安装了node，但是执行node -v 和npm  -v的时候提示命令不存在，然而直接连接宿主机执行这个命令正常，这里你发送的shell脚本命令是使用了默认的shell么，用户可以自定义使用的shell环境么

**Comment by vapao** [comment]
你可以在脚本里执行 `echo $PATH` 来确定下脚本内的 `PATH` 变量的值，如果我满足需要可以通过使用 `export PATH=$PATH:/usr/local/bin` 类似这样的方式动态修改 `PATH` 变量，也可以使用命令的绝对路径。

**Comment by gengchen528** [comment]
> 你可以在脚本里执行 `echo $PATH` 来确定下脚本内的 `PATH` 变量的值，如果不满足需要可以通过使用 `export PATH=$PATH:/usr/local/bin` 类似这样的方式动态修改 `PATH` 变量，也可以使用命令的绝对路径。

执行后发现和直连的PATH变量不同 那这样的话看来只能用绝对路径来执行命令了，目前是宿主机有问题，远程连接其他主机倒是没有问题

**Comment by gengchen528** [comment]
使用了export PATH解决了问题

**Comment by CL545740896** [comment]
怎么导入 SSH KEY 进行登录主机呢？

**Comment by vapao** [comment]
[https://spug.dev/docs/host-manage/](https://spug.dev/docs/host-manage/)
