### ISSUE TITLE
菜单权限控制问题

### ISSUE THREAD

**Issue by heylel** [openspug/spug#5]
你好，我看到网站的菜单权限貌似是通过localstorage对象来存储并基于此来控制的。但这个对象前台用户是可以自己更改的，这样用户就可以自定义属性来修改权限（如localStorage.setItem('is_supper',"true")），他就能看到所有的菜单了。

**Comment by tglmm9377** [comment]
一个没有权限的账号，登陆后通过修改修改localstorage，is_supper=true后刷新再菜单中用户管理修改管理员密码
