### ISSUE TITLE
Bug: 选择目标主机界面，分组为多级目录时，右侧列表不显示主机信息

### ISSUE THREAD

**Issue by sfturing** [openspug/spug#502]
Spug 版本: v3.1.5
## 问题重现步骤

1.批量执行->执行任务->添加目标主机（除主机管理界面，其他选择主机都有此问题。）
2.主机分组目录为多级时，右侧列表不显示数据。

## 报错/问题截图
添加目标主机问题界面，如下图：
![2](https://user-images.githubusercontent.com/26762929/174101820-3cf379d9-fcb1-4055-bc0a-13f511129dec.png)

## 期望的结果
主机管理界面显示正常，如下图：
![1](https://user-images.githubusercontent.com/26762929/174101582-7caa5f59-98cd-4867-97a2-215d8fb2326e.png)
选择主机界面呈现的结果，与主机管理相同。

**Comment by vapao** [comment]
这个是故意的，主机列表里分组展示的包含子分组内的主机， 主机选择的弹窗里是不包含子分组的主机。
当时为什么这样设计.... 现在想不起来了 😅

**Comment by sfturing** [comment]
> 这个是故意的，主机列表里分组展示的包含子分组内的主机， 主机选择的弹窗里是不包含子分组的主机。 当时为什么这样设计.... 现在想不起来了 😅

哈哈，因为比较明显，之前还疑惑这是个feature还是bug。 多台主机和多层目录得情况下，去查找一个主机还是有点不太方便得，因为列表即不显示，也不支持搜索。

**Comment by vapao** [comment]
v3.2.0 已更新。
