### ISSUE TITLE
Bug: 构建控制台查看实时输出ws断开

### ISSUE THREAD

**Issue by laikee99** [openspug/spug#504]
Spug 版本: 
v3.1.7

## 问题重现步骤

1. 应用发布，应用构建
2. 点击日志等一会，或者查看第一步构建之后弹出的dialog框输出：Websocket connection failed!
3. ws断开，查看spug_api/logs/ws.log

## 报错/问题截图
![image](https://user-images.githubusercontent.com/28212423/174675223-21c823d6-bc2b-450e-8b1c-860c0c146b8c.png)
![image](https://user-images.githubusercontent.com/28212423/174675242-318cc5fc-6ec4-45b6-a696-f79fc0f71734.png)

## 期望的结果

正常日志持续输出

**Comment by yishenggudou** [comment]
这个修复了吗 我感觉 还在
