### ISSUE TITLE
Bug: 常规发布指定分支不生效

### ISSUE THREAD

**Issue by FelixLiuSheng** [openspug/spug#508]
Spug 版本:v3.1.7

## 问题重现步骤

1.常规发布配置
2.新建发布申请,选择指定分支

## 期望的结果
期望使用指定分支进行拉取且处理,但并未拉取指定分支,而是还停留在master分支

**Comment by vapao** [comment]
这个拉取是在代码检出时执行的，你不必关心repos 目录下的仓库信息。

**Comment by crazy-zzking** [comment]
实际上代码检出时也没有切换分支 
操作系统Linux-3.10.0-1160.62.1.el7.x86_64-x86_64-with-centos-7.9.2009-Core
--
Python版本3.6.12
Django版本2.2.28
Spug API版本v3.3.2
Spug Web版本v3.3.2

**Comment by vapao** [comment]
参考官方的配置示例， 代码检出是单独的目录，且检出后是个纯目录并不是 git 仓库，原 clone 的 git 仓库并不会变更。
