### ISSUE TITLE
监控中心能不能发送的消息能不能多一点？

### ISSUE THREAD

**Issue by legendjslc** [openspug/spug#51]
只返回状态信息，并不知道具体是什么情况。
比如说：我想知道每天某个指定文件夹下多了几个文件？每个文件的名称。
我希望看到每天的具体内容。

如果放在计划任务里，发不了短信。
如果放在监控中心里，发送回的信息太少。

**Comment by vapao** [comment]
你说的需求看起来更像是每天的定时巡检功能？可以再具体描述下你那边的需求吗？

**Comment by legendjslc** [comment]
我现在的一个需求是查看数据文件的接收情况：每天定时查看一个文件夹下今天的数据文件有几个，昨天的数据文件有几个。希望能收到短信或邮件提醒这个接收情况。
具体的功能用shell脚本是可以实现的，脚本的输出就是我需要的内容，用spug的计划任务也可以执行。但"计划任务"功能并没有发送短信的功能。

**Comment by vapao** [comment]
后期我们会提供专门的巡检模块来执行

**Comment by vapao** [comment]
v2.2.5 版本已改进监控中心能够看到更多的信息
