### ISSUE TITLE
使用独立密钥，添加新的VPS时，提示“独立密钥认证失败”

### ISSUE THREAD

**Issue by aaro-n** [openspug/spug#514]
Spug 版本:v3.1.7

## 问题重现步骤

1.创建新的vps，并且设置SSH密钥
2.在本地电脑使用SSH密钥登录刚刚创建的VPS，登录成功。
3.在spug使用相同的密钥问题，最后验证时提示“独立密钥认证失败”

## 报错/问题截图
<img width="679" alt="截屏2022-07-03 下午3 09 52" src="https://user-images.githubusercontent.com/45537680/177029193-ca63957d-e1ee-45bb-95ef-3e58a62d6d23.png">

## 期望的结果
添加新的VPS成功。

**Comment by vapao** [comment]
确定下是上传的私钥吧？ 
另外可以不用上传独立密钥，尝试通过密码连接后上 spug 来配置密钥认证。

**Comment by aaro-n** [comment]
下午测试过，
1.新建一个vps并设置SSH密钥，在笔记本电脑上可以连上vps，用spug新建主机，设置主机用户名、IP、端口，使用相同的密钥，提示“独立密钥认证错误”。
2.VPS开启密码和密钥登录，在spug上将上传的密钥删除，直接点“验证”，弹出要求输入vps登录密码，输入正确后，spug可以连接vps（使用spug默认密钥），在vps的.ssh目录下手动将电脑上保存的密钥添加进去。
3.在spug重新编辑刚刚创建的vps主机，将电脑上的密钥上传，点“验证”，又可以认证成功。
感觉spug在新建主机时密钥认证有问题。

**Comment by vapao** [comment]
还能复现问题步， 可以的话看下 vps 的 ssh 日志信息

**Comment by aaro-n** [comment]
在Macbook上已经通过SSH连接到VPS了，SPUG使用相同的密钥连接，在验证时提示“独立密钥认证失败”。下边是日志：
连接新的VPS，使用独立密钥，笔记本SSH可以正常登录VPS
```
Jul  4 20:25:42 ceshi sudo: pam_unix(sudo:session): session closed for user root
Jul  4 20:26:37 ceshi sshd[1292]: userauth_pubkey: key type ssh-rsa not in Pubke
yAcceptedAlgorithms [preauth]
Jul  4 20:27:09 ceshi sshd[1310]: userauth_pubkey: key type ssh-rsa not in Pubke
yAcceptedAlgorithms [preauth]
Jul  4 20:27:12 ceshi sshd[1312]: userauth_pubkey: key type ssh-rsa not in Pubke
yAcceptedAlgorithms [preauth]
```

**Comment by vapao** [comment]
请升级下最新的 v3.2.1

**Comment by aaro-n** [comment]
问题已解决，请关闭问题。
