### ISSUE TITLE
Bug: 作为一个运维看到手册好难受啊

### ISSUE THREAD

**Issue by chenxushuo** [openspug/spug#518]
自己系统的部署这部分做专业点啊，

**Comment by vapao** [comment]
😂 https://gitee.com/openspug/docs  文档在这里欢迎提交 PR

**Comment by vapao** [comment]
看到哪部分比较难受 ？

**Comment by chenxushuo** [comment]
一个容器运行一个服务啊，搞个docker-compose 把整个服务规范化下，包括mysql 服务

**Comment by vapao** [comment]
额， 收到

**Comment by vapao** [comment]
https://www.spug.cc/docs/install-docker/   已改为docker-compose 方式
