### ISSUE TITLE
主机添加问题

### ISSUE THREAD

**Issue by 20has** [openspug/spug#52]
强烈建议添加密码登录功能
以及 批量导入、自定义扫描网段、公有云接入等添加批量主机的方式

**Comment by vapao** [comment]
稍晚些时候会添加通过 `excel` 批量导入的功能。

**Comment by 20has** [comment]
嗯  excel模板导入很实用  网段扫描和公有云接入也搞起嘛

**Comment by vapao** [comment]
嗯，网段扫描和公有云接入会往后放
