### ISSUE TITLE
Bug: “首次验证时需要输入登录用户名对应的密码” 没有输入框

### ISSUE THREAD

**Issue by xminnn** [openspug/spug#521]
“首次验证时需要输入登录用户名对应的密码” 没有输入框

![image](https://user-images.githubusercontent.com/28984579/178241531-ec1c4bb4-1573-4e16-921f-bd2b37f2695c.png)

**Comment by xminnn** [comment]
找到问题了，不能添加密钥。不管是新建界面，还是验证界面。

验证界面也是下边报错
![image](https://user-images.githubusercontent.com/28984579/178243779-f8d809ac-17bb-4c2b-ac8b-ed5e05dc7a9f.png)

**Comment by zyupo** [comment]
什么操作系统，服务器不支持密码登录吗？

**Comment by xminnn** [comment]
> 什么操作系统，服务器不支持密码登录吗？

界面上独立密钥不能添加密钥，一添加点击验证就会报错，不添加密钥则会弹出输入密码。密钥是没有什么问题的。我试了下是可以登录的。

![image](https://user-images.githubusercontent.com/28984579/178720897-b837cc09-4e6c-4a7e-a8ba-a5eb61a108e1.png)

**Comment by vapao** [comment]
是个bug，当使用独立密钥时会触发。感谢反馈，将在 v3.2.1 修复。
