### ISSUE TITLE
Bug: ### Exception Wait spug response timeout

### ISSUE THREAD

**Issue by Icecream5100** [openspug/spug#522]
Spug 版本:

## 问题重现步骤

更新版本3.2.0后之前的机子 批量执行任务之后 ### Exception Wait spug response timeout

## 报错/问题截图
<img width="785" alt="image" src="https://user-images.githubusercontent.com/48505447/178474792-1e584f5c-ffa1-4ae1-b98f-fd6d9c8ae463.png">

**Comment by vapao** [comment]
可以远程调试不，加qq 或微信群。

**Comment by bigbenz8** [comment]
貌似这个问题一直都没有解决、这个工具基本就残了

**Comment by vapao** [comment]
已经确认了，是 v3.2.0 更新的问题，明天会发布新版本 v3.2.1 修复，感谢反馈。

**Comment by vapao** [comment]
仅在默认SHELL是 zsh 时会触发。

**Comment by bigbenz8** [comment]
> 已经确认了，是 v3.2.0 更新的问题，明天会发布新版本 v3.2.1 修复，感谢反馈。

感谢。有时候对开源软件要求太高了， 但这绝对是真爱^^ /

**Comment by vapao** [comment]
v3.2.1 已修复该问题

**Comment by vapao** [comment]
> > 已经确认了，是 v3.2.0 更新的问题，明天会发布新版本 v3.2.1 修复，感谢反馈。
> 
> 感谢。有时候对开源软件要求太高了， 但这绝对是真爱^^ /



> > 已经确认了，是 v3.2.0 更新的问题，明天会发布新版本 v3.2.1 修复，感谢反馈。
> 
> 感谢。有时候对开源软件要求太高了， 但这绝对是真爱^^ /

需要你们的鞭策 😄
