### ISSUE TITLE
Bug: 页面不展示发布配置

### ISSUE THREAD

**Issue by van0314** [openspug/spug#528]
Spug 版本: v3.2.0

## 问题重现步骤

1.发布配置中添加应用aaa,标识符aaa，并新建常规发布
2.因为在测试脚本，构建仓库中多次构建，多次发布应用
3.删除发布记录，删除发布配置，删除应用。
4.重新新建应用aaa，标识符aaa
5.新建常规发布，新建成功后，没有展示发布配置；删除应用也失败，提示有关联等发布配置

**Comment by van0314** [comment]
重新启动spug容器后解决

**Comment by vapao** [comment]
刷新页面看是否有效， 能否在演示环境 复现问题？ https://demo.spug.cc

**Comment by vapao** [comment]
v3.2.4 已修复该问题

**Comment by van0314** [comment]
后来发现是权限问题，用户可以在环境中创建新的发布配置，却无发布权限，导致无法查看
