### ISSUE TITLE
使用任务模板出错

### ISSUE THREAD

**Issue by legendjslc** [openspug/spug#53]
![117](https://user-images.githubusercontent.com/2969368/78956822-1c267200-7b16-11ea-9a6a-827d1e81e03d.png)

使用任务模板时出错？这是怎么回事？我从运行正常的shell脚本中拷贝代码过来也是出错。

麻烦大家指教一下。

**Comment by vapao** [comment]
你那使用的哪个版本？这个是在 windows 平台使用时换行符为 `\r\n` 引起的问题， [`v2.2.0`](https://spug.dev/docs/change-log/#220) 开始会自动帮移除命令中多余的 `\r` 字符，请是升级至最新版本，升级后重新编辑保存下有问题的命令即可。

**Comment by legendjslc** [comment]
是docker安装的，然后按文档升级，在docker中升级似乎有点问题。
![spug1](https://user-images.githubusercontent.com/2969368/79059347-773d9d80-7cab-11ea-9d2f-0c8befa2f4c5.png)

![spug2](https://user-images.githubusercontent.com/2969368/79059349-7a388e00-7cab-11ea-940a-76762e7bef19.png)

**Comment by vapao** [comment]
第一个截图少个 git  `git checkout v2.2.3`，请直接升级最新版本。 
下边的截图需要执行 `cd spug_api` 后在执行。
