### ISSUE TITLE
Bug: 常规发布选择“构建仓库”和“tag”后进行搜索时报错

### ISSUE THREAD

**Issue by nice555** [openspug/spug#530]
Spug 版本: 3.2.2
## 问题重现步骤
1.新建发布
2.选择“构建仓库”或“tag”后进行搜索时报错
## 报错/问题截图
![图片](https://user-images.githubusercontent.com/30033923/180630598-1cc8ecdc-d7a0-489c-9c89-ac2151f99ce3.png)

**Comment by vapao** [comment]
已复现，感谢反馈。 将在下个版本修复

**Comment by vapao** [comment]
已发布 v3.2.3 修复该问题。
