### ISSUE TITLE
Bug: 发布配置-常规发布无法解析 cp 命令 * 号

### ISSUE THREAD

**Issue by benzimu** [openspug/spug#533]
Spug 版本: v3.2.2

## 问题重现步骤

1.发布配置-常规配置增加 cp 脚本，如：`cp -rf /tmp/config/* /data/config`

## 报错/问题截图

```
cp: cannot stat ‘/tmp/config/*’: No such file or directory
```

**Comment by vapao** [comment]
我这测试没问题，你确认下这个目录是否存在。

**Comment by benzimu** [comment]
目录是存在的，最后使用 `cp -rf /tmp/config/. /data/config` 解决的
