### ISSUE TITLE
Bug: 首次与 Git 远程主机 ssh 认证的问题

### ISSUE THREAD

**Issue by zhanglianxin** [openspug/spug#534]
Spug 版本: `v3.2.3`。

## 问题重现步骤

当以下情况时： 

* `.ssh/known_hosts` 没有该主机记录存在

* *spug-api* 以 **supervisor** 方式启动

* `ssh_config` 默认配置

  ```bash
  cat /etc/ssh/ssh_config | grep Strict
  #   StrictHostKeyChecking ask
  ```

会出现：
`Exception: Cmd('git') failed due to: exit code(128) cmdline: git clone -v git@github.com:xxx/xxx.git /repos/2 stderr: 'Cloning into '/repos/2'... Host key verification failed. fatal: Could not read from remote repository. Please make sure you have the correct access rights and the repository exists. '` host key 认证失败。

## 期望的结果

建议：在不影响主机本身 `ssh_config` 配置的情况下，https://github.com/openspug/spug/blob/376f192f6e16f1514c277a6c586aed8f96693191/spug_api/libs/gitlib.py#L100 加入禁用 host key 检查的选项，参考 <https://unix.stackexchange.com/a/33273>。

**Comment by zhanglianxin** [comment]
And [GitPython 文档](https://gitpython.readthedocs.io/en/latest/tutorial.html#handling-remotes:~:text=StrictHostKeyChecking%3Dno%20is%20used%20to%20avoid%20prompts%20asking%20to%20save%20the%20hosts%20key%20to%20~/.ssh/known_hosts%2C%20which%20happens%20in%20case%20you%20run%20this%20as%20daemon.)中这样描述：

> *StrictHostKeyChecking=no* is used to avoid prompts asking to save the hosts key to *~/.ssh/known_hosts*, which happens in case you run this as daemon.

**Comment by vapao** [comment]
非常感谢
