### ISSUE TITLE
应用发布过程还是发布中是否可以取消

### ISSUE THREAD

**Issue by gdbug** [openspug/spug#54]
应用发布过程还是发布中时候，是否可以增加取消发布功能。
因为有时候发布都几十分过去了还是显示发布中真的好无奈啊。。。，一直在『检出前任务』那里不动，也不知道是什么原因（退出登录进入还是发布中）
![image](https://user-images.githubusercontent.com/22127372/78961059-9ceb6b00-7b22-11ea-89d6-73fa5fba3189.png)

**Comment by vapao** [comment]
取消发布目前还没法做到预想中的效果，你那部署的哪个版本的 `spug`，请更新到最新的 `v2.2.3` 测试下，如果还有问题请随便反馈。

**Comment by gdbug** [comment]
应该是部署失败了，可是也没反馈回失败原因，感觉可以参考walle发布过程，给出每一步执行命令
![image](https://user-images.githubusercontent.com/22127372/78963343-c1971100-7b29-11ea-951d-f8990d397f12.png)
我体验用的版本是v2.2.3
![image](https://user-images.githubusercontent.com/22127372/78963247-809efc80-7b29-11ea-8c31-8bace50b8f4b.png)
我后面测试提交的部署都成功的了，可是前面的还是发布中，而且没返回错误出错原因，如果可以参考walle那样显示出每一步执行命令，这样就好容易知道什么问题
![image](https://user-images.githubusercontent.com/22127372/78963494-2eaaa680-7b2a-11ea-8502-e826c5cf0c6e.png)

**Comment by vapao** [comment]
正常情况下都是可以看到出错原因的， 不太确定你的第一个发布是什么情况造成的。
如有再发现这种问题的，可以帮发下api的日志
