### ISSUE TITLE
建议：首页可以配置为默认LDAP登录，不然每次都要切换一下～

### ISSUE THREAD

**Issue by martin1847** [openspug/spug#544]
Spug 版本:

## 问题重现步骤

1. 开启ldap功能
2. 退出，重新进入登录页面

## 报错/问题截图
![Screen Shot 2022-08-17 at 3 35 09 PM](https://user-images.githubusercontent.com/449134/185061572-adc2ec66-c8c4-4765-8308-9cc2f407c9c5.png)

## 期望的结果

可以默认到LDAP页面，直接点登陆即可

**Comment by vapao** [comment]
非常感谢，下个版本加上。

**Comment by eryajf** [comment]
我刚刚部署的最新版本，在管理端没有看到这个配置项呢

**Comment by vapao** [comment]
自动的，如果选择了 LDAP 登录，下次会自动优先ldap

**Comment by eryajf** [comment]
> 自动的，如果选择了 LDAP 登录，下次会自动优先ldap

OK，另外提一个，是否有考虑支持ldap中基于分组的过滤。

**Comment by vapao** [comment]
下个版本会提供对ldap的更多支持

**Comment by eryajf** [comment]
> 下个版本会提供对ldap的更多支持

另有一个与此issue主题不太相关的题外话，请问是否可互加下readme推荐，我是 https://github.com/eryajf/go-ldap-admin 项目的作者🫡
