### ISSUE TITLE
答疑：请问spug数据准备阶段的传输速度非常慢 大概100k/s 这是正常的吗 求解答

### ISSUE THREAD

**Issue by bwensun** [openspug/spug#554]
如题 数据准备阶段大概要花十几分钟来传包

**Comment by bwensun** [comment]
补充一下 这个是因为走的是阿里云的公网流量 因为我的带宽是1M 所以是这个速度 但是正常服务器之间复制文件应该是可以走内网的 我想问下这个传输服务是怎么实现的 FTP吗

**Comment by vapao** [comment]
重复 #555
