### ISSUE TITLE
答疑: spug的操作上下文都在容器内，自定义发布那块可以可以在宿主机操作吗

### ISSUE THREAD

**Issue by bwensun** [openspug/spug#555]
Spug 版本: v3.2.4

## 问题重现步骤

因为文件传输太慢了 我想自定义发布 通过阿里云内网来传包 但是容器打包完了之后，直接支持在目标主机操作 我宿主机的环境操作不了 😢 

## 期望的结果

可以支持在宿主机操作

**Comment by vapao** [comment]
主机管理里配置的连接地址尽可能使用内网地址
