### ISSUE TITLE
能否支持使用私钥登录

### ISSUE THREAD

**Issue by vfoLee** [openspug/spug#56]
出于安全考虑，服务器已关闭密码登录，能否在主机管理中支持使用私钥登录的方式，否则无法添加主机

**Comment by linux724** [comment]
如果你服务器和要添加的主机之间做过密钥认证了。那么可以直接添加主机，不需要再次输入密码。

**Comment by zyupo** [comment]
如果你服务器和要添加的主机之间做过密钥认证了。那么可以直接添加主机，不需要再次输入密码。

**Comment by suntao098** [comment]
> 如果你服务器和要添加的主机之间做过密钥认证了。那么可以直接添加主机，不需要再次输入密码。

但是验证后>>首次输入需要验证码，但是root关闭了密码登陆，无法连上

**Comment by Lykan-sec** [comment]
同样的问题，主机关闭了密码验证，无法添加自己的私钥，强行修改数据库中的公私钥之后，仍然需要再去每台服务器上开密码登陆，然后配置完后再关闭密码登陆。
这个逻辑还是有点复杂，能否自行选择是否使用私钥登陆，没有私钥，再验证密码，添加私钥？

**Comment by fyhqycom** [comment]
通样的问题，目前所有机器都关闭了密码登录,可以选择私钥进行登录，有一个管理的地方。

**Comment by vapao** [comment]
目前可以直接修改数据库的 `settings` 表替换默认生成的密钥对，需要同时修改 公钥和私钥。后期可考虑由用户上传自定义的密钥对。

**Comment by runsisi** [comment]
使用私钥登录各被管理节点应该是 ops 系统非常正常的需求才对？ 这个不是默认的登录方式让我很吃惊 ：）

**Comment by vapao** [comment]
`v2.3.0` 版本开始支持上传自定义密钥。
