### ISSUE TITLE
npm install 这个步骤会导致磁盘io高

### ISSUE THREAD

**Issue by jiaoshengkang** [openspug/spug#560]
Spug 版本: v3.2.4

## 问题重现步骤

创建vue项目，其中npm install 这个步骤会导致磁盘io高
连续创建一个发布，先后一起开始执行发布。

## 报错/问题截图
磁盘io很高，不知道啥情况。

![lQLPJxaw2YHdnDXMm80HYLDsAt3GnRC6RAMi0RZXgOwA_1888_155](https://user-images.githubusercontent.com/15517273/190986009-e27326cb-566a-4b01-a725-9b7dadac6879.png)

## 期望的结果
能提供一点，找到为啥会这样的方向和思路。

系统用的是阿里云，Alibaba Cloud Linux（Alibaba Cloud Linux 3基于Anolis OS 8打造，兼容CentOS 8、RHEL 8生态。https://help.aliyun.com/document_detail/111881.htm?spm=a2c4g.11186623.0.0.3b005eb3jCjfeD#concept-rgv-rvd-2hb

**Comment by vapao** [comment]
这个应该是正常的， build 时cpu消耗也比较高，尽量避免多个应用同时发布。  我们也在开发远程其他主机上构建的功能，可以使这些操作在其他主机上执行。
