### ISSUE TITLE
Bug: 批量删除发布申请记录时，发布异常的记录没有被删除

### ISSUE THREAD

**Issue by imwower** [openspug/spug#561]
Spug 版本:  Spug API版本v3.2.4 Spug Web版本v3.2.4

## 问题重现步骤

1. 进行一次出现异常的发布；
2. 发布申请界面，点击“批量删除”；选择“发布配置”，选择应用和环境后，发布异常的记录没有被删除；

## 报错/问题截图
![WX20220922-170933](https://user-images.githubusercontent.com/1744486/191707814-34a8caf0-1e44-4ff6-97f9-8f25e69b5719.png)

## 期望的结果
想要删除某个环境时，需要先删除发布记录；
但是发布异常的记录没法删除；
导致该环境不能被删除；

**Comment by vapao** [comment]
应用和环境两个都要选的
