### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by feixia5712** [openspug/spug#563]
1 请问下大佬能不能增加个所有主机导出功能,
2 能不能增加个类似xshell工具，查看日志或者搜索得时候能不能选中就复制得功能
3 做主机权限得时候，除了对某个组赋权外，是否可以对某个组里面得ip赋权（可能开发需要临时登录某几台服务器查看,平时开发是没有任何权限登录生产环境得）

**Comment by vapao** [comment]
1. 是导出excel？
2. 你说的是web终端里吗？ 
3. 第3个问题没太明白，ip赋权是什么意思？

**Comment by feixia5712** [comment]
对某个组下得ip赋权，可以对整个组下得ip,或者对组下得某个ip
是导出excel
对web终端，选中就复制

**Comment by vapao** [comment]
组下的某个主机授权对吧，  这样的话其实更好的做法是创建个临时组，角色还是授权这个临时组， 有需要的时候把相关主机添加到这个临时组里。 右键点击分组名称 使用“添加主机”，这样也不会影响其他分组。

**Comment by feixia5712** [comment]
> 组下的某个主机授权对吧， 这样的话其实更好的做法是创建个临时组，角色还是授权这个临时组， 有需要的时候把相关主机添加到这个临时组里。 右键点击分组名称 使用“添加主机”，这样也不会影响其他分组。

目前我就是这样做得，这样倒是也可以

**Comment by zijiwork** [comment]
> > 组下的某个主机授权对吧， 这样的话其实更好的做法是创建个临时组，角色还是授权这个临时组， 有需要的时候把相关主机添加到这个临时组里。 右键点击分组名称 使用“添加主机”，这样也不会影响其他分组。
> 
> 目前我就是这样做得，这样倒是也可以
鲁班运维平台支持

**Comment by opcache** [comment]
> > > 组下的某个主机授权对吧， 这样的话其实更好的做法是创建个临时组，角色还是授权这个临时组， 有需要的时候把相关主机添加到这个临时组里。 右键点击分组名称 使用“添加主机”，这样也不会影响其他分组。
> > 
> > 
> > 目前我就是这样做得，这样倒是也可以
> > 鲁班运维平台支持

有批量脚本功能吗？可以对一些选定的主机做批量执行脚本，
任务管理--》创建和修改，删除任务（任务里面可以定义脚本和选择需要执行的主机一台或多台，和定时执行），
也可以手动执行任务；这个里面的批量执行功能
