### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by benzimu** [openspug/spug#564]
Spug 版本: v3.2.4

## 报错/问题截图

有个定时任务一直显示”执行中“，有办法停掉吗？

<img width="805" alt="image" src="https://user-images.githubusercontent.com/11267631/193018241-dce43566-8621-473b-a2a2-f9fd723f2c48.png">

**Comment by vapao** [comment]
目前spug上没有终止执行的功能，可以去目标主机上手工查看下是否有相关进程，如果没有可以忽略。
