### ISSUE TITLE
Bug: 全局变量为空

### ISSUE THREAD

**Issue by nice555** [openspug/spug#567]
更新3.0最新代码后，执行应用发布“发布前“和“发布后“获取不到全局变量

**Comment by vapao** [comment]
具体是哪里的全局变量？配置中心的还是默认的？  能否在发布任务里添加`env |grep SPUG` 然后执行发布后截图看下。

**Comment by nice555** [comment]
默认配置变量
![image](https://user-images.githubusercontent.com/30033923/197452109-e58d2543-aa40-4202-b449-ce42e604f0ed.png)

![image](https://user-images.githubusercontent.com/30033923/197452086-ed530f8e-f436-4415-83ac-67a749cf6e67.png)

**Comment by vapao** [comment]
这个是还未发布的版本，可以现在获取最新的，或者使用 `git checkout v3.2.4` 切换到正式版。
