### ISSUE TITLE
新建主机，无法添加局域网内其它服务器。Unable to connect...

### ISSUE THREAD

**Issue by mrp8ge8** [openspug/spug#57]
感谢开发大大，感谢docker，感谢#13 
Tips：官网上能否新增一个交流论坛？萌新太容易碰到问题了。

此问题我已经解决了，使用docker启动的时候，改一下网络参数：
`docker  run  -d  --network=host  reg.qiniu.com/openspug/spug`

会使用主机的四个端口：
--9001  py
--9002  py
--6379  redis
--80      nginx

**Comment by vapao** [comment]
Readme 下方有qq群哦
