### ISSUE TITLE
请教个部署问题

### ISSUE THREAD

**Issue by feixia5712** [openspug/spug#572]
我记得之前的版本不是compose部署的来着，现在改成compose了，我想使用外部的数据库，外部的redis,怎么搞啊，我记得以前是docker直接部署就可以了，然后改改配置重启就行，现在怎么搞，还是先只是单独跑一个spug的容器，然后进去修改可以吗？

**Comment by aaro-n** [comment]
我给你一些意见，仅供参考：
1.按照你说的方法，先执行`docker compose up -d`，后台运行spug，然后运行`docker ps`,找到容器的编号，想办法进入容器，修改后退出容器，执行`docker compose stop`停止容器，再次执行`docker compose up -d`，运行容器。
   缺点：每次Spug更新镜像，就要删除容器，更新镜像，运行新镜像，修改新容器。
2.使用`volumes:`命令，先运行容器，进入容器，找到要修改的文件并记下在容器中的位置，在vps上修改并保存，之后强制覆盖容器中的内容。
缺点：如果spug修改了代码，你又没注意到，又更新了spug，可能到时会出问题。
这只是简单思路，具体要怎么操作要自己找资料。
docker 命令也可以做到。

**Comment by feixia5712** [comment]
> 我给你一些意见，仅供参考： 1.按照你说的方法，先执行`docker compose up -d`，后台运行spug，然后运行`docker ps`,找到容器的编号，想办法进入容器，修改后退出容器，执行`docker compose stop`停止容器，再次执行`docker compose up -d`，运行容器。 缺点：每次Spug更新镜像，就要删除容器，更新镜像，运行新镜像，修改新容器。 2.使用`volumes:`命令，先运行容器，进入容器，找到要修改的文件并记下在容器中的位置，在vps上修改并保存，之后强制覆盖容器中的内容。 缺点：如果spug修改了代码，你又没注意到，又更新了spug，可能到时会出问题。 这只是简单思路，具体要怎么操作要自己找资料。 docker 命令也可以做到。

按照老办法搞还行吗，参考这个https://www.cnblogs.com/wt645631686/p/16484735.html  我记得我当初使用的3.1就是用这个来安装的

**Comment by feixia5712** [comment]
![image](https://user-images.githubusercontent.com/12670758/200716870-6ff83b9d-c351-46df-b7bf-02a46c12f68e.png)
这个写的是不是有点问题啊，我要是使用外部的redis的话，第一个必须修改setttings,py,第二个不建议修改settings.py

**Comment by feixia5712** [comment]
目前使用2.x的安装步骤还是可以的
