### ISSUE TITLE
请求失败: 400 Bad Request

### ISSUE THREAD

**Issue by walter0909** [openspug/spug#58]
登录时报错，未看到相应报错日志。version 2.2.4

**Comment by vapao** [comment]
如果安装官网的生产环境部署文档安装的话，报 400 一般是
![image](https://user-images.githubusercontent.com/10863906/80440419-5461e900-893b-11ea-82e0-496c78270172.png)
这里的 `ALLOW_HOSTS` 配置错误引起的，请设置成 `['127.0.0.1']` 或者 `['*']`
