### ISSUE TITLE
官方文档ssl证书过期，打不开

### ISSUE THREAD

**Issue by xiyuvi** [openspug/spug#582]
https://www.spug.dev/docs/about-spug/ 
官方文档ssl证书过期，还开了hsts，导致无法访问
![image](https://user-images.githubusercontent.com/38217058/210057230-0bd0aac4-7ffa-495e-baf8-9adfcf225461.png)
![image](https://user-images.githubusercontent.com/38217058/210057441-87ed1d26-cc72-4837-8011-898f0347d44d.png)

**Comment by vapao** [comment]
已更新，感谢反馈
