### ISSUE TITLE
Bug: 建议更改申请时间为准确的日期和时间

### ISSUE THREAD

**Issue by LazySongQ** [openspug/spug#587]
版本为v3.2.5，申请时间为几小时前、几天前，不能准确的知道是什么时间，希望优化一下。
另批量审核也建议添加一下---在大量审核出现的时候，一个个的点会很繁琐
发布配置可否增加一个批量修改的功能，例如我要给同一类型的java配置都要改一下内存设定，一个个点会很繁琐
![image](https://user-images.githubusercontent.com/83281049/216257967-7705ed10-c4b1-4d54-a831-f7803f4ac2d1.png)

**Comment by vapao** [comment]
鼠标放上去会展示详细时间，完整时间太占空间了
