### ISSUE TITLE
Bug:  在当前部署主机上，无法添加主机自身

### ISSUE THREAD

**Issue by ghost** [openspug/spug#590]
操作系统Linux-5.4.0-126-generic-x86_64-with-centos-7.9.2009-Core
--
Python版本3.6.8
Django版本2.2.28
Spug API版本v3.2.5
Spug Web版本v3.2.5

## 问题重现步骤

1. 将 Spug 部署在 2.2.2.2 
2. 然后添加主机 无法添加 2.2.2.2 提示，Exception: 连接主机超时，请检查网络，添加其他主机均正常。

**Comment by ghost** [comment]
有人知道吗

**Comment by ghost** [comment]
@zyupo 麻烦大哥空了帮忙看一下呗

**Comment by ghost** [comment]
> @zyupo 麻烦大哥空了帮忙看一下呗

好像和 DOCKER 环境有关，我是使用机器的内网IP才可以，大部分厂商机器内部只有一个内网IP然后公网IP是浮动附加上去的，你要添加主机内部的内网IP

**Comment by zyupo** [comment]
你首先包保证你docker主机是否可以ssh登录成功。你可以在spug部署的主机上手动ssh登录尝试，如果可以登录，那正常就可以添加成功。
你也可以根据官方文档检查一下容器里的sshd配置。
参考链接：https://spug.cc/docs/host-manage#%E9%94%99%E8%AF%AF%E8%AF%B4%E6%98%8E
