### ISSUE TITLE
Bug: 监控一个ip，在浏览器里访问都是200，spug监测请求都是403

### ISSUE THREAD

**Issue by jhlater** [openspug/spug#595]
Spug 版本:

Spug API版本v3.0.5
--
Spug Web版本v3.0.5

该地址为https地址，用postman和浏览器请求都是200的状态，但spug每次监测都是403状态，造成误报

## 问题重现步骤

1.
2.

**Comment by vapao** [comment]
403 应该从应用的日志里能看到具体的原因，这个我们也测试不了，你可以帮忙排查下问题，如果是spug的问题欢迎继续反馈。
