### ISSUE TITLE
Bug: 监控中心监控的网站证书到期报警异常，证书更新后依然报告证书错误

### ISSUE THREAD

**Issue by ghost** [openspug/spug#597]
Spug 版本: v3.2.5

## 问题重现步骤

1. 监控中心 - 站点监测 - 监控了一个网站 https 带证书的那种，今天刚好证书过期就正常报警了，然后更新了对应站点的证书，更新后本地浏览器检查都正常生效应用到新证书，但 Spug 里面还是显示证书错误，已尝试重启网站对应的服务器，Spug 也重启过，Spug 所在的服务器也尝试重启了，还是那样，看起来 Spug 监测证书好像里面有缓存，正常浏览器的话清理下缓存再访问新证书就生效了，Spug 这个应该如何清理这个缓存，或者说这是个 Bug 还是说只能一直等着缓存过期

## 提示信息如下：

HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: /xxxxxxx/ (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),))

**Comment by zyupo** [comment]
再观察观察，有问题在微信联系我们：spugdev
