### ISSUE TITLE
问题：请问怎么在命令行调用接口实现批量删除申请记录

### ISSUE THREAD

**Issue by wabksw** [openspug/spug#604]
Spug 版本:
![image](https://user-images.githubusercontent.com/46548315/233030037-18f943fe-6b3a-43fe-a254-f851844df1c9.png)

### 问题： 请问怎么在命令行调用接口实现批量删除申请记录，这样就不用每次都在web页面操作
![image](https://user-images.githubusercontent.com/46548315/233029239-3490fec4-6e8a-450d-8eda-b69de9898c83.png)

**Comment by vapao** [comment]
命令行会比较困难，因为接口需要认证
