### ISSUE TITLE
Bug: 发布的时候，因为文件已存在，一直停留在cp命令询问是否覆盖，无法中断

### ISSUE THREAD

**Issue by fmlgh** [openspug/spug#607]
Spug 版本: 3.2.7

## 问题重现步骤

发布时，cp命令如果没有强制覆盖，导致会一直停留在 cp：是否覆盖"./docker-compose.yml"？  这个地方。没有终止执行的操作？

## 报错/问题截图
![image](https://user-images.githubusercontent.com/50400417/236158874-3157b4d3-041c-4eb5-badf-048e7db440bd.png)

## 期望的结果
可以加个强制终止的操作

**Comment by fmlgh** [comment]
现在很尴尬，docker启动的，然后重启docker容器也不能停止它。我要怎么样停止掉它呢？

**Comment by vapao** [comment]
直接忽略这个发布记录吧，目前3.x 没有终止发布功能。

**Comment by fmlgh** [comment]
关键是，它是不是还有一个进程在服务器上面挂着啊？ @vapao
