### ISSUE TITLE
npm start 的时候报错,求解决

### ISSUE THREAD

**Issue by fuzhufang** [openspug/spug#62]
Compiled with warnings.

./node_modules/moment/src/lib/locale/locales.js
Module not found: Can't resolve './locale' in '/data/spug/spug_web/node_modules/moment/src/lib/locale'

Search for the keywords to learn more about each warning.
To ignore, add // eslint-disable-next-line to the line before.

**Comment by zyupo** [comment]
确认一下你node版本。环境需要Node 12.14以及以上版本。
