### ISSUE TITLE
使用Docker方式安装，持久化存储mysql报错bug

### ISSUE THREAD

**Issue by maiguangyang** [openspug/spug#66]
使用docker方式安装，本地数据持久化存储，接口请求报错：
```
{
    "data": "",
    "error": "Exception: (2002, \"Can't connect to local MySQL server through socket '/run/mysqld/mysqld.sock' (2)\")"
}
```

### 重现步骤

1、以本地数据持久化存储方式启动
```
docker run -d -p 80:80 -v /mydata/:/data reg.qiniu.com/openspug/spug
```
> 打开页面，登录使用，一切正常

2、查看刚刚启动的容器id，并停止该容器
```
docker ps
docker stop xxxxxxxxxxxx
```
3、再次使用步骤一的方式，启动
```
docker run -d -p 80:80 -v /mydata/:/data reg.qiniu.com/openspug/spug
```
> 打开页面，登录：报错：
```
{
    "data": "",
    "error": "Exception: (2002, \"Can't connect to local MySQL server through socket '/run/mysqld/mysqld.sock' (2)\")"
}
```

**Comment by maiguangyang** [comment]
> 补充一下

不管是主动删除容器，还是重启docke或者重启服务器导致容器清空，再次以持久化存储方式启动就报错了

**Comment by vapao** [comment]
非常赞的问题反馈，我们已经定位并修复了这个问题，请更新镜像的新版本即可。
> 因为 七牛官方的问题，我们已经把镜像地址更改为了 阿里云的镜像服务地址，请只 [spug.dev](https://spug.dev/docs/install-docker/) 获取新版镜像。

**Comment by fyhqycom** [comment]
使用新版测试还是报一样的错误
docker run -d -p 80:80 -v /mydata/:/data registry.aliyuncs.com/openspug/spug

Exception: (2002, "Can't connect to local MySQL server through socket '/run/mysqld/mysqld.sock' (2)")

**Comment by vapao** [comment]
先关闭这个问题了，如果需要帮助可以再重新打开

**Comment by hello--world** [comment]
使用[这个方式](https://spug.dev/docs/install-docker/)安装一样有以下问题

`Exception: (2002, "Can't connect to local MySQL server through socket '/run/mysqld/mysqld.sock' (2)")`

**Comment by vapao** [comment]
你这个容器启动时报的错还是重启时，可以发下docker images 的输出看下镜像

**Comment by hello--world** [comment]
登陆到时候报错
```bash
REPOSITORY                            TAG                 IMAGE ID            CREATED             SIZE
registry.aliyuncs.com/openspug/spug   latest              2f4ab8437e2a        18 hours ago        555MB
```

**Comment by hello--world** [comment]
添加这个到时候报错：`如果需要持久化存储代码和数据，可以添加：-v 映射容器内/data路径`

**Comment by jiangfei1995** [comment]
这个问题后来咋解决的，还是报错啊,mysql.sock不存在
