### ISSUE TITLE
发布应用失败错误提示

### ISSUE THREAD

**Issue by jjeejj** [openspug/spug#665]
执行应用发版的时候，增加拉取代码后的 钩子脚本，必须执行钩子脚本  成功之后，才能往下进行

现在的现象是：钩子脚本执行失败了，但是继续往下走下一步了，最后提示发布成功了

问题：如果在钩子脚本执行失败了的时候，终止执行 并提示失败

**Comment by zyupo** [comment]
如果是自定义发布的，可以在发布的钩子里最前面加set -e，脚本只要发生错误，就终止执行。
