### ISSUE TITLE
关于批量任务

### ISSUE THREAD

**Issue by Shuimo03** [openspug/spug#667]
Spug 版本: 3.x

## 问题重现步骤
如果想要批量修改主机IP，比如设置静态IP的时候，是需要编写一个bash吗？目前是在模板中添加/etc/sysconfig/network-scripts/ifcfg-ens160中内容，之后在修改UUID和IPADDR

## 期望的结果

能够批量修改主机IP

**Comment by zyupo** [comment]
这个需求可以通过自己写bash脚本，配合通过批量执行功能来实现
