### ISSUE TITLE
新建的角色，看不到"应用发布"里的内容。已添加功能权限和发布权限

### ISSUE THREAD

**Issue by a1258771** [openspug/spug#67]
![image](https://user-images.githubusercontent.com/10720556/81516612-08ffff80-936b-11ea-95dd-de6673519485.png)

**Comment by vapao** [comment]
发布权限里有两项 `环境` 和 `应用`，你应该是没有添加 `应用` 的权限。

**Comment by vapao** [comment]
`v2.2.6` 版本优化了这个问题，自己创建的环境 和应用自动具有相应的权限。

**Comment by vapao** [comment]
很久没收到你的回应了，暂时先关闭这个问题了，如需帮助请再次打开。
