### ISSUE TITLE
Bug: 连接外置mysql8数据库报错

### ISSUE THREAD

**Issue by zz950115** [openspug/spug#670]
Spug 版本: openspug/spug:latest

## 问题重现步骤

1.初始化数据报错，外置数据库版本8.0.35
2.

## 报错/问题截图
![image](https://github.com/openspug/spug/assets/138740429/04e4bb2b-74e6-4d89-ab8f-49a1a6d46ba0)
![image](https://github.com/openspug/spug/assets/138740429/0bc606cb-5563-4ff2-bef8-ea0282d59e18)

**Comment by zyupo** [comment]
4.0新版本会支持。
