### ISSUE TITLE
Bug: 主机管理-IP地址获取内网IP异常

### ISSUE THREAD

**Issue by janyyy** [openspug/spug#673]
Spug 版本:
![image](https://github.com/openspug/spug/assets/27274865/880195dd-49f9-49ec-abd1-93b304dc5678)

## 问题重现步骤

1. LINUX安装docker服务
2. 创建network
![image](https://github.com/openspug/spug/assets/27274865/5eaf69ac-9289-46bc-858f-a92c480b099c)

## 报错/问题截图
![image](https://github.com/openspug/spug/assets/27274865/c1d0e075-b905-4507-952d-fa3d356b00f2)

## 期望的结果
拿到eth0对应的内网IP地址

**Comment by vapao** [comment]
点击主机名称列，会打开侧边栏，列表页展示的第一个内网 ip，可以根据需要调整

**Comment by janyyy** [comment]
OK
