### ISSUE TITLE
【漏洞】命令注入

### ISSUE THREAD

**Issue by passer-W** [openspug/spug#678]
Spug 版本: 所有版本

## 问题重现步骤

/deploy/request/upload/ 路径存在命令拼接：
![image](https://github.com/openspug/spug/assets/83850502/a2fa85a0-fd41-4e7a-90d4-581971164e5d)
可在运维主机上执行命令，获取主机权限，以示例站为例：
![image](https://github.com/openspug/spug/assets/83850502/49a0f832-6925-435c-9583-020ff4295f38)

**Comment by writebai2** [comment]
这是运维平台，你认证主机用的是root账号，本身就已经信任部署supg的这台机器。而且执行这个指令，spug还有鉴权认证，跳过这个权限才能说注入，你本身就是supg用户拥有这个执行权，这不算一个漏洞。这种平台建议只对内部ip开放，放在公网上，如果平台本身有漏洞，管理的全部机器都得爆炸。
