### ISSUE TITLE
功能权限取消一些勾选后确定退出，再次点击进去仍然显示刚才勾选

### ISSUE THREAD

**Issue by jjjyyylll** [openspug/spug#69]
系统管理--角色管理--功能权限取消一些勾选后确定退出，再次点击进去仍然显示刚才勾选，但功能似乎是正常。

**Comment by zyupo** [comment]
https://demo.spug.dev
演示环境正常的。确认一下你版本是否最新的。如果不是最新版本可以参考官方文档更新到最新版本，再次验证试试看。

**Comment by vapao** [comment]
很久没收到你的回应，先关闭这个问题了，如果需要帮助可以再重新打开。
