### ISSUE TITLE
demo 演示地址

### ISSUE THREAD

**Issue by 521xueweihan** [openspug/spug#7]
您好：
感谢开源和分享 spug 项目，已收录到 HG 月刊。将于本月 28 号发布，阅读该项目过程中发现如下问题：
- 访问 demo 演示地址，显示：链接不安全。可能是服务器 https 证书配置有问题，用户可能会停在这个警告下，影响项目的推广。

**Comment by zyupo** [comment]
感谢您的提醒，https证书已经更新。

削微寒 <notifications@github.com> 于2019年2月26日周二 上午11:38写道：
