### ISSUE TITLE
这个项目是今年才开始开发的？

### ISSUE THREAD

**Issue by xiaohuazi123** [openspug/spug#72]
问题一：这个项目是今年才开始开发的？
我看contributor页，是2020年才开发的，
但是这个issue说已经用了1年了，issue时间是2018年
https://github.com/openspug/spug/issues/1
案例征集说稳定用了3年
现在感觉头好晕

问题二：批量执行是用的ansible吗
我看功能各方面都比较简单好用，不知道是否支持二次开发

**Comment by zyupo** [comment]
1、项目大部分代码来自之前公司的运维平台，差不多在2017年就开源了，开源后公司运维平台一直在继续运行使用。
2、批量执行没有用Ansible。使用的Python的Paramiko库，可以自己二次开发。

**Comment by xiaohuazi123** [comment]
就是现在系统前东家还在用，现在这个系统还有在维护吗？

**Comment by zyupo** [comment]
系统核心的代码就是你现在看到的Spug开源运维平台，Spug开源运维平台我们一直在持续维护。

**Comment by xiaohuazi123** [comment]
> 系统核心的代码就是你现在看到的Spug开源运维平台，Spug开源运维平台我们一直在持续维护。

好的，把核心代码开源了，而且也在持续维护，那就放心用了
