### ISSUE TITLE
发布申请页面增加审核人字段

### ISSUE THREAD

**Issue by haoyu36** [openspug/spug#77]
可否在发布申请页面中增加审核人字段

**Comment by vapao** [comment]
审核是可以选择开启和关闭的，当审核关闭时展示审核人就无意义了，而且目前页面已经展示了很多字段，再添加审核人会更拥挤，你有好的注意吗？

**Comment by haoyu36** [comment]
主要是考虑到有多人审核时如果不记录日志不方法审计

**Comment by zyupo** [comment]
可以把你想要的功能添加到投票页面，我们会综合考虑是否增加这个功能。
https://feathub.com/openspug/spug
