### ISSUE TITLE
角色 授权的时候不能点击

### ISSUE THREAD

**Issue by leijinrog** [openspug/spug#8]
角色 授权的时候不能点击
![image](https://user-images.githubusercontent.com/12710875/54346588-4fcb6a00-4680-11e9-9f6b-ff1432e4c63f.png)
有的是点了很多次 才能点上

**Comment by zyupo** [comment]
可能浏览器兼容性问题，建议用google浏览器。

**Comment by zyupo** [comment]
已经修复。
