### ISSUE TITLE
使用官方文档一键部署后，没法升级到最新版本

### ISSUE THREAD

**Issue by kenvin-feng** [openspug/spug#80]
使用了官方文档的$ curl https://spug.dev/installer/spug-installer | bash
安装部署完成后，查看版本是v2.2.4
现在想升级到最新版本，按照官方文档的命令，虽然显示升级成功，但是实际上并无升级。能否有什么解决方案呢？

**Comment by zyupo** [comment]
安装成功后，确认一下是否重启服务。

**Comment by kenvin-feng** [comment]
重启服务还是不行，我重新部署一套最新版本，将数据库备份还原。
