### ISSUE TITLE
新建的两个角色，其中另一个角色看不到"应用发布"里的内容。已添加功能权限和发布权限

### ISSUE THREAD

**Issue by lilianxiang** [openspug/spug#81]
新建两个角色devadmin，develop，devadmin可以看到应用发布内容，develop看不到，两个角色权限设置为一样也不行。版本是v2.2.6

**Comment by lilianxiang** [comment]
角色授权的 发布权限 里有一个应用权限的授权，加了就好了，感谢！

**Comment by vapao** [comment]
用户看到的发布申请受环境权限和应用权限的叠加影响，注意下看看是否没有分配发布权限里的应用权限。

<img width="501" alt="WX20200521-105145@2x" src="https://user-images.githubusercontent.com/10863906/82518062-18443180-9b51-11ea-87ff-2768cdfbd67e.png">
