### ISSUE TITLE
spug部署运行的资源占用情况

### ISSUE THREAD

**Issue by sure-one** [openspug/spug#87]
想了解一下spug各种方式部署运行时，对服务器的CPU、内存和磁盘的占用情况，没看到相关文档和issue，能否说明一下？

**Comment by vapao** [comment]
`Spug` 使用无Agent设计，正常运行中对CPU和内存使用会受用户设置的一些自定义命令的影响，比如在发布配置中使用 `npm build` 等CPU密集型任务时会看到明显的CPU使用率的上升。
批量执行、任务计划和监控模块都使用独立进程来避免影响页面的响应，甚至你可以把这些模块部署在独立服务器上来提升其性能。
磁盘使用方面`Spug` 所在服务器主要增长点是常规发布会`clone` 应用代码至服务器本地，目标主机则为发布的历史备份（备份数量可通过发布配置来设置）。

**Comment by vapao** [comment]
很久没收到回复先关闭问题了，有需要请再打开。
