### ISSUE TITLE
docker 启动

### ISSUE THREAD

**Issue by zsboss** [openspug/spug#89]
docker run -d -p 8088:8088 registry.aliyuncs.com/openspug/spug 映射成8088端口，访问不了
![image](https://user-images.githubusercontent.com/19493235/82981996-d23f1000-a01f-11ea-8fd4-a8fe3d266e79.png)
curl http://0.0.0.0:8088
curl: (56) Recv failure: Connection reset by peer

**Comment by zyupo** [comment]
docker内部端口默认启动的80，你需要-p 8088:80

**Comment by zsboss** [comment]
已经ok了。谢谢大佬
