### ISSUE TITLE
不能读取自定义的环境变量

### ISSUE THREAD

**Issue by haohedev** [openspug/spug#90]
我在被管理的服务器中设置了环境变量 （通过修改/etc/profile的方式），在被管理的机器上可以正常打印出设置的环境变量。 但是通过spug的执行任务中却不能看见自定义的环境变量

**Comment by vapao** [comment]
`Spug` 不会读取 `/etc/profile`, 你可以使用命令的绝对路径 或者 在发布时设置全局变量。

**Comment by haohedev** [comment]
好的，感谢~！
