### ISSUE TITLE
2.3.0版本文件管理器上传较大文件失败

### ISSUE THREAD

**Issue by ShiLiGo** [openspug/spug#97]
文件超过4M会报 413: "Request Entity Too Large"

**Comment by vapao** [comment]
这个受限于 `nginx` 的 `client_max_body_size` 配置的值，请更改这个值的小大， 例如 `client_max_body_size 100m;`

**Comment by ShiLiGo** [comment]
嗯嗯， 问题已经解决， 感谢。
