### ISSUE TITLE
2.3.0 使用docker 部署，容器需要手动配置 ssh

### ISSUE THREAD

**Issue by ChoGathK** [openspug/spug#98]
实测，在部署docker 后
需要进入容器内 手动配置或者生产秘钥对，
还要设置  chmod 0600 ~/.ssh/id_rsa 后 docker restart 容器，新建发布才可以使用.

**Comment by vapao** [comment]
容器生成密钥对，可以在容器内执行 `ssh-keygen` 来自动生成。
